### ISSUE TITLE
Misbehaving Resolution on Wide Monitors

### ISSUE THREAD

**Issue by osoleve** [nature-of-code/noc-book-2#1007]
Setup:
OS: Windows 11
IDE: VSCode + p5.vscode extension
(Possibly) relevant hardware: Laptop screen + 2x Dell S3221QS: one landscape, one portrait. Sketch output is on landscape monitor.

Behavior:
In Ch. 0, the code for the Perlin Noise pixel map produces an output that occasionally switches to being repeated 4x horizontally, and squished vertically to 25% of its height.

What worked for me:
Add `pixelDensity(1);` to `setup()`.

**Comment by shiffman** [comment]
Could you send a screenshot, I don't have a setup where I can reproduce. I wonder if this is a p5.js or JS/canvas bug rather than an issue with the nature of code examples specifically?

**Comment by osoleve** [comment]
Oh, sorry for not specifying, I very much think this is a bug in the software not the book's code, and that it might just be helpful to add a note about. Screenshots show before/after setting pixelDensity (been messing with the color value calculations and nosieDetail, which is why it looks nothing like the original example, but the issue is similar to the original).

![image](https://github.com/user-attachments/assets/c22794d7-dc5f-473b-8fb2-bfb3840970be)
![image](https://github.com/user-attachments/assets/d080e159-93a4-429f-9196-f5c9ac10041a)

**Comment by shiffman** [comment]
Thanks for reporting this and all of the details! I think since this isn't a bug for the nature of code I'll close for now. Perhaps it makes sense to report with the p5.js project? Or is it an issue with VSCode or HTML5 canvas / browser directly? I'm not sure!
