### ISSUE TITLE
PNG - generating programmatically

### ISSUE THREAD

**Issue by ppkn** [nature-of-code/noc-book-2#1010]
In 4.8 when discussing adding image textures to a particle system, you mention generating a png.
> You can create these textures in numerous ways: you can indeed make them programmatically within p5.js (I include an example on the book’s website)

However, I was unable to locate an example of programmatically making a png 😦

Maybe we could add a hyperlink to an example?

**Comment by ppkn** [comment]
I eventually found it at https://editor.p5js.org/codingtrain/sketches/NS4rB1Yx-

**Comment by shiffman** [comment]
Thanks for reporting this! I need to think about how to best include this on the website, I don't really have a place for extra examples. Maybe I can just adjust the text for the website to include a link to the sketch. @jasongao97 for some reason I've forgotten how to do this, is it just a matter of two different callout boxes one with `web-only` and one with `pdf-only`?

**Comment by shiffman** [comment]
Ok, I've incorporated this in Notion, maybe not the best solution, but it will do! Will check on the next build!

<img width="894" alt="Screenshot 2024-10-21 at 7 18 53 PM" src="https://github.com/user-attachments/assets/ca4d2ad0-57c3-4d6f-a443-fdae3c619575">

**Comment by shiffman** [comment]
This is now incorporated in the website!
