### ISSUE TITLE
Manual <br> tags aren't being ignored on Safari

### ISSUE THREAD

**Issue by ncho** [nature-of-code/noc-book-2#1020]
Related to https://github.com/nature-of-code/noc-book-2/issues/900: 

`<br>` tags aren't being ignored when reading the book on Safari. The tags are being ignored correctly when reading the book on Chrome. I encountered the bug when using Safari versions Version 18.0 (20619.1.26.31.6) (Sequoia) and Version 18.0 (19619.1.26.111.10, 19619) (Sonoma). 

<img width="950" alt="Screenshot 2024-09-27 at 3 43 43 PM" src="https://github.com/user-attachments/assets/d34f7969-41f8-4c2c-8e8a-9c36d1a9cc28">

**Comment by shiffman** [comment]
How strange, thank you for reporting this! @jasongao97 perhaps you can look into it?

**Comment by shiffman** [comment]
@ncho This has been addressed in #1040, please check and if it's working for you it can be closed!

**Comment by shiffman** [comment]
(Not working on the site, maybe due to caching issue, currently rebuilding.)

**Comment by ncho** [comment]
This looks good to me! I checked using Safari Version 18.0 (20619.1.26.31.6) (Sequoia) and Version 18.0 (19619.1.26.111.10, 19619) (Sonoma). The below screenshot is from the first version. 

I'm closing this now, but please feel free to reopen if you're seeing anything different. I'm looking forward to finishing the book! 

<img width="1000" alt="image" src="https://github.com/user-attachments/assets/3a256445-2ec9-4659-8825-54b340635d7e">
