### ISSUE TITLE
Exercise Solution Discussion

### ISSUE THREAD

**Issue by tuantinghuang** [nature-of-code/noc-book-2#1025]
### Summary of current exercise formats:

1. Text + code with fill in blanks<img width="691" alt="Screenshot 2024-10-07 at 16 57 55" src="https://github.com/user-attachments/assets/8e23c998-c91c-4412-b199-a4fb5fe8bdfc">
    
2. Text with a linked sketch as part of the prompt<img width="691" alt="Screenshot 2024-10-07 at 16 58 21" src="https://github.com/user-attachments/assets/b538bb58-2533-47e1-a78c-ec792d5774e6">

3. Text only (Open question)![Screenshot 2024-10-07 at 17 04 20](https://github.com/user-attachments/assets/214bc408-ab95-427c-97c7-89ee2842700a)

<hr> 

### Mockup design for links to solution 
If we are to compile an index page for exercise solutions, here's a proposed design of how we can link to the solution from the exercise, similar to how we have "copy/reveal answer." (Question: Does this link to the solution page, or directly to p5 sketch?)

<img width="691" alt="Screenshot 2024-10-07 at 16 58 08" src="https://github.com/user-attachments/assets/67b478da-3302-4360-b0aa-a91c8ca0511c">

<hr>

### How to format the solution sketches in Notion?
Similarly to how we attach a sketch to an exercise, can we also place the sketch link as a bookmark in the exercise block , and add a label/callout (ex: `web-only`) so it renders as a link ("suggested answer") instead of showing the sketch? Also we can use the label to keep track of what we have only for the website, and not included in the printed version.
 
Something like this maybe?
<img width="738" alt="Screenshot 2024-10-04 at 11 19 19" src="https://github.com/user-attachments/assets/d5b63c2e-3ef4-4fa5-887c-0aff679c45f8">

**Comment by shiffman** [comment]
This works for me! I think the the "suggested solution" should link directly to a p5.js sketch.

**Comment by shiffman** [comment]
Noting this is a continuation of the discussion in #55

**Comment by shiffman** [comment]
So we're going to try the web only tag and implement this!

**Comment by shiffman** [comment]
@tuantinghuang might as well as an explanation of how to submit an exercise solution on the README as well.

**Comment by shiffman** [comment]
Noting the last piece here is to implemented the "suggested answer" label for when there is a "web only" exercise solution.

![image](https://github.com/user-attachments/assets/e70db801-36fe-4e12-9c99-4dfc53166c09)

**Comment by shiffman** [comment]
We're also going to add text based solutions with a "reveal answer" button, the proposed format in Notion is as follows:

![Screenshot 2024-11-04 at 9 22 40 AM](https://github.com/user-attachments/assets/e4d56fab-35d9-4b23-a09b-051c90afcc58)

(This is the solution from #1038)

**Comment by shiffman** [comment]
One more note is that the exercise p5 sketch embeds that are now marked with "web-only" should be hidden on the chapter pages and let's use another tag as with the text solutions above! 

* `solution` - text based exercise answer (label "reveal answer" reveals the answer)
* `p5-solution` - p5 sketch (label "suggested answer" link to p5 web editor)

Ok, I think we are all set with this!

**Comment by jasongao97** [comment]
Some update on this:

> `solution` - text based exercise answer (label "reveal answer" reveals the answer)
> `p5-solution` - p5 sketch (label "suggested answer" link to p5 web editor)

In the #1053 implementation, instead of using separate `solution` and `p5-solution` tags, I've opted for a unified `solution` tag where the type is inferred from the content. This approach should provide better consistency and simplified maintenance.

**Comment by shiffman** [comment]
I think this solution is great, closing!!!
