### ISSUE TITLE
Exercise 0.1 and its reference to Example 0.3: A Walker That Tends to Move to the Right

### ISSUE THREAD

**Issue by brandtryan** [nature-of-code/noc-book-2#1034]
Exercise 0.1 has reader create a walker that tends to move **down and to the right**, and points to solution in next section Example 0.3.

![image](https://github.com/user-attachments/assets/8e203cd9-a347-46fd-939e-b5632bade6c9)

![image](https://github.com/user-attachments/assets/0e020bcf-9656-465b-ad1c-e8bcc1abe74d)

Just pointing out that the Example  0.3's title and content show walker that tends to move **to the right** only (not down as well). This problem (if it is one) is also in the physical book.

**Comment by shiffman** [comment]
Ah, thank you! Maybe I'll just change it to "a partial solution"

**Comment by brandtryan** [comment]
> Ah, thank you! Maybe I'll just change it to "a partial solution"  

That's a great idea - another opportunity to train the brain!

BTW, I have a background in editing and am very critical in the academic sense (and am often wrong!)

And when the manual/book/manuscript is about something I'm super interested in it's like:
```js
criticismFromBrandt.mult(5000)
```
I have super tough skin (having been critiqued for 3 years in an M.F.A program!), so please ignore without hesitation any concern I may bring up with no hard feelings! **A** of all, you are the author of course, and **B** of all, there's a good chance any concern I bring up may be due to "user error" :)

**Comment by shiffman** [comment]
Haha, I appreciate it! It's helpful to have this feedback, and I am grateful for your close reading! I'm focusing on other projects now that the book is published so I may not reply or address some of the notes quickly but if/when there is a second printing you can be sure I will!

**Comment by shiffman** [comment]
Changed in Notion and added to [Errata](https://github.com/nature-of-code/noc-book-2/blob/main/errata.md). Will be updated on the next website build.
