### ISSUE TITLE
Code block with wrong character in chapter 0

### ISSUE THREAD

**Issue by sidwellr** [nature-of-code/noc-book-2#1037]
In chapter 0, the code block shortly before example 0.2, the minus signs are entered as en-dashes. This doesn't affect the printed version (unless you look very carefully), but copying/pasting the code block from the web site doesn't work correctly. Please change the three en-dashes to minus signs.

```
  step() {

    let xstep = random(–1, 1);
    let ystep = random(–1, 1);

Any floating-point number from –1 to 1

    this.x += xstep;

    this.y += ystep;

  }
```

**Comment by shiffman** [comment]
I have fixed this in Notion and updated [the Errata page](https://github.com/nature-of-code/noc-book-2/blob/main/errata.md). Will close after the next website build.

**Comment by shiffman** [comment]
Should be set now!
