### ISSUE TITLE
Tweaks to font

### ISSUE THREAD

**Issue by zee-em** [nature-of-code/noc-book-2#117]
In addition to modifications to the numeral 4 (open at top, wider cross) what are other changes we should make? 

samples: 

<img width="994" alt="Screen Shot 2022-10-12 at 1 42 50 PM" src="https://user-images.githubusercontent.com/13405058/195412922-ec3c4b35-af4f-4157-aa79-2a6a2b149963.png">
<img width="995" alt="Screen Shot 2022-10-12 at 1 43 11 PM" src="https://user-images.githubusercontent.com/13405058/195412895-7921ee85-0135-4dec-815d-8d09c04869ac.png">
<img width="895" alt="Screen Shot 2022-10-12 at 1 51 11 PM" src="https://user-images.githubusercontent.com/13405058/195414135-b3980257-16bd-4047-88f3-e45701415e6a.png">

[.otf file is here. ](https://drive.google.com/file/d/1P09EBvonn9cNY9dXPJmeBWnuLO9h6HVK/view?usp=sharing)

**Comment by zee-em** [comment]
Also... note that I'm currently using this at 12 pt in the illustrations and diagrams.

**Comment by shiffman** [comment]
This looks great! I quickly scanned over the full book and here are some things I found that might need to be addressed by the font (though you could always just sketch them instead?)

1. superscripts and subscripts. Lots of the formulas use superscript and subscript for things like `Fg` or `x squared`.

<img width="157" alt="Screen Shot 2022-10-17 at 11 35 35 AM" src="https://user-images.githubusercontent.com/191758/196221908-b2fa8335-9b0c-44c7-ae53-78cce0b7e8cd.png"> <img width="174" alt="Screen Shot 2022-10-17 at 11 36 02 AM" src="https://user-images.githubusercontent.com/191758/196221965-00f7fc18-1ec7-4724-b1a2-fe4c6f003a32.png">

2. Greek letters like theta, PI, and mu (those are all I found but maybe I missed one?)

<img width="204" alt="Screen Shot 2022-10-17 at 11 36 18 AM" src="https://user-images.githubusercontent.com/191758/196222127-6c7b15ed-8536-4049-a33b-4842d64ac5df.png"> <img width="223" alt="Screen Shot 2022-10-17 at 11 36 52 AM" src="https://user-images.githubusercontent.com/191758/196222183-ae825516-11a7-49a2-9589-4c785fa42e94.png"> <img width="162" alt="Screen Shot 2022-10-17 at 11 37 37 AM" src="https://user-images.githubusercontent.com/191758/196222333-22fa2898-c72e-4223-b54e-ee0d0f0bd295.png">

3. vector notation. This involves an arrow over a letter, a `^` over a letter (for "unit vector") and also the double pipe for vector magnitude: `||v||`.

<img width="137" alt=" Screen Shot 2022-10-17 at 11 35 32 AM" src="https://user-images.githubusercontent.com/191758/196222579-77648a33-12f8-4d01-b563-a7a12ff75f05.png"> <img width="387" alt="Screen Shot 2022-10-17 at 11 36 27 AM" src="https://user-images.githubusercontent.com/191758/196222640-ce2d7f57-f1b8-49bc-8a5a-084c1e521fb9.png">

Here's another reference for some of the above elements:

<img width="505" alt="Screen Shot 2022-10-17 at 11 38 25 AM" src="https://user-images.githubusercontent.com/191758/196222840-10de2407-3cdc-4d5d-9555-ea242fde0bee.png">

Also, this is a good one to maybe just see how a bunch of text looks like together?

<img width="584" alt="Screen Shot 2022-10-17 at 11 39 13 AM" src="https://user-images.githubusercontent.com/191758/196222917-6f4cdad6-cc87-43fd-9b57-8a63779626d8.png">

One other note is the spacing (leading?) around the `y` looks a bit odd in the samples? too much space before the y?

**Comment by zee-em** [comment]
OK, I went ahead and updated the 4. Procreate doesn't immediately seem great with special characters, so I'll go ahead and draw the other special characters.

Here's a test with 8-13 as requested! 
![Figure8-13](https://user-images.githubusercontent.com/13405058/197305564-ab28c72e-ebab-4e7c-8361-017a56a00158.png)

**Comment by shiffman** [comment]
Looks great!!! @jasontheillustrator do you mind taking a look at this as a third pair of eyes before we lock it in? Any thoughts or feedback?

**Comment by jasontheillustrator** [comment]
It all looks pretty good to me. The change to the 4 was a good one. The new 4 seems more readable.

I was just thinking about the Procreate process for the special characters. Text in Procreate is pretty cumbersome. If you were to export your Procreate image as a JPG, you could link that to a layout file in InDesign and use InDesign's more advanced font system to add in those special characters. That way you wouldn't need to draw a bunch of special characters by hand.

**Comment by shiffman** [comment]
@zee-em I believe this can be closed as we are all set with the font? Re-open if I'm missing something!
