### ISSUE TITLE
Figure Intro.4

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#124]
![image](https://user-images.githubusercontent.com/191758/198083814-02c274b8-450d-4541-b97d-ae562bc1a307.png)

* half width 
* line should be at 45 degree angle (and graph is a square)
* axes should be labeled x and y, tick marks on both at same scale
* labels should be "probability" and "value"

**Comment by shiffman** [comment]
in progress!

![image](https://user-images.githubusercontent.com/191758/213261982-f9c96a3f-080b-430e-a581-aa5c298e6a96.png)

Needs "value" label of x-axis

**Comment by zee-em** [comment]
updated and uploaded

**Comment by shiffman** [comment]
Perfect!
