### ISSUE TITLE
surface area dated reference

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#134]
> An aerodynamic Lamborghini, for example, will experience less air resistance than a boxy Volvo. Nevertheless, for a basic simulation, I will consider the object to be spherical and ignore this element.

Dated reference or charming? Maybe something less sports-car-y would be nice here.

**Comment by joeyklee** [comment]
Ha! Maybe my imagination is failing me, but what might other comparisons of aerodynamic things be? 

* Cyclists // racing bikes vs beach cruiser?
* Fish be pretty aerodynamic?
* ???

**Comment by shiffman** [comment]
Here's the new paragraph!

> `A` refers to the frontal surface area of the object that is pushing through the liquid or gas. Consider a flat sheet of paper falling through the air and compare it to a sharp pencil pointed straight down. The pencil will experience less drag. Again, this is a constant and to keep things simple, I will consider all objects to have a spherical shape and ignore this element.

Closing but I welcome additional feedback!
