### ISSUE TITLE
Update all references to p5 library to full name: "p5.js"

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#144]
I sometimes say "p5" and sometimes "p5.js" when referring to the aforementioned library. I should probably be consistent. I lean towards using "p5.js" everywhere?

**Comment by joeyklee** [comment]
In this case, I would go for p5.js to keep it as clear as possible.

**Comment by shiffman** [comment]
Went through and updated all remaining "p5" references with "p5.js"!
