### ISSUE TITLE
Closing remarks reminder

### ISSUE THREAD

**Issue by joeyklee** [nature-of-code/noc-book-2#146]
See: https://github.com/nature-of-code/noc-book-2/pull/79#discussion_r309427933

* Note: we kept in some of those closing remarks in chapter 10, but wanted a reminder to move them to chapter 11 when the time is right.

**Comment by shiffman** [comment]
Noting that the current plan is to fold neuro-evolution into chapter 10 (rather than break out into a separate chapter 11)

**Comment by shiffman** [comment]
back to having a chapter 11 and it's all done!
