### ISSUE TITLE
relationship between mass and radius

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#147]
Noting that in my examples I just use a multiplier to tie radius to mass.

```javascript
    this.radius = mass * 8;
```

Another, perhaps more accurate, way to approach this would be to consider surface area as corresponding to mass which would involve taking the square root (`area = πr²`).

```javascript
    this.radius = sqrt(mass) * 8;
```

This would need to be addressed in the text and examples.

**Comment by joeyklee** [comment]
@shiffman - Oh yes, this is a great thing to update as it creates a better visual mapping to the size of the circles.

**Comment by shiffman** [comment]
I decided to add this as an exercise? Maybe it's too easy if I provide this hint?

<img width="917" alt="Screen Shot 2023-02-11 at 3 03 23 PM" src="https://user-images.githubusercontent.com/191758/218278882-dc714902-4cf9-48cc-8cf4-47174aeceaf7.png">

There is also a reference earlier in the chapter now.

<img width="765" alt="Screen Shot 2023-02-11 at 3 04 24 PM" src="https://user-images.githubusercontent.com/191758/218278909-c786dde6-e2db-4b41-8373-a8f3a6be7aec.png">

Leaving open for comment.

**Comment by shiffman** [comment]
I did another pass over this language will be published to the new website shortly! Closing!
