### ISSUE TITLE
Gas scenario in Chapter 5

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#152]
Maybe a more environmentally friendly scenario would be nice? Or weave something in about sustainability and public transportation, etc.

> **_Feedback_**: Complex systems often include a
feedback loop where the output of the system is fed back into the
system to influence its behavior in a positive or negative direction.
Let’s say you drive to work each day because the price of gas is low.
In fact, everyone drives to work. The price of gas goes up as demand
begins to exceed supply. You, and everyone else, decide to take the
train to work because driving is too expensive. And the price of gas
declines as the demand declines. The price of gas is both the input of
the system (determining whether you choose to drive or ride the train)
and the output (the demand that results from your choice). I should
note that economic models (like supply/demand, the stock market) are
one example of a human complex system. Others include fads and trends,
elections, crowds, and traffic flow.

**Comment by joeyklee** [comment]
@shiffman - A few ideas:
1. climate change related: green house gas forcings  (maybe too obscure but could be educational about complex feedback mechanisms) 
2. machine learning related: (could also be too complex for a short paragraph)
3. public transport: 
  * how to increasing public transport use / motivate  public: 1. add more coverage, 2. dedicated public transport lanes, 3. reducing cost, 4. adding accessibility, 5. ...
4. controlled burns - in places like california or the mediterranean, plants are adapted to grow and spread seeds through fires. Small controlled burns could help prevent massive fires in these climates. 

lots of ideas!

**Comment by shiffman** [comment]
Ok! I have rewritten this paragraph to focus on public transportation, I welcome additional  feedback or comments! I wonder if there is a way for me to mention that there are ways the infrastructure could be improved without burdening the commuter with the cost!

> Feedback. Complex systems often include a feedback loop where the output of the system is fed back into the system to influence its behavior in a positive or negative direction. Let’s say you take public transportation to work each day because it’s the most reliable and cost-effective solution. In fact, everyone starts to take public transport as traffic congestion is reduced and it becomes even more efficient and attractive. However, as the popularity increases, the system may struggle to accommodate the rising demand, leading to overcrowding, delays, and increased fares to fund infrastructure improvements. As a result, you and others start to switch back to driving, thereby increasing traffic congestion and reducing public transport's efficiency. As traffic worsens, the funds from increased fares are (hopefully) used to improve public transport infrastructure, making it more appealing once again. In this way, the cost and efficiency of public transportation is both the input of the system (determining whether you choose to use it or not) and the output (the degree of traffic congestion and subsequent cost and efficiency). I should note that economic models are just one example of a human complex system. Others include fads and trends, elections, crowds, and traffic flow.

**Comment by shiffman** [comment]
closing this one!

**Comment by joeyklee** [comment]
Nice one!
