### ISSUE TITLE
sin/cosine lookup table example

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#154]
The old Processing wiki with more info no longer exists, I should build out the example and include it as part of the book itself.

**Comment by mikakruschel** [comment]
There is an archived version of this site: http://web.archive.org/web/20130510100827/http://wiki.processing.org/w/Sin/Cos_look-up_table

And I made a js version of the sketch: https://editor.p5js.org/mikakruschel/sketches/Ag6QMqDE

**Comment by shiffman** [comment]
Thanks for this! It's now included as Example 5.12 with some minor adjustments, the code comments credit you with the port. I may simplify it further but resolving for now! Thank you! 

https://editor.p5js.org/natureofcode/sketches/uqRJyVq8g
