### ISSUE TITLE
Tables with Code Snippets

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#160]
The new Chapter 6 includes tables with code snippets. Code blocks inside a table in Notion are not supported so we'll need to decide how we want to handle this. I'm putting them in as "inline" for now, but we could also use something like `[code]` in the header row to indicate a CSS class for the table? (similar to how we work with CSS classes for figures).

<img width="731" alt="Screen Shot 2022-11-02 at 12 25 11 PM" src="https://user-images.githubusercontent.com/191758/199545583-5116a9df-d687-44dc-b9cd-c28e58375b64.png">

**Comment by jasongao97** [comment]
How do you think adding the notation mark to the code which makes them a `block level`? So both inline and block types can exist in the same table. Something like a comment `// [block]` or `// {block}` before the snippet to match the style of codesplit.

<img width="697" alt="image" src="https://user-images.githubusercontent.com/6762203/201122447-53b91735-0940-447d-848e-63d6736c9327.png">

**Comment by shiffman** [comment]
Yes, this would work great, thank you!
