### ISSUE TITLE
Figure 1.16 - Ecosystem Project illustration

### ISSUE THREAD

**Issue by zee-em** [nature-of-code/noc-book-2#162]
Text says "Imagine a population of computational creatures swimming around a digital pond, interacting with each other according to various rules."

In step 1 of the exercise: "Develop a set of rules for simulating the real-world behavior of a creature, such as a nervous fly, swimming fish, hopping bunny, slithering snake, etc."

Questions:

- Do you want to keep the example to an aquatic ecosystem? Like, creatures in and/or on a pond?
- If so, should we replace bunny with something aquatic, like.... maybe capybara? 
- Or, are you open to other ecosystems, ie, forests or grasslands, etc?
- Should the illustration depict the examples given in the exercise instructions? 
- Should the illustration only include creatures and behaviors, and no "set decoration" (like grasses, rocks etc)? 
- Do we plan to develop this visual example over the chapters through illustrations-- so this Ch 1 illustration might be simpler than the current version, but we might add to it for each chapter. For example: some visual illustration of forces (waves, wind) at end of Ch 2, oscillating caterpillar added at end of Ch 3, a flower releasing a particle system of pollen in Ch 4, etc. 

Let me know what you think :)

**Comment by shiffman** [comment]
Thank you this message! I'm excited to rethink and reimagine the ecosystem project. Responses below!

> Do you want to keep the example to an aquatic ecosystem? Like, creatures in and/or on a pond?

It does not have to be aquatic but whatever we choose should map nicely to a two-dimensional world. A pond works well b/c it is self-contained and can be viewed overhead. We could consider it to be a pond with a surrounding shore?

> If so, should we replace bunny with something aquatic, like.... maybe capybara?

Hah! Capybara is such a fun idea!

> Or, are you open to other ecosystems, ie, forests or grasslands, etc?

I am open to other ecosystems for sure! But I think a large expansive world is probably harder to create with the concepts and something smaller is best? Incorporating insects, bacteria, tadpoles, etc. I think makes the most sense?

> Should the illustration depict the examples given in the exercise instructions?

I think it can veer into additional territory but the two should match conceptually and include the same elements.

> Should the illustration only include creatures and behaviors, and no "set decoration" (like grasses, rocks etc)?

I think it's ok to have other elements! Maybe I can think about how to more specifically include exercises related to obstacles or sources of food, etc?

> Do we plan to develop this visual example over the chapters through illustrations-- so this Ch 1 illustration might be simpler than the current version, but we might add to it for each chapter. For example: some visual illustration of forces (waves, wind) at end of Ch 2, oscillating caterpillar added at end of Ch 3, a flower releasing a particle system of pollen in Ch 4, etc

I love this idea, let's do it!

Also, for inspiration, here is an artist who does a lot of work that I associate with the ideas in this exercise!

https://spacefiller.space/

**Comment by zee-em** [comment]
All ecosystem illustrations are complete. Please check them [here](https://www.notion.so/Eco-System-Project-0d2fc85a70314e568c0d2a1cc69fbfee), and if approved I will upload all to the main Notion.

**Comment by shiffman** [comment]
This is fantastic!!! A few comments:

Chapter 2: Maybe remove the squid?  For me it's better to reveal it in the context of chapter 3 (oscillation)? You could also then emphasize the fish going after the food. Oh, and could the bugs do the "dance" that is featured in illustration 2.10 (the left one probably)?

![image](https://github.com/CodingTrain/thecodingtrain.com/assets/191758/ad65eb74-1f18-4e55-b382-586302936454)


Chapter 3: Could you make the little bugs were more prominent (The fish and the food can be in the background)? With the bugs, could you draw something to visually show that their wings are flapping?  This is specifically in the oscillation prompt. And then the squid's legs appear as new here to represent the sine waves!

Chapter 6: I'm not seeing the physics libraries so much here. I think the Octopus does represent the "soft body character"  idea with tentacles quite well. Is there any way to show collisions somehow? I realize it's hard without this being animated. Could there be an obstacle the fish are bumping into?

**Comment by zee-em** [comment]
Chapter 2 changes:
![Ch_2_Ecosystem 7](https://github.com/nature-of-code/noc-book-2023/assets/13405058/3269150a-45d6-49eb-a2d1-963144a579f5)


Chapter 3 changes
![Ch_3_Ecosystem 11](https://github.com/nature-of-code/noc-book-2023/assets/13405058/8fe53200-f37f-4339-8e6c-2b5963d3ef35)


Chapter 6 changes:
![Ch_6_Ecosystem 3](https://github.com/nature-of-code/noc-book-2023/assets/13405058/d3c2c1e2-92e5-4fe3-a140-32a21edd5027)

**Comment by shiffman** [comment]
yes, i love these changes, wonderful! Let's add these into the main Notion pages!

**Comment by zee-em** [comment]
all uploaded :)

**Comment by shiffman** [comment]
Amazing! Closing this one out!!
