### ISSUE TITLE
Figure 3.3: 1 radian

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#170]
Let's make sure this is accurate! (Looks like it is, here's a reference)

<img width="194" alt="Screen Shot 2022-12-01 at 10 22 43 AM" src="https://user-images.githubusercontent.com/191758/205091283-f3e60fc4-612c-4fcc-aac1-71842030645b.png">

**Comment by shiffman** [comment]
TBD later, discuss placement of angle = 1 radian

**Comment by shiffman** [comment]
![image](https://user-images.githubusercontent.com/191758/213193863-a952d788-57d7-44b7-bb8c-1ef336fde1bb.png)

**Comment by zee-em** [comment]
Here's a version with the angle label inside the triangle (I think we had this previously). Could also bring the text lower, or angle it. ![image](https://user-images.githubusercontent.com/13405058/217134314-e644e62f-d5cf-4d51-b63b-20f2135b4dc7.png)

**Comment by shiffman** [comment]
I like this better! So sorry for the back and forth. I also think moving "radius" from the bottom line to the diagonal one will be more clear! What do you think?

**Comment by zee-em** [comment]
updated.
