### ISSUE TITLE
Appendix: Creature Design

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#175]
doc by @zee-em, think about how to integrate as website addition, appendix, or part of ecosystem assignment in intro

**Comment by shiffman** [comment]
This will be an appendix and referenced in Chapter 1 at the Eco-System prompt.

**Comment by shiffman** [comment]
The appendix text is now finalized and edited. @zee-em I assume you'll want to change out the images? We can discuss when you are back!

**Comment by shiffman** [comment]
This is completed and in copy edit!

**Comment by iyzg** [comment]
I see that there's an appendix html file in the repo, but I was wondering if it's been integrated into the website yet since I can't seem to find it.

**Comment by shiffman** [comment]
Just added it! https://nature-of-code-2nd-edition.netlify.app/appendix-creature/
