### ISSUE TITLE
Chapter 5 illustrations

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#178]
Starting with 5.1 @zee-em and I have already discussed a new vehicle design but I think there is also an opportunity for a redesigned "target", maybe something that is less evocative of "shooting a target"? Do we dare use a creature and a piece of food and not even bother with car imagery? I'm not sure, TBD!

![image](https://user-images.githubusercontent.com/191758/210807850-69794bef-7544-4bc0-98b1-e3f36e2c08f4.png)

**Comment by zee-em** [comment]
If you want to stick with a car, you could do a checkered flag or some kind of flag symbol to show the destination :)

**Comment by shiffman** [comment]
Oh that could work really well! It does, however, need a very specific spot (single point) that is the target. So having something with a "center" makes that a bit easier?

**Comment by zee-em** [comment]
@shiffman here are three options for vehicles and targets. 

The third version is a non-vehicle vehicle, a creature which I've labled mover but could have another name. The target is a snack. I like this connection to the ecosystem project. This mover can also be simplified into a triangle for later figures. 

These are just drafts so for final I would adjust the proximity of the labels to elements and could tweak size of vehicle/mover and target. 

Let me know what you think!

![Figure_5-1](https://user-images.githubusercontent.com/13405058/210890233-a6eb6fbf-ca7c-4e3c-b211-7d57a338122c.png)
![Figure_5-1b](https://user-images.githubusercontent.com/13405058/210890264-9ed18f31-abfb-4f23-8900-222d7e95b968.png)
![Figure_5-1c](https://user-images.githubusercontent.com/13405058/210890279-6cd58604-58b8-4c2c-ab4b-44bef91302cf.png)

**Comment by shiffman** [comment]
I'm having so much trouble deciding about this! I do love the third one!
The term vehicle is quite important and key to the historical context of Braitenberg's book and Reynolds' paper about steering behaviors. But I think we can take creative license with how we draw the vehicle and still call it "vehicle"! 

Right now I'm leaning towards the first mostly because I really love the flag. Then we can introduce the creature later in the ecosystem prompt?  But if you were excited about the creature design I am really on the fence! The target "snack" doesn't read for me though. Not sure how to improve it. 

While chatting on Discord today a viewer suggested a "map pin" as a target. I think I would prefer the flag but just in case you would like to try it @zee-em.

**Comment by zee-em** [comment]
FWIW I made the target into a strawberry for this one. Really just for the record.
![Figure_5-1c 2](https://user-images.githubusercontent.com/13405058/211432961-bcdd2e3f-7ce2-44f4-9b45-f894ded684f0.png)
But, I think it's fine to go with the car-- are you ok with the little exhaust puff in all these diagrams? I think it makes the visual more dynamic, and I don't think anyone will be confused by it (tho all the other extra elements-- arrows and labels-- are informational).

**Comment by shiffman** [comment]
No this is too good, I LOVE the STRAWBERRY TOO MUCH!

**Comment by zee-em** [comment]
Got it! Strawberry it is.
