### ISSUE TITLE
5.1 and 5.2 scale

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#179]
Would it make sense for illustrations 5.1 and 5.2 to be identical to each other (both full width?) with the only addition being the "desired velocity" vector in 5.2? 

I'm not convinced of this, just wondering.

<img width="729" alt="Screen Shot 2023-01-05 at 9 50 46 AM" src="https://user-images.githubusercontent.com/191758/210808412-f513fa9b-6f9c-4301-b5bf-5de04e60ad8d.png">

**Comment by zee-em** [comment]
I agree, I think this will look better, and be clearer.
