### ISSUE TITLE
5.6 and 5.7

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#182]
For these two illustrations the label on the left should be "max speed" (not desired). This is showing that the desired is equal to max speed in 5.6, but that it is not in 5.7 (and instead the length is relative to the distance to target).

![image](https://user-images.githubusercontent.com/191758/210810635-dec1e9fe-363f-4d2e-ace2-dd7c83594681.png)

![image](https://user-images.githubusercontent.com/191758/210810664-18087bee-5bb3-47b8-a591-c07eb1adda84.png)

**Comment by zee-em** [comment]
would it make more sense for these illustrations to be stacked in each figure, so you can better compare the distances to the target, from max speed to desired? 

is the leftmost illustration in each figure independent of the target, like just existing to show the max speed? are both vehicles in each figure the same vehicle, or different vehicles with different velocities in relation to the same target?

**Comment by shiffman** [comment]
Ah, yes, this might help! 

> is the leftmost illustration in each figure independent of the target, like just existing to show the max speed? are both vehicles in each figure the same vehicle, or different vehicles with different velocities in relation to the same target?

Correct, the idea here is to show how in 5.6 the desired velocity is always equal to max speed and in 5.7 it is not, but instead its length is calculated based on distance to the target. Both vehicles are the same so each diagram could work stacked and just having one vehicle.

**Comment by shiffman** [comment]
I think these might work best as half-width but related to #185 should we remove some padding around them?  Or should we leave them full-width and centered?

![Screen Shot 2023-01-18 at 9 07 28 AM](https://user-images.githubusercontent.com/191758/213192846-485527e9-fc89-4273-88f2-374c47fab7aa.png)

**Comment by shiffman** [comment]
We decided to merge these into one. It could be half width stacked or full width (probably half width)

**Comment by zee-em** [comment]
Updated- will upload later

**Comment by zee-em** [comment]
Completed.

**Comment by shiffman** [comment]
@zee-em Do you like how it looks with the layout? My only thought is maybe we need a little bit more space between the two? Or perhaps only the "max force" label and curly once? I'm not sure and happy also to leave it as is!

<img width="1417" alt="Screen Shot 2023-02-11 at 1 53 46 PM" src="https://user-images.githubusercontent.com/191758/218275992-6647dceb-90b7-4a89-a720-1208f116a572.png">

**Comment by shiffman** [comment]
illustration looks great now with layout and caption.
