### ISSUE TITLE
illustration padding

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#185]
@zee-em I'm noticing in chapter 5 some of the new illustrations leave a lot of extra whitespace between the paragraphs. This is due to the padding being present in both the image and the website design itself. I think we should probably remove it from the diagrams? Here are two examples:

![Screen Shot 2023-01-18 at 8 42 37 AM](https://user-images.githubusercontent.com/191758/213187189-eeca357a-2d39-4c10-a500-45bd3bc69379.png)

![Screen Shot 2023-01-18 at 8 43 02 AM](https://user-images.githubusercontent.com/191758/213187204-61bd65cc-35a2-4b79-8fbd-b1d89f20f54e.png)

@jasongao97 let us know if you have any thoughts!

**Comment by shiffman** [comment]
@jasongao97 I am also wondering if we can adjust the CSS so that the illustration vertically aligns with the paragraph it starts floating next to. This will help quite a bit with placing it properly in notion.

![image](https://user-images.githubusercontent.com/191758/213211709-66442fd7-a5da-4af2-b4e5-4157e072a0d6.png)

**Comment by zee-em** [comment]
We can adjust the spacing in the illos if need be, but I might not get to them all this week. Generally they have top and bottom whitespace of probably 80 to 120px, which is just how I visually centered the images as I was drawing them. the whitespace on the sides is depends on the illustration and centering it. We can decide on the right dimensions and then I can crop and re-upload.

**Comment by jasongao97** [comment]
> @jasongao97 I am also wondering if we can adjust the CSS so that the illustration vertically aligns with the paragraph it starts floating next to. This will help quite a bit with placing it properly in notion.

Yes! I've added a fix. #198

**Comment by shiffman** [comment]
@zee-em do we need to leave this open as a reminder in terms of padding in the illustrations or should I close?

**Comment by shiffman** [comment]
@tuantinghuang and I discussed this at our last meeting. Based on how the PDF layout includes vertical padding around the illustration, we should crop them as close as possible to the top and bottom of the drawing itself. @tuantinghuang is available to go through and crop them, but @zee-em I'm not sure how to best approach this with your process? if you like we can work from the google drive and replace any there and in Notion?

**Comment by shiffman** [comment]
These should all be done now! Let's all keep an eye out for any we might have missed during our final reviews of the PDF. Thank you @zee-em!!
