### ISSUE TITLE
Figure 1.9 switch to full width?

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#190]
With the current layout of the page I think maybe full width side by side might work better?

![Screen Shot 2023-01-18 at 10 14 45 AM](https://user-images.githubusercontent.com/191758/213209533-752386fe-cf73-4ea5-92b4-f2e35a77a31c.png)

**Comment by zee-em** [comment]
Updated-upload to Notion later

**Comment by zee-em** [comment]
Completed.

**Comment by shiffman** [comment]
Just missing the spaces between the characters in the equations? (See 1.5)

**Comment by zee-em** [comment]
Should be correct now. And seems to be 1.10 in Notion? Did our numbering change?

**Comment by shiffman** [comment]
Yes! Apologies, I've been rewriting chapter 1 and adding captions! I took 1.7a and made it officially 1.7 and bumped the rest up a number. Hope you are having a wonderful trip!!!
