### ISSUE TITLE
Figure 2.7 should include the mouse arrow

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#191]
![image](https://user-images.githubusercontent.com/191758/213210174-6fe59160-c287-48fb-a2d7-be2452a45ff4.png)

it's a callback to 1.14, but I think we don't need all the extra labels

![image](https://user-images.githubusercontent.com/191758/213210297-5369f6bd-370b-4831-8b1b-164cbbb2969c.png)

**Comment by zee-em** [comment]
Updated- will upload to Notion later.

**Comment by zee-em** [comment]
Completed

**Comment by shiffman** [comment]
I'm assuming this is a quick and easy thing? let's move that mouse arrow all the way close to the dot (matching the acceleration arrow).

**Comment by zee-em** [comment]
Updated and uploaded :)

**Comment by shiffman** [comment]
beautiful!
