### ISSUE TITLE
Figure 3.6 full width?

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#192]
Would this illustration benefit from being full-width and a wider triangle?

![Screen Shot 2023-01-18 at 10 26 40 AM](https://user-images.githubusercontent.com/191758/213212991-b69409c8-6438-4a07-8218-0251921dcd0b.png)

```
tangent(angle) = velocity.y / velocity.x
```

**Comment by zee-em** [comment]
Updated - need to upload to Notion.

**Comment by zee-em** [comment]
Completed

**Comment by shiffman** [comment]
oops, i think the velocity.x should be a dotted line like velocity.y?

**Comment by zee-em** [comment]
Updated and uploaded :)

**Comment by shiffman** [comment]
lovely!
