### ISSUE TITLE
Figure 3.10 half width?

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#193]
Would this figure be better as half-width?

![Screen Shot 2023-01-18 at 10 30 48 AM](https://user-images.githubusercontent.com/191758/213213865-67ef1426-3f71-4a31-b90f-3d427a91ff88.png)

**Comment by zee-em** [comment]
Complete

**Comment by zee-em** [comment]
Something additional to update here?

**Comment by shiffman** [comment]
I was wondering if 3.14 should be half-width too, but I think it might make more sense to make some of these decisions once the PDF layout is closer to complete and we see how it looks there. If you want to see how 3.10 looks half and 3.14 full right now you can go to this section: https://nature-of-code-2nd-edition.netlify.app/oscillation/#39-trigonometry-and-forces-the-pendulum

**Comment by zee-em** [comment]
I prefer half width for figure 3.14, but I'll wait to update after the PDF thing is sorted!

**Comment by shiffman** [comment]
This figure is now 3.10 and we will decide to crop it to half-width later when focusing on layout.

**Comment by shiffman** [comment]
This is now half-width. I think this is best although we may have to adjust the layout a bit. This will be addressed during the layout phase.
