### ISSUE TITLE
2.3 formula whitespace

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#196]
Tiny change for 2.3, possible to write with spaces as either:

`friction = -1 * u * N * v` or if that's too wide then `friction = -1*u*N*v`

![Screen Shot 2023-01-18 at 9 23 27 AM](https://user-images.githubusercontent.com/191758/213196396-52ee1ee6-7a77-4fe4-ab94-6b735e2a6bf5.png)

**Comment by zee-em** [comment]
Updated and uploaded to notion!

**Comment by zee-em** [comment]
Following up-- I am on plane Wi-Fi and it looks like uploads are not completing. Will try again when I'm on the ground.

**Comment by zee-em** [comment]
Looks like this upload went thru :)
