### ISSUE TITLE
Figure 2.8 - typo and resolution issues

### ISSUE THREAD

**Issue by fturmel** [nature-of-code/noc-book-2#199]
There is a typo in figure 2.8, and the lower left arrow is in a lower resolution (blurry) compared to the rest of the image.

https://github.com/nature-of-code/book-website-2nd-edition/blob/main/content/images/02_forces/02_forces_13.png

<img width="1194" alt="image" src="https://user-images.githubusercontent.com/4009209/213484058-370aaa76-39b2-4e07-b43e-f1325c59d39a.png">

**Comment by shiffman** [comment]
Thanks for taking a look at this! There's already a version with the fixed typo (I need to trigger the re-build of the site). But the low res arrow I didn't notice, tagging @zee-em just in case this is an issue she wants to fix!

![image](https://user-images.githubusercontent.com/191758/213486084-3a19c462-be82-4209-a3f8-a8d09a27c16b.png)

**Comment by fturmel** [comment]
Great, no problem!

**Comment by zee-em** [comment]
Updated and uploaded to notion!

**Comment by zee-em** [comment]
Following up-- I am on plane Wi-Fi and it looks like uploads are not completing. Will try again when I'm on the ground.

**Comment by zee-em** [comment]
Uploaded!

**Comment by shiffman** [comment]
Looks great! Hope you are having a great trip! (I won't comment on each one of these unless I have a question so you can assume an enthusiastic cheer and thank you each time an issue is closed!)
