### ISSUE TITLE
Instructions of embedded examples

### ISSUE THREAD

**Issue by jasongao97** [nature-of-code/noc-book-2#207]
Some of the examples contain instructions (as HTML `<p>` element) about how to interact with the sketch. e.g. 'Click mouse to apply wind force.', 'Drag the mouse to generate new vehicles.'

To adapt it to embedded examples on the website, I'm thinking about whether adding a caption under:

![image](https://user-images.githubusercontent.com/6762203/216179480-ce730fda-5a3c-4219-acf2-405a30c0d22f.png)

or drawing the text on canvas instead of calling `createP()`:

![image](https://user-images.githubusercontent.com/6762203/216180529-8a270f8b-f187-4030-9296-e6a91c36e2fd.png)

Which one would you prefer? @shiffman

**Comment by shiffman** [comment]
Ah, this is a great question! I'm not sure about this, my instinct says let's make it a caption? It can actually just be written into Notion and doesn't have to part of the p5 web editor example if that makes things simpler.

**Comment by jasongao97** [comment]
Got it! I'll manually copy those to Notion as captions.

**Comment by shiffman** [comment]
@jasongao97 should the `createP()` instructions be removed from the example or are they ignored when the website is built? Happy to close this issue if we're all set!

**Comment by jasongao97** [comment]
@shiffman Yes, the embed iframe will only include the canvas part, so other DOM elements won't be shown. For what I can remember, there is only one sketch (the monkey Shakespeare https://editor.p5js.org/natureofcode/sketches/q4F192JCV) that use paragraphs as main output and need to be adapted.

**Comment by shiffman** [comment]
Great, I will close this issue for now and I'm sure I'll end up revisiting the Shakespeare one when I get to chapter 10.
