### ISSUE TITLE
Exercise I.2 - object literal syntax is used instead of array literal

### ISSUE THREAD

**Issue by fturmel** [nature-of-code/noc-book-2#209]
Should be corrected to:

```js
let stuff = [1, 1, 2, 3, 3];
```

<img width="793" alt="Screenshot 2023-02-03 at 2 43 23 PM" src="https://user-images.githubusercontent.com/4009209/216693387-d149f48c-d52c-45fb-a336-6cc2c8d6ea47.png">

**Comment by fturmel** [comment]
And, just a thought, obviously feel free to dismiss... In the same exercise we'll never get `1` back from `random(1)`, it's exclusive while `0` is inclusive in that range of possible return values. Could be a nice thing to clarify.

It's also a bit ambiguous if a value of `0.60` would be considered "Singing" or "Dancing" in that last example. Comparison operators (greater or equal than, lesser than, etc) might be better?

<img width="795" alt="image" src="https://user-images.githubusercontent.com/4009209/216698633-b9f7a1c2-6440-474b-a07b-b9e7874ecad8.png">

**Comment by shiffman** [comment]
Fixed the array! You raise a really good point about the ranges, I could say:

- *greater than or equal to 0.00 and less than 0.60 (60%) → Singing*
- *greater than or equal to 0.60 and less than 0.70 (10%) → Dancing*
- *greater than or equal to 0.70 and less than 1.00 (30%) → Sleeping*

Does this make things more confusing?

**Comment by fturmel** [comment]
Yeah, you have to find the right balance between simplicity and depth of accuracy. Especially for the intro material.

More verbose, but I _think_ it's better. It could be worth asking a few juniors/beginners to see how they feel about it.

If you're looking for other options, I found this table showing different interval notations:

![image](https://user-images.githubusercontent.com/4009209/217558765-1efadd94-0d14-4ae0-9da0-032f7da2641a.png)

source: https://courses.lumenlearning.com/suny-osalgebratrig/chapter/domain-and-range/

**Comment by shiffman** [comment]
@Prof-Sears Would love your thoughts on this last question!

**Comment by Prof-Sears** [comment]
I recommend skipping interval notation for the introduction and use the edit you proposed.

One thing to consider is adding an appendix with math concepts. It would keep the flow of the coding sections intact while helping student who need the extra background. It could be a set of links to OpenStax books if you're looking to do it quickly.

Sorry it took so long to get back. My youngest son is finishing high school. We'll be going nonstop with activities until June 1st.

**Comment by fturmel** [comment]
> One thing to consider is adding an appendix with math concepts.

That's a great idea imo, maybe something in the style of https://github.com/Jam3/math-as-code? Sadly, the repo doesn't seem to be maintained anymore.

**Comment by shiffman** [comment]
Oh wow, the math is code repo is great! I like the idea of adding an appendix, I'm prioritizing edits and rewrites now but I can consider this once I've gotten through the bulk of this work!

**Comment by shiffman** [comment]
I think where I am landing with this is to leave the bullet points written informally to describe the concept, but have the code comments be precise.

<img width="780" alt="Screen Shot 2023-10-10 at 7 29 02 AM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/bdefa377-1052-4507-830e-f989af5b88d2">

Would welcome any last thoughts before I close this issue. Ran out of time for any kind of math appendix for the book, but that could 100% be part of the website. (Am considering a glossary for the website as well.) I can work on additional supplemental materials after the book heads off to print.

**Comment by fturmel** [comment]
Small corrections: the "Dancing" bullet should be 10%, and the second code comment should read "Greater **or equal** than 0.6 and less than 0.7" if you want to be exhaustive there.

**Comment by shiffman** [comment]
> Small corrections: the "Dancing" bullet should be 10%, and the second code comment should read "Greater **or equal** than 0.6 and less than 0.7" if you want to be exhaustive there.

Ah, thanks, updated!

**Comment by shiffman** [comment]
This has now been finalized, I left the text informal and then clarified specifically in the code comments. You can see the latest in the website build.
