### ISSUE TITLE
Example I.4 - code format issue

### ISSUE THREAD

**Issue by fturmel** [nature-of-code/noc-book-2#210]
Looks like the line of code is showing up in the comment column. The second argument passed to the function should also be `60` based on the description.

<img width="802" alt="Screenshot 2023-02-03 at 3 43 29 PM" src="https://user-images.githubusercontent.com/4009209/216707013-65d6bd3c-e626-4728-982a-8c98fea71786.png">

**Comment by shiffman** [comment]
This has been fixed in Notion. I'll leave open until the next site build to double-check. Thank you for catching this @fturmel!!

**Comment by shiffman** [comment]
Fixed!
