### ISSUE TITLE
Column Layout for p5 sketches

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#228]
In chapter 3, I tried placing three sketches as columns and it works great! However, the "open in web editor" text wraps creating a lot of extra vertical space.  Maybe we create an alternate design if the width is less than some threshold? 

<img width="818" alt="Screen Shot 2023-02-18 at 10 07 38 AM" src="https://user-images.githubusercontent.com/191758/219873215-ca4bd011-09ef-4c95-9ff3-6585b8e19744.png">

What do you think @jasongao97?

**Comment by jasongao97** [comment]
Sure! I got some idea here. Which one would you prefer?

<img width="799" alt="image" src="https://user-images.githubusercontent.com/6762203/220244068-4c33f6a4-169f-4561-af71-7a27876235e1.png">

**Comment by shiffman** [comment]
I think I like the left or middle one, do you have a preference in terms of consistency?  Either works for me!

**Comment by shiffman** [comment]
This is completed but leaving open until #280 is fully completed and I have a print figure for these three sketches.

**Comment by shiffman** [comment]
@tuantinghuang these extra sketches need individual screenshots for the PDF build. This is the web (under "static waves" in Chapter 3).

https://nature-of-code-2nd-edition.netlify.app/oscillation/#waves

<img width="813" alt="Screen Shot 2023-07-20 at 9 46 29 AM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/20c28a54-ed66-4490-ac60-16f64c2654a6">

https://editor.p5js.org/natureofcode/sketches/3msqsP8ZD
https://editor.p5js.org/natureofcode/sketches/S9l2FSS_M
https://editor.p5js.org/natureofcode/sketches/0oH4O6Y0d

**Comment by shiffman** [comment]
Added screenshots and "Figure 3.x" to the caption for these, leaving this open until the PDF is checked

**Comment by shiffman** [comment]
Leaving open until #464 is completed

**Comment by shiffman** [comment]
All set now!
