### ISSUE TITLE
fill in the blank exercises for website

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#232]
This is perhaps more of a note for the PDF layout? Something we need to take a look at is the design for "fill in the blank" exercises. In the print book it's meant to have enough space to actually write in the book. What should it look like there vs. the web version? Do we need special markup for it?

<img width="802" alt="Screen Shot 2023-02-23 at 10 52 51 AM" src="https://user-images.githubusercontent.com/191758/220960216-801b17c8-ebf7-495f-86a0-f4a6d2a4afe5.png">

cc @jasongao97 @tuantinghuang

**Comment by jasongao97** [comment]
How about we put answers with underline marks at the blanks, so we can have:

- A slightly larger blank space generated for the PDF
- A click-to-reveal feature for the website

![image](https://user-images.githubusercontent.com/6762203/221277932-f9fabaf6-0edf-4ee5-8f5e-bb34c9fe2b72.png)

**Comment by shiffman** [comment]
Oh I love this idea! This is great!

Related, I wonder if we should build in a design element for some exercises where you can click to a sample solution running in the web editor? I can add a bookmark web editor url? Then I suppose we would have to decide if we want to embed the solution running or if it's best not to see it but have the option to click and look?

**Comment by jasongao97** [comment]
Sure! I don't have any specific idea right now. A simple inline link for non-embedded sketch and a bookmark for embed sketch would do the job. Or we can make it more special for the exercises' callout blocks to have a more consistent look, like a button that jumps to web editor.

**Comment by shiffman** [comment]
@jasongao97 shall we finalize this? Let's not worry about my comment, I'll just add an embedded sketch if I want to include a solution.

**Comment by shiffman** [comment]
@jasongao97 Just wanted to bump this thread, I'm doing another pass over the introduction and chapter 1 and wanted to finalize the formatting for web and PDF of "fill in the blank" exercises:

<img width="764" alt="Screen Shot 2023-06-03 at 9 31 23 AM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/650ece78-2f75-4aad-a63d-25b15ccbd391">

**Comment by jasongao97** [comment]
Oh yes! I'll work on this right away.

**Comment by shiffman** [comment]
Hi @jasongao97, I believe this is finalized now for the PDF, but I will leave this open as a reminder to implement the "click-to-reveal feature for the website"? Or let me know if you prefer to track in a new issue.

**Comment by shiffman** [comment]
Let's start with a "toggle" interface elements to reveal/hide solution.

**Comment by shiffman** [comment]
This can be closed, yay, thank you @jasongao97!
