### ISSUE TITLE
Bulleted list of steps (Section 4.3)

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#233]
Here is an example of a list of steps where I'm using "latex" math formulas for a bulleted list of steps, probably something different would be more appropriate? It actually looks ok, but just feels strange to be using math formula notation here.

<img width="721" alt="Screen Shot 2023-02-23 at 11 08 41 AM" src="https://user-images.githubusercontent.com/191758/220966277-5f14816e-79ba-4a12-a057-9ec8395f002a.png">

cc @jasongao97 @tuantinghuang

**Comment by jasongao97** [comment]
What do you think to use plain bulleted list? Inline-equations can still be added for better looking math formulas.

<img width="615" alt="image" src="https://user-images.githubusercontent.com/6762203/221291657-33b85022-4fd4-4969-9a0e-212aad73f786.png">

```html
<ul>
  <li>
    when <span data-type="equation">i = 0</span> → Check particle A → Do not
    delete
  </li>
  <li>
    when <span data-type="equation">i = 1</span> → Check particle B → Do not
    delete
  </li>
  <li>
    when <span data-type="equation">i = 2</span> → Check particle C → Delete!
  </li>
  <li>Slide particles D and E back from slots 3 and 4 to 2 and 3</li>
  <li>
    When <span data-type="equation">i = 3</span> → Check particle E → Do not
    delete
  </li>
</ul>
```

**Comment by shiffman** [comment]
Yes, let's change this as suggested! @jasongao97 do you want to go ahead and update in Notion to test or shall I?

**Comment by jasongao97** [comment]
Yes! I've updated in Notion. Let's check in the next build and can be closed.

**Comment by shiffman** [comment]
Rewrote this as a table!
