### ISSUE TITLE
Code Comment attached to no code

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#238]
In Chapter 2, there is a code snippet where I write a note to explain that the code from the previous snippet is assumed. In Notion, I am writing this using the keyword `[inline]` (I think we may have had something for that in the previous edition of the book?).

@jasongao97 should we maybe adjust this to `{inline}`? We'll also need a design that maybe shows the comment highlighted but written across the full horizontal space?)

```
//{!1} The Mover is now called a Body
class Body {
	
  //[inline] All the other stuff from before

  //${!7} The attract function is now part of the Body class
  attract(body) {
    let force = p5.Vector.sub(this.position, body.position);
    let d = constrain(force.mag(), 5, 25);
    let strength = (G * (this.mass * body.mass)) / (d * d);
    force.setMag(strength);
    body.applyForce(force);
  }
}
```

<img width="817" alt="Screen Shot 2023-02-24 at 1 38 24 PM" src="https://user-images.githubusercontent.com/191758/221264088-e0ca7ac9-f9c0-4ecd-828b-49d65166a805.png">

cc @tuantinghuang

**Comment by jasongao97** [comment]
Sure! Let's change it to `{inline}`. The following is a screenshot of the previous version for reference.

<img width="829" alt="image" src="https://user-images.githubusercontent.com/6762203/221269468-f306e08e-5fae-4518-9e4f-5d95e2cc19a2.png">

**Comment by shiffman** [comment]
I've updated all references to `[inline]` to `{inline}`, I'll double check that it's working on the next build and close.
