### ISSUE TITLE
Unable to run the github action

### ISSUE THREAD

**Issue by jasongao97** [nature-of-code/noc-book-2#26]
I have imported all the contents in the [noc-book-2](https://github.com/nature-of-code/noc-book-2/tree/source/content) repository and successfully turn it back to HTML on my local side.

<img width="864" alt="Screen Shot 2022-05-09 at 10 05 50 PM" src="https://user-images.githubusercontent.com/6762203/167527983-904d614b-0c96-4bd9-bb5b-99d7f6a55373.png">

However, I failed to run the script with GitHub action. Is it something with my permission/settings?

<img width="854" alt="Screen Shot 2022-05-09 at 10 10 56 PM" src="https://user-images.githubusercontent.com/6762203/167528401-37f9d362-2569-4e2d-afcd-ca08f3e63bf1.png">

**Comment by shiffman** [comment]
Resolved with [93c7c1aff0889da5d61411608a288dc961a3802d](https://github.com/nature-of-code/noc-notion/commit/93c7c1aff0889da5d61411608a288dc961a3802d)
