### ISSUE TITLE
Chapter 6 Destructuring Callout Box

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#268]
@jasongao97 I think I messed up how this is supposed to be formatted, can you take a peek at it? It should be a callout box with a short code embed if that's possible?

Notion:
<img width="771" alt="Screen Shot 2023-03-20 at 5 33 30 PM" src="https://user-images.githubusercontent.com/191758/226470934-b02def2f-49d8-4663-a160-eaf4e8b77405.png">

Website:
<img width="811" alt="Screen Shot 2023-03-20 at 5 33 17 PM" src="https://user-images.githubusercontent.com/191758/226470961-088feb50-df6e-425e-87a9-6b4eeededc80.png">

**Comment by jasongao97** [comment]
Would you like to have this as a 'note' callout block? I think the following should work (I've changed it).

<img width="755" alt="image" src="https://user-images.githubusercontent.com/6762203/226472276-56390a37-4b0c-48d7-b273-cdb1032aedb0.png">

**Comment by shiffman** [comment]
Oh whoops, this was just a silly mistake on my part, I got the emoji icons confused!!!
