### ISSUE TITLE
Chapter 6 many sketches / page slowness

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#269]
@jasongao97 My new chapter 6 draft is live! I noticed the page runs very slow. This may be due to:

1) There are a ton of embedded sketches.
2) Lots of the sketches drop particles continuously and I may not have properly coded them to remove particles over time.

I also notice that a lot of sketches run and the settle into something static so by the time you scroll down to them there aren't particularly active. The reset button is perhaps enough here, but just wondering if we should revisit any lazy loading / unloading of the sketches?

**Comment by jasongao97** [comment]
Sure, I'd be happy to work on improving the loading/unloading plan. Also, how about we consider having all the examples start in a static state, and require a user to click a play button to begin? And embedded sketch as a figure may be better if they start automatically?

**Comment by shiffman** [comment]
I'm open to the idea of having them not start automatically, but let's hold that option for later and see how we can improve the performance first! I like the experience of the animations running while you are browsing the text without having to click to start them.

**Comment by shiffman** [comment]
I think this can be closed now, thank you @fturmel!!!
