### ISSUE TITLE
URLs in print vs. web

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#279]
I'm moving an email discussion @nheidelberger and I are having regarding how to handle URLs/links in the book text. @jasongao97 this follows up on our discussion at our meeting last week. From what I understand, it's best to just let the reader know there is something online and point to a top domain or quick way to search rather than a long URL to type out.

One way to handle this is to have two separate sentences, one for online and one for print. @jasongao97 should we use the existing system for doing this or do you have any different ideas?

@nheidelberger let us know if you have further comments or thoughts.

Here are some examples:

---------

ONLINE: The seminal work in L-systems and plant structures, [The Algorithmic Beauty of Plants](http://algorithmicbotany.org/papers/abop/abop.pdf) by Przemysław Prusinkiewicz and Aristid Lindenmayer, was published in 1990.

PRINT:  The seminal work in L-systems and plants structure, The Algorithmic Beauty of Plants by Przemsylaw Prusinkiewicz and Aristid Lndenmayer, was published in 1990 and is freely available online at _algorithmicbotany.org_.

---------

ONLINE:  If you’ve never worked with OOP before, you may want something more comprehensive; I’d suggest stopping here and reviewing this [video tutorial on the basics of ES6 classes](https://thecodingtrain.com/tracks/code-programming-with-p5-js/code/6-objects/2-classes) with p5.js before continuing.

PRINT:  If you’ve never worked with OOP before, you may want something more comprehensive; I’d suggest stopping here and reviewing this 'Objects' section of my 'Programming with p5.js' video course on _thecodingtrain.com_.

---------

**Comment by jasongao97** [comment]
Yes, I think the web-only/print-only callout blocks should works fine. One potential problem I can think of is it only support block level, so the whole paragraph need to be repeated. However, in my opinion, this is still a more favorable approach than introducing a new inline markup, as the latter can be difficult to remember and may complicate the overall process.

<img width="767" alt="image" src="https://user-images.githubusercontent.com/6762203/230246114-eda96448-2efb-44f3-8e69-71d929189587.png">

**Comment by shiffman** [comment]
Alright, let's go with this, I would like to try to minimize the use of separate paragraphs, however. @jasongao97 can we also change the Notion -> PDF build to remove any hyperlinks? So in theory I could actually just use the bottom paragraph for both but have it actually link for the web version. I'll leave this open since I need to go back and adjust earlier chapters according to this methodology.

**Comment by jasongao97** [comment]
Currently, links are appended after the text between parentheses without any special style.

```md
For more, you can read this discussion on the p5.js GitHub repository (https://github.com/processing/p5.js/issues/3877).
```

@shiffman Do you mean removing the whole link part? So it would become:

```md
For more, you can read this discussion on the p5.js GitHub repository.
```

**Comment by shiffman** [comment]
Yes, I think it this case I would rewrite the text to be 

```
For more, you can read the discussion in issue #3877 of the p5.js GitHub repository.
```

This way a web reader can click to go straight there and a book reader would likely just type `issue #3877 of the p5.js GitHub repository` into google or another search engine to find it. If I want a URL explicitly in the print book I'll add it with a separate "PDF" paragraph.

**Comment by shiffman** [comment]
This is resolved and all set but leaving open still as a reference for editing as there are many URLs that need to be adapted still.

**Comment by shiffman** [comment]
I can close this now that the copy edit has begun and will catch any that are not properly described or formatted.
