### ISSUE TITLE
Side by Side Figures + Captions

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#280]
This issue also follows up on an email discussion with @nheidelberger.  The goal is for any "side by side" figures to have only one caption and Figure #. (Is that correct @nheidelberger?).

For the illustrated figures @zee-em would you prefer to just combine them into one before uploading? This might be best but we can also handle it on our end. For the p5.js sketch figure (that will have a screenshot in the book) @jasongao97 I think we'll need to treat these as a special case and know that they get just one caption but appear as two separate images or canvases (print or online).

Does that make sense?

<img width="797" alt="Screen Shot 2023-04-04 at 10 20 23 AM" src="https://user-images.githubusercontent.com/191758/229822586-e60eed9e-73fd-4726-bbb1-410434b18b83.png">

<img width="817" alt="Screen Shot 2023-04-04 at 10 19 19 AM" src="https://user-images.githubusercontent.com/191758/229822602-9aefa01a-69f2-4430-b063-06ea791c70c7.png">

**Comment by nheidelberger** [comment]
Correct. Ideally one caption and figure number, with the caption using "left" and "right" designators or similar.

**Comment by jasongao97** [comment]
Hi! Dan. I've implemented it in this PR https://github.com/nature-of-code/fetch-notion/pull/4, and it's working in the recent build. The script merges all the captions to one (by adding a space between each), so they can be written together on any figure or be separated.

<img width="1063" alt="image" src="https://github.com/nature-of-code/noc-book-2023/assets/6762203/347e8700-6dab-4e25-968c-b40158e6afa3">

**Comment by shiffman** [comment]
Looks great, thank you @jasongao97!
