### ISSUE TITLE
Convert RGB images to grayscale

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#287]
Just filing an issue so that we remember to build this into the process. Based on our discussions I believe this should happen at the **build PDF** stage (so that RGB images can remain for the web / notion / etc versions).

Dan

**Comment by jasongao97** [comment]
Hi Dan! I've added this feature to the Magicbook project since it's much easier to implement and people may also benefit from it. Could you please review it?
https://github.com/magicbookproject/magicbook/pull/55

**Comment by shiffman** [comment]
Just noting that maybe we want to use `grey16` instead of `b-w`, black and white implies to me "thresholding" the image so that the values are only `255` or `0` but I'm not sure if this is actually how sharp treats it. We can of course try both.

**Comment by jasongao97** [comment]
I noticed that in the libvips (which sharp is powered of) documentation, `b-w` refers to 8-bit grayscale and `grey16` refers to 16-bit. Should we use 8bit or 16?

<img width="867" alt="image" src="https://user-images.githubusercontent.com/6762203/232954258-fccec7a4-81ae-42ed-aaa4-ce2ca76c68b6.png">

Source: https://www.libvips.org/API/current/libvips-colour.html#libvips-colour.description

**Comment by shiffman** [comment]
Hmmmm, I'm not sure! Why don't we start with 16-bit and we can change it later back to `b-w` if we want?
