### ISSUE TITLE
Misspelled word in introduction.html line 199

### ISSUE THREAD

**Issue by Sneezy123** [nature-of-code/noc-book-2#288]
The word `the` is spelled as `hte` in line 199 in the `content/introduction.html` [Here](https://github.com/nature-of-code/noc-book-2023/blob/main/content/00_7_introduction.html): ![Screenshot of the file with the misspelled word selected](https://i.imgur.com/o15oENA.jpeg)

**Comment by shiffman** [comment]
This has been updated in the notion source files for the book, will be fixed on the next build!

**Comment by shiffman** [comment]
All set!
