### ISSUE TITLE
Project Structure

### ISSUE THREAD

**Issue by jasongao97** [nature-of-code/noc-book-2#29]
Hi Dan! I'm thinking about two ways of arranging the project. We can either separate the three parts(node script for fetching data from notion to create local HTML files / magicbook pdf build / gatsby website build) into three node.js packages/modules or create one big project with all the scripts and logic. Which one do you prefer?

## Plan A: Separated three parts
```
├── content/
│   ├── html/
│   ├── images/
│   ├── package.json
│   └── scripts/
├── pdf/
│   ├── magicbook.json
│   └── package.json
└── website/
    ├── gatsby-browser.js
    ├── gatsby-config.js
    ├── gatsby-node.js
    ├── package.json
    └── src/
```

## Plan B: Combined
```
├── content/
├── magicbook/
│   ├── layouts
│   └── stylessheets/
├── scripts/
├── src/
│   ├── components/
│   ├── pages/
│   └── styles/
├── gatsby-browser.js
├── gatsby-config.js
├── gatsby-node.js
├── magicbook.json
└── package.json
```

**Comment by shiffman** [comment]
Just noting here that @jasongao97 and I met to discuss and we are leaning towards going with Plan B! @jasongao97 feel free to let me know if you think A is better as you begin to organize the repo!
