### ISSUE TITLE
Figure 8.5 Coastline Fractal

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#294]
I took parts of the two different Greeland coastlines and place them side by side. I think this works quite well and makes the point. However, one is not actually a zoomed in version of the other since I took two different parts of the coastline.

![coastline](https://github.com/nature-of-code/noc-book-2023/assets/191758/2ea19c98-971d-444e-83dc-7e7f16390bdc)

The next figure should then reveal that one is a zoom of the other, do you think if you zoom into this section and add additional detail beyond what google maps provides this could work?

![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/b51561ac-6c3a-4f7f-bb15-6cd52098a5df)

**Comment by shiffman** [comment]
Also, the second figure should include a simplified version of a scale bar for both A and B

<img width="489" alt="Screen Shot 2023-05-11 at 10 02 22 AM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/7402bb06-8260-4583-afe9-61756d7df131">

**Comment by zee-em** [comment]
updated in notion!

**Comment by shiffman** [comment]
These look terrific! I'm excited about this new direction. Is the scale accurate? We should include units on it if we can. I'm happy to do the legwork of figuring it out if you want to point me towards the parts of the coastline you used as a basis.

**Comment by shiffman** [comment]
re-assign to myself to check the scales

**Comment by shiffman** [comment]
Hi @zee-em I found the spot that you traced! My overlay is not perfect but is this enough to go on for adding a scale in kilometers that is relatively accurate? 

<img width="791" alt="greenland_2 copy" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/ccf1c156-7a4e-4390-a027-efaaad1ae9ee">

I can do the same for the other one or if you can extrapolate how zoomed in it is, then it can be scaled accordingly. 

I'm happy to do more here to help make this easier just want to make sure I'm on the right track!

**Comment by shiffman** [comment]
Also, I just noticed that the right side (B) of Figure 8.5 and 8.6 do not match. I assume the 8.6 is the correct one and can be copied into 8.5?

![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/f868569d-c4db-4957-a878-f11687e632a3)
![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/1d5fa110-c713-4fb5-ab2e-db4755a253e1)

**Comment by fturmel** [comment]
Also a reminder that the text between figures 8.5 and 8.6 has **[TBD]** placeholders still.

<img width="800" alt="Screenshot 2023-09-09 at 5 38 08 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/4009209/ec3e16d2-0d21-4fad-84e0-d853dcb2511e">

**Comment by zee-em** [comment]
replace top right b with bottom right b

**Comment by shiffman** [comment]
I will take the next step to try to mark it up with an approximate scale!

**Comment by shiffman** [comment]
Well, this was quite the approximation, but I used a ruler and calculator and this is what I came up with!

![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/6e7c9124-f2ac-43bf-a70b-8b9b69b984c3)

Zannah, I think the placement and design you had in yours is good. Hopefully you can use the length of these rectangles (which correspond to 300km on the left and 100km on the right to help). If you prefer them to be shorter we can make a 150km and a 50km one and cut them in half.

**Comment by zee-em** [comment]
uploaded to notion, pls review

**Comment by shiffman** [comment]
Amazing! It's just missing the layer with the gray "zoom" oval.


<img width="462" alt="Screen Shot 2023-11-10 at 4 36 39 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/5164bdbe-34e3-479f-9bbe-98808c47aced">

**Comment by zee-em** [comment]
updated :)

**Comment by shiffman** [comment]
Ah, 8.5 is great now, but the grey bubble arrow should not be included in 8.4! Once that is removed they are all set!!

**Comment by zee-em** [comment]
oh nooooo!

ok it's updated :)

**Comment by shiffman** [comment]
Yay! We got it now!
