### ISSUE TITLE
Figure 8.7 Factorial

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#295]
The arrows should come from `factorial()` and point towards (unpacking the function) `return() * factorial()`. Is it more clear if the arrow comes from the center of factorial? I'm not sure.

![factorial](https://github.com/nature-of-code/noc-book-2023/assets/191758/de5d55ad-c483-46e9-8ef3-7cbcefc40bc4)

**Comment by zee-em** [comment]
updated in notion!

**Comment by shiffman** [comment]
This is awesome! I have an idea of how we can adjust the "becomes ______" parts that can make this even more clearer. I marked it up below but I think it makes sense for us to work on this one together during our next meeting.

![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/80c569a3-afe2-47c3-b06b-0fcda7b2683c)

**Comment by zee-em** [comment]
New version, what do you think?


![figure_8-8](https://github.com/nature-of-code/noc-book-2023/assets/13405058/a0c42557-0a22-4658-9adf-2a3723544d0e)

**Comment by shiffman** [comment]
This is fantastic! I just have one correction, and one tiny nitpicky comment. The last "return 10" should be "return 1". Also, I would like to be consistent about the path of the arrows along the right side (the left ones are consistent). They should start from the center of each equation (the `*`) and end at the second number above. I want to see clearly that `3  * 2 = 6` for example. Here's a markup.

![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/7da81b7b-26e5-4bec-9d3c-ab4e4adf7f03)

**Comment by zee-em** [comment]
hold for now.

**Comment by shiffman** [comment]
(waiting for technical review)

**Comment by shiffman** [comment]
This has been reviewed and is good to go with the changes marked up in red above!

**Comment by zee-em** [comment]
updated and uploaded to notion for review.

**Comment by shiffman** [comment]
Perfect!
