### ISSUE TITLE
Match 8.20 and 8.21

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#296]
These should match each other int terms of stroke weight, dotted lines, dot size, etc.

 <img width="328" alt="Screen Shot 2023-05-11 at 10 23 23 AM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/5f1646f2-ac44-4a2d-acec-d59579da97e6"> 
8.20

<img width="269" alt="Screen Shot 2023-05-11 at 10 23 30 AM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/69ad367d-6037-4ca7-bd1f-b9fa17a1f49b">
8.21

**Comment by zee-em** [comment]
updated in notion!

**Comment by shiffman** [comment]
Beautiful!
