### ISSUE TITLE
Exercise 8.6 Layout

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#299]
The float for the illustration paired with 8.6 should be contained within the exercise box. (or is there a different design that would be better?) Shall I make the PNG transparent so that it doesn't feel like a separate image?

Notion:
<img width="759" alt="Screen Shot 2023-05-11 at 11 33 25 AM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/5f028108-8147-44fb-9248-2630f5dd6ec2">

Web:
![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/75944837-1696-4dda-a257-6b6597911eed)

(I haven't checked PDF yet)

**Comment by shiffman** [comment]
Here's what the PDF render looks like with markup corrections

![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/5b83dab4-8a2f-4253-aaea-ddc9f0901a5c)

**Comment by shiffman** [comment]
Noticing that the design works properly in Exercise 5.15, however, there is a great deal of extra space below that can be removed.

<img width="804" alt="Screen Shot 2023-05-11 at 2 43 42 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/b4f1f961-909c-429c-9a08-1dadc1199d28">

PDF could also be tightened (but is less expanded):

<img width="828" alt="Screen Shot 2023-05-11 at 2 45 33 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/a39d3cf0-2221-4c9c-9b21-40e9d3e3a178">

**Comment by shiffman** [comment]
Tagging in @tuantinghuang also in case you have any design ideas here.

**Comment by shiffman** [comment]
#432 will fix this, but I will leave this open until I have a chance to replace the image for 8.6!

**Comment by shiffman** [comment]
This is much better now! yay! @jasongao97 would it be possible to align the image vertically with the exercise header?

![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/14295699-2dae-482a-9453-2c14f10a9cfb)

**Comment by jasongao97** [comment]
Added! #476. @shiffman Can we close this?

**Comment by shiffman** [comment]
yes, just checked the PDF and they are looking great!
