### ISSUE TITLE
Figure 8.21 shorten height

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#300]
Let's shorten this figure, I think I would like it ideally to fit alongside the two paragraphs (not the list of rules).

![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/530b45c8-2ea9-4603-97d3-fa6f5ac05743)

**Comment by zee-em** [comment]
I shortened it! But I can't see in notion if it's enough. Can you test and let me know? Thanks!

**Comment by shiffman** [comment]
Yes, will test during the next build!

**Comment by shiffman** [comment]
Looking great on the web version! Will close after checking the PDF:

<img width="822" alt="Screen Shot 2023-05-31 at 3 18 30 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/40af844e-4c9a-4909-bc04-4379aeb128a9">

**Comment by shiffman** [comment]
Ah, thanks to @nheidelberger I noticed that this figure is a little incomplete in terms of properly illustrating all the rules. Here's a mark-up with corrections in pink.  It's important to be able to clearly see that A -> AB and B -> A

![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/909a44d7-c304-462b-9a4e-3a96e06a3596)

**Comment by zee-em** [comment]
updated and uploaded to notion, pls review there :)

**Comment by shiffman** [comment]
Fantastic!
