### ISSUE TITLE
table line breaks not rendering

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#302]
See this example for chapter 8.

Notion:
![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/f9d99d7d-efe8-4fb5-8cf6-faa85cc2ac85)

PDF:
<img width="770" alt="Screen Shot 2023-05-11 at 12 09 20 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/c22900cc-8a3d-4245-a8dd-39eec79ff0fa">

Web:
<img width="810" alt="Screen Shot 2023-05-11 at 12 09 43 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/7ec84cbe-ab23-4157-a56c-e7f29cb47374">

**Comment by jasongao97** [comment]
I suggest adding the line break with latex grammar. I've made the change, and they rendered fine on both format.

<img width="549" alt="image" src="https://github.com/nature-of-code/noc-book-2023/assets/6762203/0019bd32-89c6-4542-ad79-5768fc8def59">
