### ISSUE TITLE
table row height spacing with code

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#303]
This could probably be condensed with less padding around the code, especially the web version (PDF is maybe ok?)

Notion:
<img width="781" alt="Screen Shot 2023-05-11 at 12 14 38 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/226a1cf6-4e9a-45be-97e0-9bd97fdaab61">

Web:
<img width="843" alt="Screen Shot 2023-05-11 at 12 13 35 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/f84e8fd9-908f-4960-a2c8-bda85cb0e632">

PDF:
<img width="842" alt="Screen Shot 2023-05-11 at 12 13 44 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/74770fd0-bb0d-4a55-af66-42b5b5e7db82">

**Comment by jasongao97** [comment]
I've reduced the spacing in the last PR (#936). Would it be considered resolve?

![Capture-2024-04-22-100335](https://github.com/nature-of-code/noc-book-2/assets/6762203/45c12c1e-9535-42e7-a3c7-9e70a7b8014a)

**Comment by shiffman** [comment]
Yes, this looks great! We can close once merged!

**Comment by jasongao97** [comment]
Sounds great! It was already merged. Closing it.
