### ISSUE TITLE
Tables with embedded image/svg?

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#305]
In Chapter 9, the book has two tables to demonstrate the concepts of genotype vs. phenotype. This is from the 2012 version:

<img width="849" alt="Screen Shot 2023-05-12 at 10 53 33 AM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/531ba5de-3158-4282-addb-899c9bfd056c">

@jasongao97 Do you have any thoughts on how to handle this in Notion? I tried briefly to embed an image or SVG in the table, but didn't quickly find a solution.

<img width="775" alt="Screen Shot 2023-05-12 at 10 56 52 AM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/6568428b-5cd9-49f1-85e0-292b9041e288">

**Comment by jasongao97** [comment]
I got this weird idea of using TeX equations. It renders fine since we use `KaTeX` everywhere.

<img width="487" alt="image" src="https://github.com/nature-of-code/noc-book-2023/assets/6762203/eed21bd9-275a-48f5-9479-819612f586cd">

**Comment by shiffman** [comment]
Ah, this is great! One issue is that the square doesn't have an outline so that white one isn't visible, I could just change the values or adapt the text but I wonder if just embedding HTML right in there might work?

```html
    <div style="width: 20px; height: 20px; background-color: #7F7F7F; border: 1px solid black;"></div>
```

We could do something similar for the lines and/or use SVG?

**Comment by jasongao97** [comment]
Yes! This looks much better and should work. I've added the ability to keep HTML in text (https://github.com/nature-of-code/fetch-notion/pull/3) so they won't be converted to plain text. Noted I only enabled this feature in tables to avoid accidentally render some inline HTML in paragraph or code snippet if there is any.

**Comment by jasongao97** [comment]
Tested! This is working.

<img width="634" alt="image" src="https://github.com/nature-of-code/noc-book-2023/assets/6762203/f6e00595-2ab5-4906-86e1-113a73316828">

**Comment by shiffman** [comment]
Awesome, this is great! I've done the same for the horizontal lines. I'll close this issue on the next build of the site if all looks good.

<img width="785" alt="Screen Shot 2023-05-16 at 5 29 09 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/68a0a0cc-5e4c-4a7b-ac50-efe50bda9e69">

**Comment by shiffman** [comment]
@jasongao97 this is working great now! One question—what determines the column width? This is a small detail, but I'd love for these two tables that are so near each other in the text to line up.

![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/2cbec4f7-78f5-4884-a91e-6e211ca7dc71)

**Comment by shiffman** [comment]
These are looking great and we can track the column width in #368
