### ISSUE TITLE
Example 9.1 Comment Formatting

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#306]
The original NOC book usings bold/underline to emphasize where the steps of the genetic algorithm are in the code... this could probably use a custom design codesplit markup?

![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/99ac8b72-d268-4f76-b3eb-d7db3a5f8afb)

This is what the old mark-up looked like:

```javascript
  //{!4} <b><span style="font-size: 110%; text-decoration:underline;">Step 1: Initialize Population</b></span>
  for (let i = 0; i < population.length; i++) {
    population[i] = new DNA(target.length);
  }
}
```

**Comment by shiffman** [comment]
Current PDF render is doing something inverting the gray boxes. This needs to be fixed and we should think about a design treatment for the "header" comments (step 1, step 2, step 3)

**Comment by jasongao97** [comment]
Can we just make those step titles bold?

![consolidated](https://github.com/nature-of-code/noc-book-2023/assets/6762203/34883588-07cc-47dd-8bfa-4799c9b22d96)

**Comment by shiffman** [comment]
yes, this looks great!
