### ISSUE TITLE
noc-book-2 repo

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#31]
It looks like the build is pulling some images from the [NOC Book 2](https://github.com/nature-of-code/noc-book-2) repo. When we first started this repo it was a speculative exploration of working with Notion. Now that are moving forward in that direction I think it maybe makes sense to bring everything here and archive the `noc-book-2` repo. Or do we need two separate repos still?

The options are:

1. Archive `noc-book-2` and bring everything into `noc-notion`
2. Archive `noc-notion` and integrate all of these build scripts into `noc-book-2`
3. Keep both repos?

I think my preference is to go with (1) but I'll want to go through all of the issues there and resolve them or bring them over. What do you think @jasongao97?

**Comment by jasongao97** [comment]
Agree! I think the first option makes sense. I didn't include any images in this repo since I haven't got a full plan for handling the images. I'm still thinking about downloading images during imports, so they can be all managed on Notion. Or do you prefer manually uploading images here?

**Comment by shiffman** [comment]
Good question, I'm good with adding and updating images to notion directly while working on the book but we should probably bring them over during the import process that way if notion ever goes down or I decide I no longer want to work with it everything that is needed for the book and website would still be in this repo?

**Comment by jasongao97** [comment]
Yes totally! I'll update the script to do that.

**Comment by shiffman** [comment]
This is now the repo!
