### ISSUE TITLE
Revised Figure 0.8

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#314]
@nheidelberger had some good feedback about Figure I.9, it's in notion but opening an issue to track here. @zee-em we can discuss at our next meeting.

<img width="790" alt="Screen Shot 2023-05-31 at 4 45 07 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/2150bc42-fe0b-4886-9d8e-fb10a6af1f04">

Possible update to left:

![IMG_3220](https://github.com/nature-of-code/noc-book-2023/assets/191758/c9eaf7d4-a20b-4b28-863a-e9e942c0d1ae)

**Comment by shiffman** [comment]
Continuing this thread. The latest version of the illustration is as follows:

![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/81c99791-0d76-4fe7-b88b-f8f109924de7)

Here is my draft caption:

"Figure 0.8: Comparing neighboring Perlin noise values in one (left) and two (right) dimensions. The cells are shaded according to their Perlin noise value."

Does the shading and my explanation add something here or is it confusing and we should leave it out? @nheidelberger and @wellcaffeinated would love your thoughts!

If we do keep the shading, @zee-em I think we need to adjust it slightly so that it more accurately depicts perlin noise, I can explain in our meeting. But the TLDR is that every cell's shading should be very similar to their neighbor (they are a bit too different/random right now). And the cells included in in the neighborhood should also have variable shading.

**Comment by nheidelberger** [comment]
I like the idea of the shading.

**Comment by zee-em** [comment]
![Figure_I-11](https://github.com/nature-of-code/noc-book-2023/assets/13405058/d83b58e9-1d9f-4088-92a6-c185d726ddc6)

**Comment by zee-em** [comment]
neighbors should be more similar, clean up figure at right.

**Comment by zee-em** [comment]
adjust grayscale, less texture, keep same colors together

**Comment by zee-em** [comment]
updated pls review.
![Figure_I-11 4](https://github.com/nature-of-code/noc-book-2023/assets/13405058/0abb0f6f-2861-44a6-a04d-d47609142d95)

**Comment by shiffman** [comment]
Yes, this is all set!

**Comment by zee-em** [comment]
uploaded :)

**Comment by shiffman** [comment]
Yay! Closing!
