### ISSUE TITLE
Two and Three Body Problem Figure for Chapter 2

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#320]
Starting the discussion of a new figure for chapter 2 about the two and three body problem. I think showing two sample path scenarios side by side could work well.

![IMG_3244](https://github.com/nature-of-code/noc-book-2023/assets/191758/80a1939e-8c0e-4f93-907f-a406eb6a8041)

Two Body
![Orbit5](https://github.com/nature-of-code/noc-book-2023/assets/191758/dce5bfc8-7e98-4f41-9917-a0b72e8a05fa)

Three Body
![Three-body_Problem_Animation_with_COM](https://github.com/nature-of-code/noc-book-2023/assets/191758/cb770d77-7b2c-4c1f-813e-eb748c3bbcd1)

Draft Text
<img width="804" alt="Screen Shot 2023-06-04 at 12 23 19 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/c6948263-9874-4a24-96e7-7f8f79adc73b">

**Comment by shiffman** [comment]
Related to this Exercise 2.12 refers to a paper about various paths, should we include a redrawing of a few of these with that exercise?

<img width="753" alt="Screen Shot 2023-06-04 at 12 32 07 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/3a93eb8c-af36-4414-bbe8-750718b78dbe">

![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/8b20ba18-7eff-4d70-bbde-67deeed88eab)

**Comment by zee-em** [comment]
here's a first draft

![3body](https://github.com/nature-of-code/noc-book-2023/assets/13405058/5721ea88-26a0-406c-9c6e-6ba37642ce39)

**Comment by shiffman** [comment]
I think this looks great! Let's go ahead and add to Notion!

**Comment by zee-em** [comment]
uploaded. closing.
