### ISSUE TITLE
Figure 3.7: v1 vs v2 (change to subscripts, maybe full width)

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#322]
v1 and v2 should be v_1 and v_2 (w/ 1 and 2 as subscripts). Also the half-width here is causing some layout issues. We may want to change to a full width. Let's wait on this until chapter 3 is more complete.

**Comment by shiffman** [comment]
I think this will work as half-width in the design (the top just needs to be cropped) but I'm open to changing it to full-width if you prefer @zee-em. At a minimum, the numbers in v1 and v2 need to be subscript (see caption).

![Screen Shot 2023-08-25 at 1 53 46 PM](https://github.com/nature-of-code/noc-book-2023/assets/191758/34a48869-a2e5-4e4f-924d-4c2c84b52181)

**Comment by zee-em** [comment]
Kept half-width as is-- changed subscripts, uploaded to notion. Please check the layout. Thanks!

**Comment by shiffman** [comment]
Ah, sorry, looking at this again with the subscripts it's noticeable that there are no arrows over the top of v1 and v2, could we add that in? This will make it more consistent (see Figure 3.5) Thank you @zee-em!

**Comment by zee-em** [comment]
new new version
![Figure_3-7v2](https://github.com/nature-of-code/noc-book-2023/assets/13405058/77ac4b82-10eb-471e-88c3-1781764cfcfa)

**Comment by shiffman** [comment]
Perfect!

**Comment by shiffman** [comment]
(Actually I'll leave this one open just to check the layout but the figure is good to go, re-assigning to me for now.)

**Comment by shiffman** [comment]
looking good in the PDF!
