### ISSUE TITLE
Print PDF build should no longer include URLs in parentheses

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#324]
The text is now being written to describe how to find a link rather than typing out a long URL. This is also perhaps an impetus to have 2 PDF builds:

1. print PDF (no hyperlinks or color)
2. digital PDF (full color, w/ hyperlinks)

2 is lower priority right now as it can always be worked on after the print PDF is locked in.

@jasongao97 let me know what you think

**Comment by jasongao97** [comment]
Sounds great! This should be easy to do. Just to be sure, will the digital PDF have the same text as the print version? Or you'd like to write them separately?

**Comment by shiffman** [comment]
I definitely don't want to introduce a 3rd option so yes, let's go with the same text as print but actively adding the link. But the focus right now is the print version so we can also figure this out later!

**Comment by shiffman** [comment]
Noticing this is a duplicate of #279 so closing this one.
