### ISSUE TITLE
Figure 3.11 Pendulum, add "tension"

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#326]
Let's add the "tension" force to the diagram. It could say "tension force" but maybe it'll fit  better if it just says "tension" and "gravity".

![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/99534ca6-b02d-4d27-a59f-1ddac09bc5ea)

**Comment by nheidelberger** [comment]
@shiffman , you might consider adding Fp to the diagram as well, so we can see it more clearly from the get-go, before zeroing in on the right triangle in the next figure. But no problem if you'd rather defer that to Figure 3.12.

![244706552-99534ca6-b02d-4d27-a59f-1ddac09bc5ea](https://github.com/nature-of-code/noc-book-2023/assets/77461054/a573060b-6392-4c80-94fd-8e798599e0da)

**Comment by shiffman** [comment]
I think I'd like to defer it b/c I'm being slightly imprecise about the lengths of the vectors in this diagram and around the "net force" vs. Fp language so I prefer to keep this a traditional diagram with gravity and tension and then unpack the net force in the next diagram. I might keep this issue open after replacing the illustration with my changes just for one last consideration during technical review.

**Comment by zee-em** [comment]
here's a version with tension. I made the arm of the pendulum gray so you can see the tension arrow, but it's easy to change it back to black of that works better. 

![Figure_3-11v2](https://github.com/nature-of-code/noc-book-2023/assets/13405058/4e8eaf79-1981-4cc5-8b80-b1c510834f22)

**Comment by shiffman** [comment]
Looks great!

**Comment by shiffman** [comment]
@zee-em Thanks to excellent feedback from @dipamsen and @wellcaffeinated, the Pendulum section has been rewritten for clarity and scientific accuracy. The above figure is the same, however, the others have changed. I've drawn mockups of them and will include below!

Figure 3.15: Revised illustration by @zee-em in https://github.com/nature-of-code/noc-book-2023/issues/326#issuecomment-1629490875

Figure 3.16: On the left, the pendulum is drawn rotated so that the arm is the y-axis. The right shows $F_g$ zoomed in and divided into components $F_{gx}$ and $F_{gy}$.
<img width="715" alt="Screen Shot 2023-09-04 at 10 32 15 AM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/37b81f89-a5e3-4d2f-8cd5-a5969bb37afa">

Figure 3.17: $F_{gx}$ is now labeled $F_p$, the net force in the direction of motion.
![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/210ccece-d35c-462b-a59f-4bed5e17503c)

**Comment by zee-em** [comment]
![FIgure_3-17](https://github.com/nature-of-code/noc-book-2023/assets/13405058/83dafd9a-1b79-410f-a427-03abc1d4d420)
![Figure_3-16](https://github.com/nature-of-code/noc-book-2023/assets/13405058/61815d96-452c-4ff9-ada3-21891a66091a)

**Comment by zee-em** [comment]
![Figure_3-16 2](https://github.com/nature-of-code/noc-book-2023/assets/13405058/a00e55e6-6e25-45f8-b340-6718a49f6b5a)
![FIgure_3-17 2](https://github.com/nature-of-code/noc-book-2023/assets/13405058/e22c97d8-6dfd-4fc3-b2a5-abafd9d4fdff)

**Comment by zee-em** [comment]
Fix dots

**Comment by zee-em** [comment]
updated and uploaded!
