### ISSUE TITLE
Proposal to add a unified callout block for adding class names

### ISSUE THREAD

**Issue by jasongao97** [nature-of-code/noc-book-2#327]
<img width="600" alt="image" src="https://github.com/nature-of-code/noc-book-2023/assets/6762203/112e9d25-25ea-4587-94ed-69bc0f07d35c">

We currently use `code` mark inside captions to add custom styles like floating images. It seems to be causing a few issues when there are actual code snippets included in the captions.

What I was considering is introducing a new type of callout block for adding class names, something like a tag icon (🏷️) perhaps? This could create a more unified system for our callout blocks to cover the existing 'pdf/web only' blocks, and any other styles we might need in the future.

<img width="745" alt="image" src="https://github.com/nature-of-code/noc-book-2023/assets/6762203/88fe3353-1eba-40db-bcff-5fb8c774e457">

@shiffman How do you think about it?

**Comment by shiffman** [comment]
@jasongao97 this works for me! I wonder if we should apply the `code` syntax to things like `web-only` so that they look distinct from regular text?

Tagging @nheidelberger in as an FYI. Let us know if you have any thoughts as well!

**Comment by jasongao97** [comment]
Sure! In this way, I believe a block with multiple class names should look like this?

<img width="726" alt="image" src="https://github.com/nature-of-code/noc-book-2023/assets/6762203/2285c407-a2c0-4572-b6ab-79263302d34e">

**Comment by shiffman** [comment]
This can be closed as it's now implemented and in use in Notion, thank you @jasongao97!
