### ISSUE TITLE
Figure 4.3 change "attraction" to "repulsion"

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#330]
The example demonstrates a repeller rather than an attractor so it makes sense to reverse the direction of the arrows in this figure:

![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/a8bd96bb-fbcc-4a14-b5f8-2d7970e43323)

Also, the book build system is taking care of this, but if we are re-uploading it these two figures can be combined into one image:

<img width="802" alt="Screen Shot 2023-06-16 at 12 43 08 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/aadf6482-7e7e-432d-ad40-cb73588e1d21">

**Comment by zee-em** [comment]
new version, combined!


![Figure-4_4+3 2](https://github.com/nature-of-code/noc-book-2023/assets/13405058/75da7b5e-c247-4679-9808-0e8f8fe7ee07)

**Comment by shiffman** [comment]
Looks great!!

**Comment by zee-em** [comment]
Uploaded to Notion and GDrive

**Comment by shiffman** [comment]
Fantabulous!
