### ISSUE TITLE
Soft Body Character Illustrations

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#334]
Write a short section based on https://thecodingtrain.com/challenges/177-soft-body-character or just reference the video and example?

Should this replace the "force directed graph" example or be in addition to it?

**Comment by shiffman** [comment]
I've written a new section for Chapter 6 about a soft body character example. I've added two additional illustrations for this chapter:

![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/c917e9ef-8aac-49cf-965a-420fefffab5d)

For this second one, it should visually highlight the addition of the "internal springs". . maybe the outer ones are light gray?

![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/ed91ecb2-df88-4633-bc51-0be778a7ba23)

**Comment by zee-em** [comment]
how do these look? 


![newCh6](https://github.com/nature-of-code/noc-book-2023/assets/13405058/d117b322-12af-43b4-86fb-128feb8538e6)



![newCh62](https://github.com/nature-of-code/noc-book-2023/assets/13405058/a44d8ba3-d2e1-403c-9563-3c5fad6c29a3)

**Comment by shiffman** [comment]
Perfect!

**Comment by zee-em** [comment]
I've uploaded to Notion. If you provide Figure numbers or a working file name I can save them in GDrive. Thanks!

**Comment by shiffman** [comment]
I renumbered the figures and they are 6.15 and 6.16 (though at some point I'll have to do a full pass over the full book and they may change again.) You can also name them `soft-body-1` and `soft-body-2` They look great!
