### ISSUE TITLE
PDF Math formula font size

### ISSUE THREAD

**Issue by tuantinghuang** [nature-of-code/noc-book-2#347]
The font size for math formula is too big, inline and sometime in explanation box.

<img width="787" alt="Screenshot 2023-07-23 at 4 08 35 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/90000947/da740270-b886-4665-a8b2-4f364a3fbb43">

**Comment by jasongao97** [comment]
#485 should solve this issue.

**Noted that KaTeX math is rendered in 1.21x size, so in our case, 9.68pt.**

**Comment by shiffman** [comment]
Looking great! Closing, thank you @jasongao97!
