### ISSUE TITLE
CSS for code in tables

### ISSUE THREAD

**Issue by tuantinghuang** [nature-of-code/noc-book-2#350]
CSS treatment for code in tables

InDesign Mockup:
<img width="614" alt="Screenshot 2023-07-23 at 4 27 32 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/90000947/476948db-5c42-4c34-bfdf-9eb7c608f572">

**Comment by shiffman** [comment]
There is also another table in chapter 4 which is not rendering properly.

<img width="655" alt="Screen Shot 2023-08-02 at 9 23 25 AM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/ec597f29-ef9a-440b-84bf-486e78b1ffc9">
<img width="805" alt="Screen Shot 2023-08-02 at 9 23 46 AM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/fcb3ebaa-cbf5-4cc8-8b3d-10bfd730f380">

**Comment by shiffman** [comment]
@jasongao97 this is such a tiny thing but would be nice to fix, the left column should have additional line breaks so that the identical lines of code match each other horizontally. The line breaks are in Notion but not rendering to the PDF in the same way.

![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/aaedad6c-214b-4b17-b3b8-cb95a9262756)

**Comment by shiffman** [comment]
(The applyForce() and applyRepeller() table is perfect now.)

**Comment by jasongao97** [comment]
It's working on my side. Could you please run the latest build again?

<img width="934" alt="image" src="https://github.com/nature-of-code/noc-book-2023/assets/6762203/61f6ccd3-37b3-48df-a09b-4fb36b86e366">

Another problem is these code are too wide and overflow the page width. Is it possible to narrow the code? (e.g. adding line break in the for loop line)

**Comment by shiffman** [comment]
Ah, let's try it like this!

```javascript
  let length = particles.length - 1
  for (let i = length; i >= 0; i--) {
    let particles = particles[i];
    particle.run();
    if (particle.isDead()) {
      particles.splice(i, 1);
    }
  }
  ```

<img width="1133" alt="Screen Shot 2023-10-09 at 9 31 35 AM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/0607ad3f-c3ee-45ea-b9b7-eb16a28b2d5a">

**Comment by shiffman** [comment]
Hi @jasongao97, looks like this is still off by one line? I tried to add a line break in #547 but it didn't take. Also, should we make these rounded corners as well? cc @tuantinghuang 

![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/c76e037f-5f83-43e8-82b3-e1b0baccced2)

**Comment by shiffman** [comment]
Checked the latest build and this issue is resolved, however @tuantinghuang I think it might still be worth looking at whether we want to "round" these corners as well as bottom align the grey box.

**Comment by shiffman** [comment]
Notes from our meeting:

* slight rounded corner for the boxes
* align bottom of the boxes (adding an extra line break if needed)
* additional padding inside the boxes around the margins

**Comment by jasongao97** [comment]
Hi! I applied the styles. Which one would you prefer for the rounded corder? @tuantinghuang @shiffman 

| same as other code blocks: 8pt | smaller: 4pt |
| - | - |
| <img width="697" alt="image" src="https://github.com/nature-of-code/noc-book-2023/assets/6762203/1a31693a-687c-4d89-a899-ee338bd985e6"> | <img width="698" alt="image" src="https://github.com/nature-of-code/noc-book-2023/assets/6762203/2037a5b5-5750-46e4-ac36-9b1c8b8d1813"> |

**Comment by shiffman** [comment]
These look great! I think I prefer 4pt, but defer to you and @tuantinghuang!

**Comment by tuantinghuang** [comment]
Thank you @jasongao97 ! I'd prefer 4pt too!

**Comment by shiffman** [comment]
Just checked the latest PDF, looks great!
