### ISSUE TITLE
CSS treatment for number and bullet lists

### ISSUE THREAD

**Issue by tuantinghuang** [nature-of-code/noc-book-2#351]
Update CSS treatment for number and bullet lists.

InDesign mockup:
Number list
<img width="616" alt="Screenshot 2023-07-23 at 4 29 35 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/90000947/a88ee550-f93a-4d89-ac4a-f0631f023c98">

Bullet points
<img width="615" alt="Screenshot 2023-07-23 at 4 29 43 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/90000947/3842c8f7-156d-4127-9f44-aeaff8d99e60">

**Comment by shiffman** [comment]
Also, noticed that the bold text in the chapter 2 bulleted list looks "too bold" and distorted in the PDF render. Maybe this should be a separate issue but I'll note it here for now.

![Screen Shot 2023-08-02 at 7 55 25 AM](https://github.com/nature-of-code/noc-book-2023/assets/191758/5f4c057b-bbef-43fb-a009-dfb6e04638c8)

**Comment by shiffman** [comment]
See #364 for the font-weight / bold question.

**Comment by shiffman** [comment]
This is all set!
