### ISSUE TITLE
CSS update for exercise fill-in blanks

### ISSUE THREAD

**Issue by tuantinghuang** [nature-of-code/noc-book-2#352]
Update CSS for fill-in blanks in exercises:
<img width="636" alt="Screenshot 2023-07-23 at 4 31 53 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/90000947/036cc7f2-569c-4691-9eb6-38f04ab4034f">

**Comment by shiffman** [comment]
I merged #361 but I will leave this open to evaluate and compare the PDF render for exercise 2.2 to the image above from @tuantinghuang. We can then fine-tune as needed.

**Comment by shiffman** [comment]
I updated the text and rebuilt the PDF, here's what it looks like now:

![Screen Shot 2023-08-02 at 8 24 16 AM](https://github.com/nature-of-code/noc-book-2023/assets/191758/6a50ff03-8ff0-4b41-80d3-602c0d06404f)

I think it would look better with increasing the vertical padding (the original design appears to have more). It might also be nice to add a bit more horizontal space per letter maybe this can be accomplished by increasing the font size for these "blank" characters?

**Comment by shiffman** [comment]
This can be closed with #379  after double checking a new PDF render.

**Comment by tuantinghuang** [comment]
@shiffman Can this one be closed, as the monospaced font is updated already?

**Comment by shiffman** [comment]
Yes, let's close this! Just need to remember to finish filling in all the exercises too!
