### ISSUE TITLE
PDF big blanks between page breaks

### ISSUE THREAD

**Issue by tuantinghuang** [nature-of-code/noc-book-2#354]
There are multiple big blanks between pages throughout the pdf. It may be helpful to document where the big blank happens and look into [CSS paged media](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_paged_media), and see how we can solve it by adjusting the code.

For example, the example screenshot box is bound to the code beneath, causing a blank in the previous page. Maybe we can separate these two elements so the screenshot box can move upward one page.
<img width="488" alt="Screenshot 2023-07-23 at 4 57 39 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/90000947/58bf2bdc-20ca-4378-9d62-665bc81178aa">

**Comment by shiffman** [comment]
Related to this (maybe should be a separate issue but compiling into one for now), I noticed that some code comments are split across two pages and this shouldn't be allowed. Here's an example from chapter 2:

page 87:
![Screen Shot 2023-08-25 at 12 38 55 PM](https://github.com/nature-of-code/noc-book-2023/assets/191758/db0d48bb-5fa7-4ab6-8161-1b5f638cceaf) 

page 88:
![Screen Shot 2023-08-25 at 12 39 03 PM](https://github.com/nature-of-code/noc-book-2023/assets/191758/954ce478-5e6c-44ec-b1af-8b4180bb9161)

(Right after Example 2.1 for reference)

**Comment by shiffman** [comment]
this is now being tracked separate in more specific issues
