### ISSUE TITLE
Figure 6.1 r1 and r2 -> subscripts r_1 and r_2

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#356]
Change "r1" and "r2" to $r_1$ and $r_2$ (subscripts)

![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/0974f44d-0145-4e5d-975d-8c1a914d24fd)

**Comment by zee-em** [comment]
Updated and added to Notion for review.

**Comment by shiffman** [comment]
We should try to place them a little bit more consistently in terms of proximity to the radius itself. I think they could all be a little closer to the line, but especially the r2 on the far right. Otherwise, it's all set!

![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/11017d0e-4ce3-49a1-8929-40913d89ab3d)

**Comment by zee-em** [comment]
How's this?

![Figure_6-1 2](https://github.com/nature-of-code/noc-book-2023/assets/13405058/27b3f404-4a8f-4cd0-a4de-fd5db75c8dbb)

**Comment by shiffman** [comment]
perfect but the 1s and 2s subscripts at the bottom `r_1 + r_2` floated up, oops!

**Comment by zee-em** [comment]
Ugh, layer error.  Ok, trying again. 
![Figure_6-1](https://github.com/nature-of-code/noc-book-2023/assets/13405058/3b4c3b42-df29-4ed9-b8f0-a6e0c31dd901)

**Comment by shiffman** [comment]
We got it!! 🎉
