### ISSUE TITLE
Figure 6.8 add "constraint" label

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#357]
I'm not sure if the "arrow" makes sense but it would be great to add a "constraint" label that is clearly pointing out the line between the two anchors.

![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/e43f2ddc-83ba-47e7-8252-08571a71c7fb)

**Comment by zee-em** [comment]
Is constraint capitalized? The other labels aren't (and in the text the capital C seems to represent the class?) so I'd say not for consistency.
How about the label along the line, like this?  
![FIgure_6-8](https://github.com/nature-of-code/noc-book-2023/assets/13405058/2d4a1506-5257-45ee-8b70-98c3c31638aa)

**Comment by shiffman** [comment]
I think this is perfect! Tagging @nheidelberger just in case since he had the original comment.

**Comment by nheidelberger** [comment]
Yeah, looks great. Thanks!

**Comment by zee-em** [comment]
add to notion

**Comment by zee-em** [comment]
uploaded.

**Comment by zee-em** [comment]
closing!
