### ISSUE TITLE
pseudo code design in website and PDF

### ISSUE THREAD

**Issue by tuantinghuang** [nature-of-code/noc-book-2#363]
In need of design treatment for pseudocode (the pink boxes in the screenshot) , or make it into a callout box, to separate them more from the copy. Both website and pdf!

In Notion, Chapter 6:
<img width="788" alt="Screenshot 2023-07-28 at 3 12 19 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/90000947/99adcbfb-3ec1-4625-8b68-fc62655554ca">

**Comment by tuantinghuang** [comment]
For the pseudo code, I went into Notion and changed the _SETUP_ to `setup()`, and this is the rendered pdf of it. @shiffman Do you think it should be bolded or have some extra treatment, or does it look ok as is?

![Screenshot 2023-08-22 at 5 42 26 PM](https://github.com/nature-of-code/noc-book-2023/assets/90000947/bb32fca6-9905-41e2-a009-9c46643b8f48)

**Comment by shiffman** [comment]
Looks great! Closing this and now tracking in #397
