### ISSUE TITLE
table column widths

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#368]
Right now the column widths for tables are set automatically (presumably related to the width of the table content). I'd like to be able to set these manually as needed. (I'm focusing on the PDF right now where this is more specifically needed, though I'm happy for this to apply to the website as well.)

Here's an example in Chapter 1 where I'd like to do this so that the "Variable Names" columns line up.

![Screen Shot 2023-08-02 at 8 12 10 AM](https://github.com/nature-of-code/noc-book-2023/assets/191758/ba8e00f3-8696-416e-9d94-e6d653615900)

In Chapter 2, this would allow me to have more space for the "Function" column.

![Screen Shot 2023-08-02 at 8 15 21 AM](https://github.com/nature-of-code/noc-book-2023/assets/191758/48074230-a9fb-41c6-ba11-eee345b78cc4)

@jasongao97 One idea is to use markup along the lines of `[100px]` in the column headers. @jasongao97 maybe you have a better idea?

<img width="761" alt="Screen Shot 2023-08-02 at 8 20 04 AM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/82b9127a-7bb4-41bb-af95-2325e4f87522">

**Comment by shiffman** [comment]
Also, while we're at it code blocks in tables should not be indented as it looks strange:

![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/51c741e5-12a3-4b67-a8d2-72975294822e)

**Comment by shiffman** [comment]
@jasongao97 can you remind me here what we settled on and I can try it in a few places? (Feel free to add to Notion yourself too.)

**Comment by jasongao97** [comment]
I added those here in Chapter 1:

<img width="744" alt="image" src="https://github.com/nature-of-code/noc-book-2023/assets/6762203/fd3e6dc9-b36d-4696-b598-52f29e03057f">

---

They are working well in the latest build:

<img width="699" alt="image" src="https://github.com/nature-of-code/noc-book-2023/assets/6762203/2ca30100-92bb-49d2-a29b-5f6e522147a1">

**Comment by shiffman** [comment]
This is amazing! Works great. I will leave this issue open as a reminder for adjusting any other tables.

**Comment by shiffman** [comment]
(re-assigned to myself but @jasongao97 feel free to adjust any tables as you see fit.)

**Comment by shiffman** [comment]
This can be closed now and we can adjust table widths as we review the layout. Thank you @jasongao97!
