### ISSUE TITLE
Icons for exercises and ecosystem projects

### ISSUE THREAD

**Issue by tuantinghuang** [nature-of-code/noc-book-2#370]
Design or find icon for exercises and ecosystem projects, can also potentially be applied to the website.

as seen in pdf mockup:
<img width="600" alt="Screenshot 2023-08-04 at 12 29 00 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/90000947/8238bcf2-8ebf-4f0b-9919-318ca3ce4fb1">

Notion:
<img width="600" alt="Screenshot 2023-08-04 at 12 10 39 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/90000947/251ff898-ab73-4848-9f3b-3c43440f5da0">

Website:
<img width="600" alt="Screenshot 2023-08-04 at 12 25 39 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/90000947/fec18f19-9610-4f06-8195-417a5e148c65">
<img width="600" alt="Screenshot 2023-08-04 at 12 25 24 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/90000947/27dbc48b-583a-4090-8d84-29cc3ee8660f">

**Comment by tuantinghuang** [comment]
I found two icons for both of these on [openmoji.org](https://openmoji.org/) that might be suitable!

<img width="952" alt="Screenshot 2023-08-09 at 8 54 52 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/90000947/cd20449f-11d5-47aa-bad1-4408fda62710">

<img width="1103" alt="Screenshot 2023-08-09 at 8 58 33 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/90000947/89c88651-2e11-422c-9d4a-f333e10f2a27">

**Comment by shiffman** [comment]
These look great! Assigning to @jasongao97 to add the implementation of rendering the emojis in the PDF. You can also consider adding them to the web version but that is lower priority.

**Comment by tuantinghuang** [comment]
@jasongao97 Here are the links to the icons on [openmoji](openmoji.org)!

[parrot](https://openmoji.org/library/emoji-1F99C/#variant=black)
[crayon](https://openmoji.org/library/emoji-1F58D/#variant=black)

**Comment by jasongao97** [comment]
I noticed that `note` block has a similar design compare to the ecosystem projects. Do we need an icon for this type as well?

In Notion:
![image](https://github.com/nature-of-code/noc-book-2023/assets/6762203/dccacbfc-9691-4c74-b924-4122f7df142a)


In PDF:
![image](https://github.com/nature-of-code/noc-book-2023/assets/6762203/ff83307e-8fcc-45c9-9189-f57fc9a54bd9)

**Comment by shiffman** [comment]
Let's try something and see how it looks! A starting point would be the "book/paper" category, but I'm always game for something a bit more unusual or specific to nature of code related! What do you think @tuantinghuang?

<img width="856" alt="Screen Shot 2023-08-13 at 10 33 33 AM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/d4c40f02-b38b-41ee-8736-8ee39885438d">
https://openmoji.org/library/#group=objects%2Fbook-paper

**Comment by tuantinghuang** [comment]
I found three icons that might suit the book! [magnifying glass](https://openmoji.org/library/emoji-1F50E/#variant=black), [label](https://openmoji.org/library/emoji-1F3F7/#variant=black), and [ruler](https://openmoji.org/library/emoji-1F4D0/#variant=black), and below is what they look like in a mockup. What do you think of these? @shiffman 


<img width="500" alt="Screenshot 2023-08-16 at 2 08 04 AM" src="https://github.com/nature-of-code/noc-book-2023/assets/90000947/29225705-145a-4848-91f8-c41879036bb5">

zoom in -
<img width="500" alt="Screenshot 2023-08-16 at 2 08 13 AM" src="https://github.com/nature-of-code/noc-book-2023/assets/90000947/285921b9-951b-4734-9d5b-2519621d3df6">

**Comment by shiffman** [comment]
Oh, I like these! The ruler is perfect for this one, but I think the magnifying glass might be apply better across the board. Let's go with that for now!

**Comment by shiffman** [comment]
I think this can be closed now!(and linking to #381)
