### ISSUE TITLE
Credit OpenMoji

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#381]
* PDF preface
* GitHub README
* website depending on use there

See: #370 https://openmoji.org/faq/

**Comment by shiffman** [comment]
added to the acknowledgements!

> A special thanks also to the OpenMoji (CC BY-SA 4.0) project for providing a delightful and comprehensive set of emojis, used throughout this book for various elements.

Will leave open as a reminder to make sure credits are on the website as well.

**Comment by shiffman** [comment]
Hey @b-g! Just wanted to tag you and let you know that i'm using OpenMoji in a few places in the new nature of code book!
If you have any requests or notes on how to properly credit the project please let me know!


<img width="847" alt="Screen Shot 2023-10-08 at 11 06 03 AM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/50442c4a-513f-458c-87d3-939140622d7d">

**Comment by b-g** [comment]
Hi @shiffman, that's great! Happy that the OpenMojis prove to be useful! The official attribution suggestion is to put the sentence below somewhere unobtrusive e.g. about section, acknowledge ... but definitely not all over the place, mentioning us once is fine.

> All emojis designed by [OpenMoji](https://openmoji.org/) – the open-source emoji and icon project. License: [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/#)

Best of luck with new nature of code book!! Looking forward for it!

**Comment by shiffman** [comment]
This can be closed now that the credit is offered in the acknowledgments. @melissa-rodriguez depending on how we do with the "additional credits" page it could also be included there.
