### ISSUE TITLE
Illustration quality Notion -> PDF

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#383]
@jasongao97 I'm noticing when I look at the latest PDF render that the illustrations appear slightly pixelated. Here is one example:

<img width="854" alt="Screen Shot 2023-08-09 at 9 43 11 AM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/d2fb285f-fbe8-4875-8eb3-ee29fdb70169">

I checked Notion and the source image appears to be high resolution / quality (see below). I'm not sure if this is just related to how I'm looking at the PDF on my screen (I haven't tried to print it), but is it possible there is some degradation / compression of the image that happens during the build process?

![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/2a2d8851-2916-46a7-9ed1-c9076d539de8)

**Comment by jasongao97** [comment]
Turns out it was the css grayscale filter that degraded the image quality.

```css
img {
  filter: grayscale(100);
}
```

**Comment by shiffman** [comment]
Thank you so much for finding this!!
