### ISSUE TITLE
When i build the pdf , i got an error.

### ISSUE THREAD

**Issue by xiatian12345** [nature-of-code/noc-book-2#384]
➜  noc-book-2023 git:(main) node --version
v18.16.1
➜  noc-book-2023 git:(main) npm install
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-server-dom-webpack@0.0.0-experimental-c8b778b7f-20220825
npm WARN Found: react@18.2.0
npm WARN node_modules/react
npm WARN   react@"^18.2.0" from the root project
npm WARN   10 more (@gatsbyjs/reach-router, gatsby, gatsby-link, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"0.0.0-experimental-c8b778b7f-20220825" from react-server-dom-webpack@0.0.0-experimental-c8b778b7f-20220825
npm WARN node_modules/react-server-dom-webpack
npm WARN   react-server-dom-webpack@"0.0.0-experimental-c8b778b7f-20220825" from gatsby@4.25.7
npm WARN   node_modules/gatsby
npm WARN
npm WARN Conflicting peer dependency: react@0.0.0-experimental-c8b778b7f-20220825
npm WARN node_modules/react
npm WARN   peer react@"0.0.0-experimental-c8b778b7f-20220825" from react-server-dom-webpack@0.0.0-experimental-c8b778b7f-20220825
npm WARN   node_modules/react-server-dom-webpack
npm WARN     react-server-dom-webpack@"0.0.0-experimental-c8b778b7f-20220825" from gatsby@4.25.7
npm WARN     node_modules/gatsby
npm WARN deprecated string-similarity@1.2.2: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated async-cache@1.1.0: No longer maintained. Use [lru-cache](http://npm.im/lru-cache) version 7.6 or higher, and provide an asynchronous `fetchMethod` option.
npm WARN deprecated express-graphql@0.12.0: This package is no longer maintained. We recommend using `graphql-http` instead. Please consult the migration document https://github.com/graphql/graphql-http#migrating-express-grpahql.
npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
(##################) ⠙ reify:date-fns: http fetch GET 200 https://cdn.npmmirror.com/packages/date-fns/2.30.0/date-fns-2
(##################) ⠙ reify:date-fns: http fetch GET 200 https://cdn.npmmirror.com/packages/date-fns/2.30.0/date-fns-2
(##################) ⠙ reify:date-fns: http fetch GET 200 https://cdn.npmmirror.com/packages/date-fns/2.30.0/date-fns-2
npm ERR! code 1
npm ERR! path /Users/xiatian/Work/gits/noc-book-2023/node_modules/magicbook/node_modules/sharp
npm ERR! command failed
npm ERR! command sh -c (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
npm ERR! sharp: Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.14.2/libvips-8.14.2-darwin-x64.tar.br
npm ERR! sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies
npm ERR! sharp: Installation error: read ETIMEDOUT

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xiatian/.npm/_logs/2023-08-09T22_25_30_182Z-debug-0.log
➜  noc-book-2023 git:(main)
➜  noc-book-2023 git:(main) npm install sharp
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-server-dom-webpack@0.0.0-experimental-c8b778b7f-20220825
npm WARN Found: react@18.2.0
npm WARN node_modules/react
npm WARN   peer react@"15.x || 16.x || 17.x || 18.x" from @gatsbyjs/reach-router@1.3.9
npm WARN   node_modules/@gatsbyjs/reach-router
npm WARN     @gatsbyjs/reach-router@"^1.3.9" from gatsby@4.25.7
npm WARN     node_modules/gatsby
npm WARN     3 more (gatsby-link, gatsby-react-router-scroll, gatsby-script)
npm WARN   10 more (gatsby, gatsby-link, gatsby-plugin-image, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"0.0.0-experimental-c8b778b7f-20220825" from react-server-dom-webpack@0.0.0-experimental-c8b778b7f-20220825
npm WARN node_modules/react-server-dom-webpack
npm WARN   react-server-dom-webpack@"0.0.0-experimental-c8b778b7f-20220825" from gatsby@4.25.7
npm WARN   node_modules/gatsby
npm WARN
npm WARN Conflicting peer dependency: react@0.0.0-experimental-c8b778b7f-20220825
npm WARN node_modules/react
npm WARN   peer react@"0.0.0-experimental-c8b778b7f-20220825" from react-server-dom-webpack@0.0.0-experimental-c8b778b7f-20220825
npm WARN   node_modules/react-server-dom-webpack
npm WARN     react-server-dom-webpack@"0.0.0-experimental-c8b778b7f-20220825" from gatsby@4.25.7
npm WARN     node_modules/gatsby
npm WARN deprecated string-similarity@1.2.2: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated async-cache@1.1.0: No longer maintained. Use [lru-cache](http://npm.im/lru-cache) version 7.6 or higher, and provide an asynchronous `fetchMethod` option.
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated express-graphql@0.12.0: This package is no longer maintained. We recommend using `graphql-http` instead. Please consult the migration document https://github.com/graphql/graphql-http#migrating-express-grpahql.
(##################) ⠏ reify:date-fns: timing reifyNode:node_modules/@parcel/transformer-js Completed in 13683ms
(##################) ⠏ reify:date-fns: timing reifyNode:node_modules/@parcel/transformer-js Completed in 13683ms
(##################) ⠏ reify:date-fns: timing reifyNode:node_modules/@parcel/transformer-js Completed in 13683ms

added 1822 packages in 2m

297 packages are looking for funding
  run `npm fund` for details
➜  noc-book-2023 git:(main) ✗
➜  noc-book-2023 git:(main) ✗ npm run build:pdf

> noc2@1.0.0 build:pdf
> magicbook build

Config file detected: magicbook.json
/Users/xiatian/Work/gits/noc-book-2023/node_modules/prince/prince-api.js:292
            throw new Error("Prince#" + method + ": cannot resolve binary \"" +
            ^

Error: Prince#execute: cannot resolve binary "prince" to a filesystem path
    at Prince._execute (/Users/xiatian/Work/gits/noc-book-2023/node_modules/prince/prince-api.js:292:19)
    at Prince.execute (/Users/xiatian/Work/gits/noc-book-2023/node_modules/prince/prince-api.js:359:17)
    at Pumpify.<anonymous> (/Users/xiatian/Work/gits/noc-book-2023/node_modules/magicbook/src/plugins/pdf.js:55:10)
    at Pumpify.emit (node:events:525:35)
    at finishMaybe (/Users/xiatian/Work/gits/noc-book-2023/node_modules/readable-stream/lib/_stream_writable.js:630:14)
    at afterWrite (/Users/xiatian/Work/gits/noc-book-2023/node_modules/readable-stream/lib/_stream_writable.js:492:3)
    at onwrite (/Users/xiatian/Work/gits/noc-book-2023/node_modules/readable-stream/lib/_stream_writable.js:483:7)
    at WritableState.onwrite (/Users/xiatian/Work/gits/noc-book-2023/node_modules/readable-stream/lib/_stream_writable.js:180:5)
    at Object.onceWrapper (node:events:627:28)
    at Pumpify.emit (node:events:513:28)

Node.js v18.16.1
➜  noc-book-2023 git:(main) ✗

**Comment by xiatian12345** [comment]
closed

**Comment by knandersen** [comment]
I also encountered this issue and fixed it by installing `prince` manually through `brew install prince` (https://github.com/magicbookproject/magicbook/issues/15)
