### ISSUE TITLE
wolfram rules error in Figure 7.11

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#398]
The binary numbers should read:

```
000 001 010 011 100 101 110 111
```

![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/9cb528b9-59a5-435a-a36a-6d3fee1a131f)

**Comment by shiffman** [comment]
Oh! Thanks to another comment from @nheidelberger I've realized that we actually need to write the binary digits with the highest value `111` on the left and lowest `000` on the right, so it should be the following:

```
111 110 101 100 011 010 001 000
```

![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/3a322470-5fcc-48c1-82e9-eab4e48c98e4)

**Comment by zee-em** [comment]
Hey, I see we are reversing the order of the numbers on the right at top-- does that mean the 0s and 1s at bottom right are also changing, or do they stay the same?

**Comment by shiffman** [comment]
They stay the same (they are symmetrical so it doesn't matter in this case!)

**Comment by shiffman** [comment]
Oh, but the curved arrow will have to move to the new spot for `010` too!

![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/f7401957-6ee1-4316-9c07-d9eacd674b6e)

**Comment by zee-em** [comment]
how's this?
![Figure_7-11NEW](https://github.com/nature-of-code/noc-book-2023/assets/13405058/1da4d774-4f5c-4a8f-8c1a-1f72888c7920)

**Comment by shiffman** [comment]
perfect!

**Comment by zee-em** [comment]
Uploaded to notion and drive as 7.11NEW (the numbering is off again, from Notion to this issue, so just saving it as such to avoid any overwrites :)

**Comment by shiffman** [comment]
Yay! So satisfying to close these issues out!
