### ISSUE TITLE
Add generation labels in Figure 7.12

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#399]
@nheidelberger suggested added labels along the left edge of the figure. 

* Feel free to skip the ":" if it looks better without?
* Feel free to use a some kind of vertical ellipses (...) between gen 2 and gen 8 or number all of them?

Mockup:

![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/e162d793-fab7-4f6c-af47-dde8d00a233f)

**Comment by zee-em** [comment]
how does this look?
![Figure_7-13](https://github.com/nature-of-code/noc-book-2023/assets/13405058/f76e746e-eb9a-4b17-957e-2ed035d58263)

**Comment by shiffman** [comment]
perfect!

**Comment by zee-em** [comment]
Uploaded to Notion and GDrive 👍

**Comment by shiffman** [comment]
@zee-em what do you think about combining this into grid where the zeros appear in black over the white squares and the 1s appear in white over the black squares? Does that makes this easier or harder to read? Also, we could go wider if we wanted to. The pink square is what we're showing now, we could even just go from 0-7 maybe?

![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/3c37c50c-512a-49ae-a892-69d9ca6cc8fa)

**Comment by zee-em** [comment]
test-- does this work?
![Figure_7-12NEW](https://github.com/nature-of-code/noc-book-2023/assets/13405058/1aa7041e-dd5a-472e-9487-008c435f68ba)

**Comment by zee-em** [comment]
updated and uploaded to notion, pls review.

**Comment by shiffman** [comment]
yes, this one turned out so great in the end!
