### ISSUE TITLE
Reverse order of binary numbers from left to right, Figure 7.8

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#400]
The binary digits in this figure should start from 111 and count down to 000.

```
111 110 101 100 011 010 001 000
```

The outcomes along the bottom can stay the same (they are symmetrical).

![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/1db01513-acc2-450e-bf6a-c940f099f324)

@nheidelberger please feel free to double check this!

**Comment by zee-em** [comment]
updated, uploaded to Notion and in GDrive.

**Comment by shiffman** [comment]
It doesn't have to be exact but the arrows should come from the middle of the 3 digits. `110` and `101` look particularly askew to the left.

![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/0983d4e7-59a5-467e-af89-9fbe004c602d)

**Comment by zee-em** [comment]
better?
![Figure_7-9 2](https://github.com/nature-of-code/noc-book-2023/assets/13405058/8a87caf1-6b6b-4738-b9e7-18a5d0b5913b)

**Comment by shiffman** [comment]
yes, beautiful!

**Comment by zee-em** [comment]
uploaded to Notion and Drive. FYI on the files it's called 7.8NEW because some numbering changed since we updated, and I didn't want to overwrite a different figure.

**Comment by shiffman** [comment]
Got it!
