### ISSUE TITLE
Figure 8.19 and 8.20 line, translate, push, pop

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#404]
@nheidelberger had some good suggestions about these figures. For 8.19, it might be nice to rotate the `(0,0)` to emphasize that the full "scene" is rotated.

![temp-figure8-19](https://github.com/nature-of-code/noc-book-2023/assets/191758/a9f9e099-bed2-4243-bcad-ccc8ce433919)

I did the above in photoshop but assume @zee-em you'd prefer to adjust the original illustration.

Then for 8.20, a full width illustration that covers the next three steps would be more clear. Here's @nheidelberger's mockup:

![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/70197437-4181-4889-af6d-9acc5ac9589e)

What do you think @zee-em? One issue @nheidelberger is that `push()` is missing from the illustrations, but maybe that's ok.

**Comment by nheidelberger** [comment]
I don't think I'm bothered the lack of push() in the illustrations, since the text is already talking about push() being left out of the code.

**Comment by zee-em** [comment]
how do these look? will upload when approved. 
![Figure_8-19 2](https://github.com/nature-of-code/noc-book-2023/assets/13405058/cf4fa36e-4f2d-449d-870a-1b5eb37e8149)


![FIgure_8-20](https://github.com/nature-of-code/noc-book-2023/assets/13405058/3f50efa4-8ead-4364-9a1c-f62477932722)

**Comment by shiffman** [comment]
Almost there! The relative position of `(0,0)` should stay consistent. On the top figure, far right, it's shifted up after rotation.

![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/9096032b-6e13-4421-85de-c7081753a2b7) ![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/e624c27f-54bb-4179-8497-1206b1688beb)

For the bottom figure, left should re-position (0,0) to match. Center `(0,0)` text should be back to normal orientation (that's what pop() does!). And then even though it looks weird, I've realized that the correct orientation of the text is actually: 

![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/35bee793-8ede-4e14-b206-9de701f0624f)

**Comment by shiffman** [comment]
If you want me to do all of them for tracing I can!

**Comment by shiffman** [comment]
Top 3:

![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/9e92a4f2-d3bc-41bb-b0a9-05e2d744f052) ![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/04a3d971-e0fa-42a8-b5b5-3f2b591e1781) ![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/d226710a-bdf4-4da0-b026-ef31fc023ae0)

**Comment by shiffman** [comment]
Bottom three. (I didn't include the thetas/angles those can stay the same. And the dots too.)

![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/dd2a1223-5ae0-4d49-87c8-13f7e77bcebd) ![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/01869798-097c-4786-8ce4-8b55a0859a78)  ![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/3135f25f-9265-4f0d-ad83-9ddfe23e97c4)

**Comment by zee-em** [comment]
how are these?
![Figure_8-19 3](https://github.com/nature-of-code/noc-book-2023/assets/13405058/824b4037-a55d-4281-89a0-4eb407cb0fe8)
![FIgure_8-20 2](https://github.com/nature-of-code/noc-book-2023/assets/13405058/e8035c1f-1648-41ca-9492-fa8758f54ae7)

**Comment by shiffman** [comment]
Close!  Only the very bottom right one is off. The `(0,0)` should be aligned at a right angle to the dotted line. Also, it's missing the dot at the top (just to be consistent.)

The bottom image looks like it has different line weights and dot weights, is that true or am I just seeing that b/c of how it's rendering on github?

![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/26e8e5a2-b5c4-461b-8112-c37656b31356)

**Comment by zee-em** [comment]
Yes, the line weights were different! I use approx the same brush pixel size but it's all pressure sensitive--looks like I wasn't pressing hard enough when I did the second figure for the update :)
And I see what you meant about the angle! 

Let me know how this looks:
![Figure_8-19 4](https://github.com/nature-of-code/noc-book-2023/assets/13405058/0afbcce2-6af0-47c1-8145-6b2af329270c)
![FIgure_8-20R 3](https://github.com/nature-of-code/noc-book-2023/assets/13405058/65d18a45-7fca-483f-8121-a2eba99c3019)



Here's the drawn angle in case it looks weird. Rotated from the left center edge of the text bounding box (which is visible in software). 

![FIgure_8-20R](https://github.com/nature-of-code/noc-book-2023/assets/13405058/36e64db1-d40d-4130-b7af-db7433930ea2)

**Comment by shiffman** [comment]
Yes, this is great now and can go into Notion!

**Comment by zee-em** [comment]
Uploaded to Notion and GDrive.

**Comment by shiffman** [comment]
yay!
