### ISSUE TITLE
Chapter 0 introductory paragraph

### ISSUE THREAD

**Issue by sidwellr** [nature-of-code/noc-book-2#407]
If you are changing "Introduction" to "Chapter 0. Randomness" (which seems a logical thing to do), you should rewrite its first paragraph. The title change changes the main purpose of the chapter from "reacquaint your mind with computational thinking" to introducing some useful tools for coding simulations: random numbers, random distributions, and noise. The first paragraph should explain this (and perhaps say why it is numbered "0").

**Comment by shiffman** [comment]
How is this new version? (I still feel it's important to emphasize the "just getting back into it" aspect of the chapter)

> Here we are: the beginning. If it’s been a while since you’ve programmed in JavaScript (or done any math, for that matter), this chapter will reacquaint your mind with computational thinking. To start your coding of nature journey, I’ll introduce you to some foundational tools for programming simulations: random numbers, random distributions, and noise. Think of this as the first (zero!) element of the array that makes up this book—a refresher and a gateway to the possibilities that lie ahead.

FYI @nheidelberger

**Comment by sidwellr** [comment]
I like it!
