### ISSUE TITLE
Clarification on Newton's third law

### ISSUE THREAD

**Issue by dipamsen** [nature-of-code/noc-book-2#409]
CHP 2 Forces - Modelling a Force - Gravitational Attraction

> In truth, just as Earth pulls the apple toward it due to a gravitational force, the apple pulls Earth as well. Earth is just so freaking massive that it overwhelms all the other gravity interactions. In fact, every object with mass exerts a gravitational force on every other object (this is Newton’s third law). The formula for calculating the strengths of these forces is depicted in Figure 2.6.

In the above paragraph:

> In fact, every object with mass exerts a gravitational force on every other object (this is Newton’s third law).

This statement may be a bit misleading as the fact that "every object with mass exerts a gravitational force on every other object " is not a consequence of / explained by Newton's third law. 

What is explained by Newton's third law is the fact that the **magnitude of gravitational forces among two bodies is the same.** 

The parenthesis can be moved to the first statement to be more accurate:
> In truth, just as Earth pulls the apple toward it due to a gravitational force, the apple pulls Earth as well. (...)

**Comment by shiffman** [comment]
Ah, this is great feedback! I've made the change and the paragraph now reads:

> In truth, just as Earth pulls the apple toward it due to a gravitational force, the apple pulls Earth as well (this is Newton’s third law). Earth is just so freaking massive that it overwhelms all the other gravity interactions. In fact, every object with mass exerts a gravitational force on every other object. The formula for calculating the strengths of these forces is depicted in Figure 2.6.

It might be overkill, but tagging in @nheidelberger and @wellcaffeinated since this is a substantive change (albeit very small.) I'm closing the issue but let me know if I should re-open or make any other changes!
