### ISSUE TITLE
Chp2 typos

### ISSUE THREAD

**Issue by dipamsen** [nature-of-code/noc-book-2#410]
## Typos
- [x] Newton's First Law restatement ("constant if _i's_ in a state")
- [x] Force Accumulation ("Net Force") - "which I now *to* confess to having simplified"
- [x] Creating Forces - "Mover" class code comments - "edges ofthe canvas"
- [x] Exercise 2.10 - "drag force can **be** also be perpendicular."
- [x] Modelling a Force - Gravitational Attraction - "that can be used to **to** scale"

**Comment by shiffman** [comment]
All corrected in Notion! They won't be updated on the website until I run the next build, but this can safely be closed. Thank you @dipamsen!
