### ISSUE TITLE
Angular quantities

### ISSUE THREAD

**Issue by dipamsen** [nature-of-code/noc-book-2#413]
CHP 3 Oscillation - Angular Motion
> You can apply exactly the same logic to a rotating object:
>
> angular velocity=angular velocity+angular acceleration
> angle=angle+angular velocity
>
> In fact, these angular motion formulas are simpler than their linear motion equivalents because an angle is a scalar quantity (a single number), not a vector!

This is a very nitpicky comment, but it _may_ be worth mentioning (as a note) that usually, these quantities (angular position, angular velocity, angular acceleration) are vector quantities, however as we are only dealing with 2D, we can just use scalars. (in this case these vectors always point perpendicular to the plane, so their directions is insignificant, however it becomes important in case we are working with 3D.)

**Comment by shiffman** [comment]
I recently added an extra paragraph to mention "delta time" and I just further expanded it to:

> (Note: In most contexts, these formulas include a multiplication by the change in time, referred to as “delta-time”.  I’m assuming a delta-time of 1 that corresponds to one frame of animation in p5.js. Also, the angular values are only treated as scalars because I am focusing on two-dimensional space, where there is one axis of rotation!)

I'll close this once it's approved by @wellcaffeinated and @nheidelberger in Notion.
