### ISSUE TITLE
monospace text in caption

### ISSUE THREAD

**Issue by dipamsen** [nature-of-code/noc-book-2#415]
Monospace text inside figure captions do not show up in the web output.

Notion:
![image](https://github.com/nature-of-code/noc-book-2023/assets/59444569/c16d8868-6103-41ec-a3f7-345eeeb3b333)

Web:
![image](https://github.com/nature-of-code/noc-book-2023/assets/59444569/304d45ca-a65d-446a-b8e7-d1be5e02a0bb)

**Comment by shiffman** [comment]
Noting this issue is also present in the PDF.

![Screen Shot 2023-08-27 at 1 53 14 PM](https://github.com/nature-of-code/noc-book-2023/assets/191758/9b2d3afc-dfd6-4d7b-bf69-5c72b31409e5)

**Comment by dipamsen** [comment]
From the docs,

> Images are downloaded and referenced relatively with path as images/{chapter}/{chapter}_{index}.{extension}. For caption, annotated code part are turned to class and the rest will be the content of figcaption and images’ alternative text.

This is most likely the issue. This has to be changed so that only the code block at the start of the caption is used as the class names.

**Comment by shiffman** [comment]
Ah yes, that makes sense! Thanks for finding this! Let me know if you want to work on a fix, otherwise I'll assign to @jasongao97! I think it would be part of this repo? https://github.com/nature-of-code/fetch-notion

**Comment by dipamsen** [comment]
@shiffman I just PR'ed here: https://github.com/nature-of-code/fetch-notion/pull/6

**Comment by jasongao97** [comment]
Closing this since the fix is merged. Thank you!
