### ISSUE TITLE
Chapter 3 - Typos

### ISSUE THREAD

**Issue by dipamsen** [nature-of-code/noc-book-2#416]
- [x] Angular Motion 
    > "[...] velocity—the rate at which an object’s position changes **over time**— [...] angular velocity—that rate at which an object’s angle changes. By extension, angular acceleration describes changes in an object’s angular velocity." 
    
   Add "over time" to the description of angular velocity for symmetry (and maybe also to that of angular acceleration?)

- [x] Oscillations with Angular velocity: "In fact, the period is the **the** number of frames"

- [x] Trigonometry and Forces: The Pendulum: "If you lift the pendulum up from its resting state and then release it, however, it starts to swing back and forth, tracing the shape of an arc." The text can maybe be changed to "lift the pendulum up **at an angle** ..." ?
(Currently it sounds like lifting the Bob straight up)
- [x] Spring Forces - "All I need to do now is set the magnitude of the vector used **used** for"

**Comment by shiffman** [comment]
Thank you!
