### ISSUE TITLE
Code example in Chp4 

### ISSUE THREAD

**Issue by dipamsen** [nature-of-code/noc-book-2#417]
Chp 4 Particle Systems - A Single Particle

the first code example has a class with a "Particle" function, which should be renamed to "constructor".

![image](https://github.com/nature-of-code/noc-book-2023/assets/59444569/bdfdda2d-4be2-435b-878d-699cc4c8a18b)

**Comment by dipamsen** [comment]
Similarly, in the code snippet after Example 4.3:
![image](https://github.com/nature-of-code/noc-book-2023/assets/59444569/cddf745c-9eec-4c06-8317-373a7483c8c1)

**Comment by shiffman** [comment]
Fixed!
