### ISSUE TITLE
Remove cross line in code

### ISSUE THREAD

**Issue by adebiasi** [nature-of-code/noc-book-2#418]
In the Chapter 1. , secion Vector Addiction there is:
_...And so I must dig into the p5.Vector object and pull out the x and y components using object-oriented dot syntax:_
~~circle(position, 48);~~
~~circle(position.x, position.y, 48);~~

It shoud be:

_...And so I must dig into the p5.Vector object and pull out the x and y components using object-oriented dot syntax:_
~~circle(position, 48);~~
circle(position.x, position.y, 48);

**Comment by shiffman** [comment]
Ah, good catch! I think this markup in notion should fix it. Will wait to close until the next build.

![Screen Shot 2023-08-28 at 8 53 00 AM](https://github.com/nature-of-code/noc-book-2023/assets/191758/ec38df62-ae80-4d1d-bedb-e9fecfac1962)

**Comment by shiffman** [comment]
Fixed!

<img width="810" alt="Screen Shot 2023-08-28 at 2 12 17 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/d039b265-dc8a-4488-9ce5-f04edce6e815">
