### ISSUE TITLE
Chapter 10 typos

### ISSUE THREAD

**Issue by netalondon** [nature-of-code/noc-book-2#419]
Hey :)
I found some typos while reading the 10th chapter, 
this only ranges from the reinforcement learning part and forwards:

1. "Let’s being with the inputs" - should be begin instead of being
2.  "This is a quite the intriguing question" - no need for a before quite
3. "Maybe you don’t want to put your thumb on the scale in terms of what aspects of the game are important so this approach 			 attempts to feed everything about the game into the model." - it might be better to put a comma after "important", otherwise the sentence is quite convoluted.
4. "the important points data points" - no need for the first "points"
5.  "there are only a discrete set of choices" - should be is instead of are
6. "I’d have to go back steps 1 and 2" - missing "to" after "back"
7. "for every moment of game play" - gameplay should be one word
8. "Instead of this going down this road" - no need for the first "this"
9. pregressively refines - should be "progressively"
10. "the neural network computations will instead run the “Central Processing Unit” " - missing "on" after "run"
11. "you may noticed that I’ve slipped in another new feature" - should be notice instead of noticed
12. "brain will evaluate to true and is assigned directly to this.brain" - not as critical, but here you switch from future tense to present tense
13. "That’s it! Everything else from the original example example" - example is written twice
14. "perhaps a small cup soothing tea" - missing "of" after "cup"
15. "Here is the final version of the example with new Creature constructor" - missing "a" before "new"?
16. "only is immediate surroundings" - should be its instead of is
18. "Instead of fixed lifespan cycle for the population" - missing "a" before "fixed"
19. " I’ll manage this an eat() method of the Creature class" - I assume you meant "**in** an eat() method"
20. "for the purpose of htis book" - misspelled "this"

**Comment by shiffman** [comment]
Thank you! Hope you enjoyed reading the section!

These have all been corrected and will appear shortly when I rebuild the website.
