### ISSUE TITLE
broken reference

### ISSUE THREAD

**Issue by adebiasi** [nature-of-code/noc-book-2#422]
Chapter 2:
_...See the [Metropop Denim project by Clayton Cubitt and Tom Carden](http://processing.org/exhibition/works/metropop/) for an example._

http://processing.org/exhibition/works/metropop/ doesn't work.

**Comment by shiffman** [comment]
Yes, thank you! I'm going to close this since it's an active comment / issue in the Notion doc and will be resolved there. I'm also looking for ideas of what to reference here!
