### ISSUE TITLE
Empty comment blocks

### ISSUE THREAD

**Issue by dipamsen** [nature-of-code/noc-book-2#426]
Ch5 Autonomous Agents - Algorithmic Efficiency

Is the comment "do something" intended to be highlighted with the closing brace?

![image](https://github.com/nature-of-code/noc-book-2023/assets/59444569/77c42f6d-7876-4e57-bdb0-e05cb00b1aea)

It would be nicer it it were on its own block with no code in it, though I'm not sure if that's possible.

**Comment by shiffman** [comment]
This is being adjusted based on #434!

**Comment by shiffman** [comment]
(will leave it open as a reminder to look at this particular comment and close when completed)

**Comment by fturmel** [comment]
Looks better now, maybe this issue can be closed?

<img width="803" alt="Screenshot 2023-09-29 at 8 54 26 AM" src="https://github.com/nature-of-code/noc-book-2023/assets/4009209/17907afd-b309-4123-89dd-37c62e54b709">

**Comment by shiffman** [comment]
Closing, let's discuss in #434
