### ISSUE TITLE
Reference suggestion

### ISSUE THREAD

**Issue by adebiasi** [nature-of-code/noc-book-2#428]
Only a small suggestion:

Perhaps the paper [The Evolution of Evolvability](https://www.richarddawkins.net/wp-content/uploads/sites/41/2014/06/Evolution-of-Evolvability.pdf) by Richard Dawkins deserves a mention in the section `Interactive Selection`.

**Comment by shiffman** [comment]
Thank you for this! I'll consider in the "further reading" section.

**Comment by shiffman** [comment]
The further reading section will be on the website only now so I will tackle this later.

**Comment by shiffman** [comment]
This is now added to the Notion page which will be built onto the website soon.
