### ISSUE TITLE
"inline" codesplit

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#434]
The current markup is:

```javascript
//{inline} text about a section of code that is blank
```

Let's change it to:

```javascript
/* text about a section of code that is blank */
```

Also, these should be left aligned with the body of the code (at the comment indentation).

**Comment by jasongao97** [comment]
![image](https://github.com/nature-of-code/noc-book-2023/assets/6762203/86476854-b70b-4621-96b0-8058bf0cba5f)

**Comment by shiffman** [comment]
Ah, I was imagining that "All the other stuff from before" would be inside of its own gray box and in Gotham instead of Inconsolata, but I think this might actually be better and more clear! Any thoughts @tuantinghuang?

**Comment by jasongao97** [comment]
Gotcha! @shiffman Is this what you had in mind?

![a](https://github.com/nature-of-code/noc-book-2023/assets/6762203/bed54fbd-8448-42cc-88f3-ff16222c165e)

Which one do you like better?

**Comment by shiffman** [comment]
Hmmm, I'm not sure! I think maybe the block/multi-line `/* comment here */` format better? Also, we could go with the gray box style but I wonder if it be right aligned with the code indentation? Or center aligned?

![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/f979a02c-341c-4e0e-bd78-40782e1934ab)

I don't feel super strongly about this, whatever is easiest is maybe best. Any thoughts @tuantinghuang?

**Comment by tuantinghuang** [comment]
<img width="1512" alt="Screenshot 2023-09-19 at 6 14 45 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/90000947/18493e18-d468-44ce-be63-8a5d83e5e317">
If this is helpful, I made a mockup showing 4 different versions of laying out this line of text, and I think I like 1 or 3 more!

**Comment by shiffman** [comment]
@jasongao97 I forgot where we landed with this. I think there is a final design, but hsould the markup be `//{inline} comment` or `/* comment */`? I think I prefer to latter.

**Comment by jasongao97** [comment]
> @jasongao97 I forgot where we landed with this. I think there is a final design, but hsould the markup be `//{inline} comment` or `/* comment */`? I think I prefer to latter.

Sure! `/* comment */` would work. As for the render: current implementation is 1 in Tuan's comment. Would you like to change it to 2 or anything else?

**Comment by shiffman** [comment]
I think 1 or 2 are my top choices, I can't decide between them (don't feel super strongly about this if you think one is better @jasongao97 go for it!) @tuantinghuang, what do you think?

**Comment by jasongao97** [comment]
Great, I'll leave it as 1 for now since it doesn't require any implementation🤪.

**Comment by shiffman** [comment]
Sounds good! If @tuantinghuang approves, this can be closed!

**Comment by shiffman** [comment]
Completed!
