### ISSUE TITLE
math block does not renders for caption of side-by-side figures

### ISSUE THREAD

**Issue by dipamsen** [nature-of-code/noc-book-2#438]
Notion: 
![image](https://github.com/nature-of-code/noc-book-2023/assets/59444569/6585405e-65b0-4c78-8efd-e419f38c01c1)

Web: 
![image](https://github.com/nature-of-code/noc-book-2023/assets/59444569/dfb52def-c2fb-4d27-a5aa-4b9effda00be)

**Comment by shiffman** [comment]
Ah, great find! This one won't matter in the end b/c the figure is a placeholder and will be drawn as a "wide" image, but still would be good to fix!

**Comment by jasongao97** [comment]
Thank you! This is fixed now.

![image](https://github.com/nature-of-code/noc-book-2023/assets/6762203/77c32915-b61a-478e-a488-4b308a9cf871)

**Comment by shiffman** [comment]
Thank you @jasongao97!!!
