### ISSUE TITLE
Check writing style during the fetch process and log the result to PR

### ISSUE THREAD

**Issue by jasongao97** [nature-of-code/noc-book-2#443]
An idea of having the fetch-notion script check writing styles such as:

- bold+italic
- title case or sentence case for heading
- ...

the script may log the result to the PR so these rules can be checked automatically.

**Comment by shiffman** [comment]
Also, noting that I'm finding some inconsistent use of tabs vs. spaces which I can't see in Notion so maybe this is something we check for and log?

See: https://github.com/nature-of-code/noc-book-2023/pull/461/files

**Comment by shiffman** [comment]
I believe @fturmel's pull request now takes care of the code checks. I'm open to having more checks but the book will be undergoing a professional copy edit so this may not be so necessary at this stage.

**Comment by shiffman** [comment]
This is a great idea but as the project is wrapping up (in its current incarnation) I think I will close. We can always re-open if we want to pursue ideas like this in the future!
