### ISSUE TITLE
Figure 6.15 cluster connections

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#444]
I noticed I don't have an open issue regarding this illustration. I'm lazily just pasting a screenshot of the discussion on Notion and will come back to this later.

<img width="1169" alt="Screen Shot 2023-09-05 at 10 27 38 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/c2c2ab32-f0a1-4805-933f-7d7da756ad02">

**Comment by zee-em** [comment]
Hi, I think I understand this, but just to make sure, can you draw the pentagon and send me an image? 
Also, weighing in on the discussion-- as I look at this cold (without reading this section of the chapter) and try to figure out what to draw, I find the step by step listing much more readable than just having the result and a table.  I noticed we used grayscale to show lines drawn in previous steps-- I guess for a complete single figure it would be all black lines?

**Comment by shiffman** [comment]
Here's what the pentagon would look like:

![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/e3ad65ad-7fcb-4951-a4b5-0dcded466049)

What if we kept all the stages in the figure and just used the table in the text? It could look something like:

![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/fb9f03e4-c611-4784-9d9c-ba6f22408d11)

**Comment by shiffman** [comment]
0 | connected to | 1
-- | -- | --
0 | connected to | 2
0 | connected to | 3
0 | connected to | 4
1 | connected to | 2
1 | connected to | 3
1 | connected to | 4
2 | connected to | 3
2 | connected to | 4
3 | connected to | 4

**Comment by zee-em** [comment]
updated, pls review
![Figure_6-14](https://github.com/nature-of-code/noc-book-2023/assets/13405058/47fb8fdf-3c51-47d5-baa3-3768855ec1a2)

**Comment by zee-em** [comment]
add list of connection under each step

**Comment by zee-em** [comment]
updated, please review:

![Figure_6-14 2](https://github.com/nature-of-code/noc-book-2023/assets/13405058/7804c839-d858-4522-8a08-7339ba828139)

**Comment by shiffman** [comment]
Perfect!

**Comment by zee-em** [comment]
uploaded to notion :)

**Comment by shiffman** [comment]
All set!
