### ISSUE TITLE
Chapter 0 - code snippet comment should say "methods" instead of "functions"

### ISSUE THREAD

**Issue by fturmel** [nature-of-code/noc-book-2#448]
It seems like you're previously making the point that functions on classes/objects are called methods, but the comment doesn't reflect this.

<img width="795" alt="image" src="https://github.com/nature-of-code/noc-book-2023/assets/4009209/45a81a67-cd76-4017-b410-0d1eb0584a5e">

**Comment by shiffman** [comment]
Fixed! About to run the build now!
