### ISSUE TITLE
Figure 8.1 typo (mountain)

### ISSUE THREAD

**Issue by fturmel** [nature-of-code/noc-book-2#449]
<img width="790" alt="image" src="https://github.com/nature-of-code/noc-book-2023/assets/4009209/8a9c34c2-3f1d-4d31-832b-d3b9bf670834">

**Comment by shiffman** [comment]
Ah, thank you for catching this! This will be fixed when @zee-em does her next round of revised illustrations.

**Comment by zee-em** [comment]
updated & uploaded to notion + google drive.

**Comment by shiffman** [comment]
Looks great thank you @zee-em!!
