### ISSUE TITLE
Figure 10.19 caption typo

### ISSUE THREAD

**Issue by fturmel** [nature-of-code/noc-book-2#450]
<img width="624" alt="Screenshot 2023-09-09 at 5 17 59 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/4009209/0132422d-c549-4627-a093-287a05b167a1">

![image](https://github.com/nature-of-code/noc-book-2023/assets/4009209/d6c938a4-34a8-4e82-b79a-e7651900a812)

**Comment by shiffman** [comment]
Haha! Also fixed!
