### ISSUE TITLE
Chapter 8 Koch curve - code snippet correction

### ISSUE THREAD

**Issue by fturmel** [nature-of-code/noc-book-2#451]
I think you meant to write "let segment **of segments**" here:

<img width="796" alt="image" src="https://github.com/nature-of-code/noc-book-2023/assets/4009209/6805a5e2-1efc-4f52-b87c-07936381bc19">

**Comment by shiffman** [comment]
Great catch, fixed! (will update in the next build)

**Comment by fturmel** [comment]
See my comment on PR #452, it seems like it was only partially corrected.

**Comment by shiffman** [comment]
Re-opening until it's 100% fixed in the build.

**Comment by shiffman** [comment]
It's a miracle I am somehow able to publish a book considering how long it took me to fix this!
