### ISSUE TITLE
Wrong result of `Average Variance` (chp0)

### ISSUE THREAD

**Issue by ManoylovAC** [nature-of-code/noc-book-2#454]
Section [Calculating Mean and Standard Deviation](https://nature-of-code-2nd-edition.netlify.app/random/#calculating-mean-and-standard-deviation)

https://github.com/nature-of-code/noc-book-2023/blob/51ab5ba065996e36be72e935d259bf015c8d3d80/content/00_randomness.html#L332-L333

In the conditions we have an array of 10 score values: [ 85, 82, 88, 86, 85, 93, 98, 40, 73, 83]
so the `Average Variance` result should be equal **`228.81`** but not `254.23` as it now 
```
const scores = [85, 82, 88, 86, 85, 93, 98, 40, 73, 83];
const getTotalSum = (acc, val) => acc + val;

const average = scores.reduce(getTotalSum) / scores.length;
// average = 81.3
const averageVariance = scores.map(score => (score - average) ** 2).reduce(getTotalSum) / scores.length;
// averageVariance = 228.81
```
I see the same inaccuracy in the first edition

**Comment by shiffman** [comment]
Ah, thank you for catching this! Fixed and will be updated in the next build!
