### ISSUE TITLE
Reference typo (chp0)

### ISSUE THREAD

**Issue by ManoylovAC** [nature-of-code/noc-book-2#455]
In 0 Chapter we have only 8 figures

https://github.com/nature-of-code/noc-book-2023/blob/51ab5ba065996e36be72e935d259bf015c8d3d80/content/00_randomness.html#L579
![image](https://github.com/nature-of-code/noc-book-2023/assets/6568745/397dd6f3-a780-4041-af86-bd575c7d72ec)

**Comment by shiffman** [comment]
Ah, thanks for catching this!! It's also fixed now and will be updated in the next build
