### ISSUE TITLE
p5.js sketch borders for "non-example" screenshots?

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#464]
The first stage of the "blank" screen needs its own sketch.

**Comment by shiffman** [comment]
Leaving this open as a reminder to implement the p5.js sketch borders? cc @tuantinghuang @jasongao97 

![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/6ccba7ca-32ae-4560-8c0a-452b6eff3fd9)

**Comment by jasongao97** [comment]
Feature implemented in #529

**Comment by shiffman** [comment]
Any comments about this before I close? I like how it looks a lot! Though I could see how it makes some pages busy and is also a related, but different design to the Examples. @tuantinghuang let us know if you have any comments or adjustments to suggest! Here are some examples:

![Screen Shot 2023-10-20 at 2 36 57 PM](https://github.com/nature-of-code/noc-book-2023/assets/191758/897f1d0f-9091-4557-8081-83439ebb5b84)
![Screen Shot 2023-10-20 at 2 36 54 PM](https://github.com/nature-of-code/noc-book-2023/assets/191758/7a60b0ec-87e1-4f86-94ec-f920e90a65a4)

![Screen Shot 2023-10-20 at 2 38 04 PM](https://github.com/nature-of-code/noc-book-2023/assets/191758/1f94fe94-9aa5-4daf-b006-1a60e50adc6d)
![Screen Shot 2023-10-20 at 2 37 53 PM](https://github.com/nature-of-code/noc-book-2023/assets/191758/c5baa526-76e8-44ad-a90e-e8b1c5bc2c5a)
![Screen Shot 2023-10-20 at 2 37 48 PM](https://github.com/nature-of-code/noc-book-2023/assets/191758/bfa1c46d-862d-46ed-bc52-b65b4d73d4fe)
![Screen Shot 2023-10-20 at 2 37 44 PM](https://github.com/nature-of-code/noc-book-2023/assets/191758/dc4d2e5b-367c-4582-9926-452f0547ec6c)
![Screen Shot 2023-10-20 at 2 37 41 PM](https://github.com/nature-of-code/noc-book-2023/assets/191758/c01eedba-a0a6-40d7-84e4-1775c1f349a9)
![Screen Shot 2023-10-20 at 2 37 30 PM](https://github.com/nature-of-code/noc-book-2023/assets/191758/4bfec7b3-51f9-4d48-a598-34b3dbee9e82)

**Comment by tuantinghuang** [comment]
I like it too! I scanned through the pdf and don't think the busy situation will happen often :)

**Comment by shiffman** [comment]
Yay!
