### ISSUE TITLE
Figure 3.1 360 degrees edit

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#465]
The way 360 degrees is drawn does not match the other angles, it should be as follows:

![IMG_4467](https://github.com/nature-of-code/noc-book-2023/assets/191758/3b278e89-e69a-4dac-80d7-86baded57aed)

Current figure:

![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/99700558-c36c-4d5f-b82e-ad8a5912bd33)

**Comment by zee-em** [comment]
updated and uploaded to Notion and GDrive :)

**Comment by shiffman** [comment]
Perfect! Looks like this one is but just a reminder as we update corrections that all figures can be cropped at the top and bottom to the start of any drawing (the padding will be added in the layout of the book and website).

(we can do a full pass over all of them once everything is finished.)

Thank you @zee-em!!
