### ISSUE TITLE
Code Out of Block

### ISSUE THREAD

**Issue by cemalgnlts** [nature-of-code/noc-book-2#466]
Hi,

The line of code is outside the code block.

![Screenshot 2023-09-16 18 20 50](https://github.com/nature-of-code/noc-book-2023/assets/45357531/74502239-5514-4b80-895c-dbb930b7603c)

https://nature-of-code-2nd-edition.netlify.app/physics-libraries/#matterjs-overview

**Comment by shiffman** [comment]
Strange! I don't see any different formatting in the Notion source. I tried deleting and replacing the table, let's see if it's fixed on the next build.

**Comment by fturmel** [comment]
We might be able to close this issue, it looks OK to me:

<img width="814" alt="Screenshot 2023-09-29 at 8 38 30 AM" src="https://github.com/nature-of-code/noc-book-2023/assets/4009209/e6e49bf2-fbe0-4adf-bc0a-7073c4aa4d2d">

**Comment by shiffman** [comment]
Oh great! I just need to double-check the PDF (i'm prioritizing that now b/c the deadline is this month where the website can be refined over time.)

**Comment by shiffman** [comment]
looking good in the PDF
