### ISSUE TITLE
Chapter 10 y = ax + b figure

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#478]
I'd like to add a figure here, I'll sketch one out that @zee-em can redraw.

<img width="1150" alt="Screen Shot 2023-09-19 at 5 39 45 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/d5eba67a-b69a-4e82-8c16-73f6fcf9dd39">

**Comment by shiffman** [comment]
The equation is now:

$$y = \frac{1}2x - 1$$

![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/2fb53f5e-27b0-49a6-a16e-1dfbb28b70ec)

**Comment by zee-em** [comment]
see issue #552 ??

**Comment by shiffman** [comment]
all set
