### ISSUE TITLE
Chapter 2 - Code snippet error

### ISSUE THREAD

**Issue by fturmel** [nature-of-code/noc-book-2#489]
There's a missing closing paren in the following snippet:

<img width="797" alt="Screenshot 2023-09-28 at 11 09 06 AM" src="https://github.com/nature-of-code/noc-book-2023/assets/4009209/cea3feb2-95b2-401a-9df3-08875ba069cc">

**Comment by shiffman** [comment]
fixed in Notion! @fturmel I'm going to just close these when I edit in Notion even though the fixes won't appear until the build process is run. I assume that the linting will catch it again later if I've messed it up anyway?

**Comment by fturmel** [comment]
Yes, we'll be able to catch similar issues, regressions, etc
