### ISSUE TITLE
Chapter 6 - Matter.js author and library version

### ISSUE THREAD

**Issue by fturmel** [nature-of-code/noc-book-2#498]
The external examples have been updated to use version "0.19.0". References to "0.18.0" should be updated in the book at some point.

There's a placeholder for the author's last name in the "Importing the Matter.js Library" intro paragraph. Full name is "Liam Brummitt" according to the project's readme on github.

**Comment by shiffman** [comment]
Thank you! @liabru, can you confirm that this is the proper way to credit you + year of matter.js?

<img width="744" alt="Screen Shot 2023-09-30 at 9 35 58 AM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/db4f06c2-7685-4bc7-a81a-438b8cb948a2">

Full text: https://nature-of-code-2nd-edition.netlify.app/physics-libraries/

**Comment by shiffman** [comment]
I've updated the versions, will leave open just in case Liam wants to comment.

**Comment by shiffman** [comment]
Closing as it's been a while now and the text is finalized. (I can still change if need be though if something is wrong!)
