### ISSUE TITLE
Chapter 10 - `<script>` snippet language should be HTML (not JS)

### ISSUE THREAD

**Issue by fturmel** [nature-of-code/noc-book-2#499]
<img width="810" alt="Screenshot 2023-09-29 at 7 55 46 AM" src="https://github.com/nature-of-code/noc-book-2023/assets/4009209/7ff53603-8705-4d57-97c0-db5147340221">

---

Chapter 6 seems to be doing it properly:

<img width="806" alt="Screenshot 2023-09-29 at 8 32 27 AM" src="https://github.com/nature-of-code/noc-book-2023/assets/4009209/0cc05a83-71ad-42f6-b48e-601abaadd432">

**Comment by shiffman** [comment]
Interesting! I don't think we're specifying in Notion, maybe this was applied manually for a single use case. @jasongao97, any thoughts? (This is low priority b/c it does not affect the PDF.)

**Comment by shiffman** [comment]
oh, actually, apologies, this is a super easy fix, it is marked in Notion! All set!
