### ISSUE TITLE
Example 6.6 - Code comment in snippet is grouped with "floating" comment

### ISSUE THREAD

**Issue by fturmel** [nature-of-code/noc-book-2#500]
The comment "The anchor is static." I think was meant to be above the line of code and not floating on the side. Not sure if it's a bug or the order of the comments should be swapped?

<img width="793" alt="Screenshot 2023-09-28 at 12 33 20 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/4009209/eca162ed-7939-4b83-adc4-409556b645e2">

This is how it's laid out in the HTML source:

```js
    //{!2} Create two bodies, one for the anchor and one for the bob.
    // The anchor is static.
    this.anchor = Bodies.circle(x, y, this.r, { isStatic: true });
    this.bob = Bodies.circle(x + len, y, this.r, { restitution: 0.6 });
```

**Comment by shiffman** [comment]
@fturmel ah, no this is actually the expected behavior. Multiple lines of comments above a single line will be joined together and float to the side. Do you think it's unclear for any reason (the end result that is?)

**Comment by fturmel** [comment]
The end result is OK, I spotted this while looking at the HTML source. I thought it looked off and was perhaps meant to be inlined since both comments could've just been joined and produce the same formatting.

If that's how it's meant to work and it makes sense in the Notion doc source, then no issues here.
