### ISSUE TITLE
Chapter 5 - single space indentation in two code snippets

### ISSUE THREAD

**Issue by fturmel** [nature-of-code/noc-book-2#501]
The snippets are below example 5.12

<img width="826" alt="image" src="https://github.com/nature-of-code/noc-book-2023/assets/4009209/d597d828-f931-4978-9115-125ae0ff77c8">

**Comment by shiffman** [comment]
Amazing, great catch! Fixing...

**Comment by shiffman** [comment]
Also, realized this would be better as:

let mouse;

```javascript
function setup() {
  mouse = createVector();
}

function draw() {
  mouse.set(x, y);
  for (let v of vehicles) {
    v.seek(mouse);
  }
}
```

**Comment by fturmel** [comment]
I think it should be the following, since there are no `x` and `y` in scope?

```js
mouse.set(mouseX, mouseY);
```

**Comment by shiffman** [comment]
yes, yes, oops, that's what I meant!
