### ISSUE TITLE
chp1: incorrect order of exercises

### ISSUE THREAD

**Issue by ManoylovAC** [nature-of-code/noc-book-2#503]
https://github.com/nature-of-code/noc-book-2023/blob/6eb0ea516c72b4238b9da764d68fed6c4037fbfd/content/01_vectors.html#L311-L318
![image](https://github.com/nature-of-code/noc-book-2023/assets/6568745/66fec8e7-338e-4dee-bdde-59d19876d038)

**Comment by shiffman** [comment]
all set now!
