### ISSUE TITLE
chp1: Typos

### ISSUE THREAD

**Issue by ManoylovAC** [nature-of-code/noc-book-2#504]
### 1. Extra "**and**"
   > second vector **and** **and** placing

   https://github.com/nature-of-code/noc-book-2023/blob/6eb0ea516c72b4238b9da764d68fed6c4037fbfd/content/01_vectors.html#L448
  
  
### 2. No space after the formula
   <img width="364" alt="image" src="https://github.com/nature-of-code/noc-book-2023/assets/6568745/30daad0b-f716-49be-8f35-529986801d67">
   https://github.com/nature-of-code/noc-book-2023/blob/6eb0ea516c72b4238b9da764d68fed6c4037fbfd/content/01_vectors.html#L502
  
### 3. The variable name `topSpeed` in the code is in camel case, but not in comments. In other code examples, this variable is in lowercase.
   <img width="770" alt="image" src="https://github.com/nature-of-code/noc-book-2023/assets/6568745/b8251648-3c97-4c01-a2c6-f354f5f60847">

   https://github.com/nature-of-code/noc-book-2023/blob/6eb0ea516c72b4238b9da764d68fed6c4037fbfd/content/01_vectors.html#L855-L862
  

### 4. of the mouse
   > of. them ouse

   <img width="375" alt="image" src="https://github.com/nature-of-code/noc-book-2023/assets/6568745/15540a81-91fa-43c1-8796-835f29b3c2df">

   https://github.com/nature-of-code/noc-book-2023/blob/6eb0ea516c72b4238b9da764d68fed6c4037fbfd/content/01_vectors.html#L982

### 5. Typo "createI"
   > to createI a new vector

   https://github.com/nature-of-code/noc-book-2023/blob/6eb0ea516c72b4238b9da764d68fed6c4037fbfd/content/01_vectors.html#L994

  
### 6. Extra space before dot
   > object-oriented-programming .)

   https://github.com/nature-of-code/noc-book-2023/blob/6eb0ea516c72b4238b9da764d68fed6c4037fbfd/content/01_vectors.html#L685
  
  
### 7. Extra space before coma
   > Chapter 4</a> , for example

   https://github.com/nature-of-code/noc-book-2023/blob/6eb0ea516c72b4238b9da764d68fed6c4037fbfd/content/01_vectors.html#L792

### 8. The last underscore in `em` tag
   > I must first _____**_**
   
![image](https://github.com/nature-of-code/noc-book-2023/assets/6568745/22842e4d-e887-44ee-94d1-cabe15f8651b)

https://github.com/nature-of-code/noc-book-2023/blob/6eb0ea516c72b4238b9da764d68fed6c4037fbfd/content/01_vectors.html#L995

**Comment by shiffman** [comment]
Fixed all these thank you!!!!
