### ISSUE TITLE
chp1: Exercises show ready answers

### ISSUE THREAD

**Issue by ManoylovAC** [nature-of-code/noc-book-2#505]
Perhaps it is still in the development process, but I decided to highlight that some of the exercises are presented with ready answers

<img width="749" alt="image" src="https://github.com/nature-of-code/noc-book-2023/assets/6568745/75998a0e-bcaf-42cc-a6ad-6325deed7232">

vs 1s edition

<img width="470" alt="image" src="https://github.com/nature-of-code/noc-book-2023/assets/6568745/3fa74629-a5ef-4135-b314-2b714db56ae0">

https://github.com/nature-of-code/noc-book-2023/blob/6eb0ea516c72b4238b9da764d68fed6c4037fbfd/content/01_vectors.html#L834-L839

<img width="744" alt="image" src="https://github.com/nature-of-code/noc-book-2023/assets/6568745/549e43a3-4c82-4182-b979-5e94e1a0cbf0">

vs 1st edition

<img width="397" alt="image" src="https://github.com/nature-of-code/noc-book-2023/assets/6568745/f6438a02-c5f4-49f5-9556-aed614dadb30">

https://github.com/nature-of-code/noc-book-2023/blob/6eb0ea516c72b4238b9da764d68fed6c4037fbfd/content/01_vectors.html#L965-L968

**Comment by dipamsen** [comment]
The website is WIP, on the pdf build i believe this is already implemented.

**Comment by shiffman** [comment]
Correct! You can follow the issue #232 and #380!
