### ISSUE TITLE
chp1: A mouse click on the example saves the image

### ISSUE THREAD

**Issue by ManoylovAC** [nature-of-code/noc-book-2#506]
I think it is not need to save the image when clicking on the canvas from example 1.8
<img width="796" alt="image" src="https://github.com/nature-of-code/noc-book-2023/assets/6568745/75d8bebe-bca8-456f-bdd4-240f4923c5de">

<img width="272" alt="image" src="https://github.com/nature-of-code/noc-book-2023/assets/6568745/3eea3cba-78b3-48e4-aba1-891e327e833f">

https://github.com/nature-of-code/noc-book-2023/blob/6eb0ea516c72b4238b9da764d68fed6c4037fbfd/content/01_vectors.html#L843-L847

**Comment by shiffman** [comment]
Fixed, thank you!!
