### ISSUE TITLE
chp1: Comment line to drawing two vectors

### ISSUE THREAD

**Issue by ManoylovAC** [nature-of-code/noc-book-2#507]
> //{!3} Draw the original two vectors 

<img width="784" alt="image" src="https://github.com/nature-of-code/noc-book-2023/assets/6568745/6c51cbaf-96ee-443a-a0d7-0c74817c663d">

I believe this comment should account for 4 lines due to drawing **two** vectors

https://github.com/nature-of-code/noc-book-2023/blob/6eb0ea516c72b4238b9da764d68fed6c4037fbfd/content/01_vectors.html#L475-L479

**Comment by shiffman** [comment]
fixed now! (won't show up until the next build, but it's easiest for me to close the issue when I update the Notion database. Feel free to doublecheck on the next build!) Thank you for taking the time to find these errors!!
