### ISSUE TITLE
Chapter 6 - tag `[offset-down]` in snippet comments

### ISSUE THREAD

**Issue by fturmel** [nature-of-code/noc-book-2#520]
Just noticed that these are in 2 snippets in Chapter 6.

<img width="796" alt="Screenshot 2023-10-08 at 4 16 48 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/4009209/276b64eb-de0e-4825-b2cd-505d35968b06">

<img width="810" alt="Screenshot 2023-10-08 at 4 17 04 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/4009209/a015ccd1-e5bc-4a42-aa23-21ad2da52cbe">

**Comment by jasongao97** [comment]
Removed! Thank you.
