### ISSUE TITLE
Figure 7.31 hard to read

### ISSUE THREAD

**Issue by fturmel** [nature-of-code/noc-book-2#521]
Not sure if it's because there are large horizontal margins on the image, or the text is just too thin/small, but this image is particularly hard to read. (highlighted to show margins)

<img width="806" alt="Screenshot 2023-10-08 at 4 27 27 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/4009209/5a59ac5b-8e1b-40b1-a3d4-584edb3d5d92">

**Comment by shiffman** [comment]
Ah, good catch! I think this figure is drawn to be a "full width" figure, but it's marked up in Notion as half-width. I am changing it to full width, if we like how that looks this issue can be closed. But leaving it open for @zee-em to take a look in case we want to redraw it for half-width. Next time I build the PDF I can drop a screenshot of it here too.

<img width="811" alt="Screen Shot 2023-10-09 at 9 42 02 AM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/7b2e64e6-723a-4717-8e30-96c3e285207f">

**Comment by shiffman** [comment]
Screenshot of latest PDF render
![Screen Shot 2023-10-20 at 2 30 06 PM](https://github.com/nature-of-code/noc-book-2023/assets/191758/4d2d980f-33f3-4dbd-b43c-433733897f1b)

**Comment by zee-em** [comment]
what revisions are needed here?

**Comment by shiffman** [comment]
leaving as full width!
