### ISSUE TITLE
Chapter 7 errors

### ISSUE THREAD

**Issue by dipamsen** [nature-of-code/noc-book-2#522]
- "Figure 7.3: A one-dimensional line of cells marked with states 0 or 1. What familiar programming data structure ~~that~~ could represent this sequence?"
- Figure 7.7 caption misspelt "neighborhood"
- Elementary CA code comment "Except the center cell is set to state 1." should span single line
- Game of Life - "add 1e to a counter"
- Object Oriented Cells - "I used **a** separate 2D arrays"

**Comment by shiffman** [comment]
Thank you @dipamsen, fixed all of these!
