### ISSUE TITLE
Chapter 8 notes

### ISSUE THREAD

**Issue by dipamsen** [nature-of-code/noc-book-2#523]
- Koch Curve - "a and b are p5.Vector objects" comment should span 2 lines (maybe this is supposed to be automatically handled?)
- "A KochLine needs a methods that returns all five point computed according to the Koch rules." comment should span either 1 or 5 lines.
- Fractal Trees - "Here’s the code for the process illustrated in Figure ~8.19.~ **8.18.**"
- "Translate to the end." comment should span single line
- In the last code snippet before Example 8.6, in the `branch()` function, I think the line `if (len > 2) {` should be highlighted (commented) to mention that it is the exit condition for the recursive function (or, the recursion stops when the length becomes too small). 
  For consistency with other examples, this can also be changed into an if-guard i.e. `if (len < 2) return`, however that probably isn't needed.
- Codesplit comment spans for code snippet under Example 8.7
- L Systems - "Render the text to the canvas." comment should span 3 lines
- "Save the next generation." comment should span 1 line
- (low-priority) In the L-system tables, newlines inside the rules do not appear in web, making it hard to distinguish between the rules. I believe this is correct in the pdf.
  
- "This could also be written with a ~“case”~ **"switch"** statement" ([MDN Reference](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/switch))

**Comment by shiffman** [comment]
@dipamsen are you looking at the comment spanning on the website? We're focusing on the PDF right now and have been fixing bugs that may not have made it through. This is the PDF:

<img width="849" alt="Screen Shot 2023-10-10 at 7 33 38 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/b5be02b7-dcc6-45e7-8493-43854b9c2f72">

if you want to message me on discord i can help provide any fonts or other assets needed for the PDF build. Though we should keep things open / a list of things for the web build after the PDF is fully sent to the printer (end of October?)

**Comment by shiffman** [comment]
I fixed the issues below. I have to do a pass over the code comment spanning on the PDF at some point. Unfortunately I don't have time right now to cross check the website. Will leave open and mark as "future"!

* Fractal Trees - "Here’s the code for the process illustrated in Figure 8.19. 8.18."
* In the last code snippet before Example 8.6, in the branch() function, I think the line if (len > 2) { should be highlighted (commented) to mention that it is the exit condition for the recursive function (or, the recursion stops when the length becomes too small). For consistency with other examples, this can also be changed into an if-guard i.e. if (len < 2) return, however that probably isn't needed.
* "This could also be written with a “case” "switch" statement" ([MDN Reference](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/switch))

**Comment by shiffman** [comment]
@jasongao97 is it possible some of the codesplit features you updated recently perform different on the web build than the PDF? I'm happy to only focus on the PDF right now and we can fix bugs later for the website, but just curious if your expectation is that they are identical.

**Comment by jasongao97** [comment]
> @jasongao97 is it possible some of the codesplit features you updated recently perform different on the web build than the PDF? I'm happy to only focus on the PDF right now and we can fix bugs later for the website, but just curious if your expectation is that they are identical.

Sure! I haven't touched the website part for a while, so they already act differently on both end. I'm happy to make changes to accommodate different formats.

**Comment by shiffman** [comment]
Thanks @jasongao97! I'm fine with holding off on finalizing the codesplit for the website until after we finish the PDF, but if there are quick fixes now to align them together that's a-ok too!

**Comment by shiffman** [comment]
@dipamsen if it's ok with you I might like to close this issue and #525 and just leave open a general purpose "update codesplit behaviors for website to align with PDF" issue. What do you think?

**Comment by dipamsen** [comment]
@shiffman sure. I didn't realise the codesplit behaviours were different for website and pdf.

**Comment by shiffman** [comment]
Not to worry @dipamsen, there's a lot of moving parts here, thank you so much for your generous and incredibly helpful reviews!
