### ISSUE TITLE
Chp 9 table px artifact 

### ISSUE THREAD

**Issue by dipamsen** [nature-of-code/noc-book-2#524]
![image](https://github.com/nature-of-code/noc-book-2023/assets/59444569/ced7a8dc-4e3a-4feb-ad8d-1cf669475107)

**Comment by shiffman** [comment]
Ah, thanks for catching this, the new format is here: https://github.com/nature-of-code/noc-book-2023/issues/368#issuecomment-1752438964 Fixing and closing!
