### ISSUE TITLE
Chapter 9 notes

### ISSUE THREAD

**Issue by dipamsen** [nature-of-code/noc-book-2#525]
- Coding the GA - "First I need two random indices into the mating pool—random numbers between 0 and the size of the array." - `random(matingPool)` can be used directly, as the indexes are not used anywhere else.
- "After the midpoint, take from the partner DNA." comment should span 3 lines
- "Any code here would be executed 1% of the time." comment should use an inline comment (`/* ... */`)
- Example 9.1 Codesplit comment spans
- "A ~PVector~ **vector** pointing in a random direction"
- Smart Rockets - "Your instinct in creating a random vector might be as follows:" - unsure about the placement of this discussion as there are other places before this in the book which use `random2D`. Even in this chapter, before this section there is an example code which introduces the rockets GA example, in which the DNA is constructed using `random2D`.
- "The population" comment should span 1 line
- "Check if rocket hits an obstacle" comment should span 1 line
- "A p5.js button" should span 3 lines

**Comment by shiffman** [comment]
Thank you @dipamsen. I didn't address the codesplit / comment spanning, but I fixed the following:

* using `random(matingPool)` now.
* rewrote the smart rockets section to refer back to `p5.Vector.random2D()` in chapter 3
