### ISSUE TITLE
ordered list, custom numbers

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#526]
In chapter 6, there is an ordered list (1-5) that has a paragraph in between. In notion, the 5 shows restarts the count at 1. I can't figure out a way to manually adjust in Notion (though it's quite likely I've missed this!). @jasongao97 maybe we can just make a manual change during the conversion to HTML?

<img width="781" alt="Screen Shot 2023-10-10 at 6 26 21 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/865c195c-fe27-4718-8866-4008abfac19d">

(I think there is one other place in the book too, I'll add it here when I find it.)

**Comment by shiffman** [comment]
found it! Also, in chapter 10
<img width="1165" alt="Screen Shot 2023-10-10 at 6 35 58 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/3026afff-c591-4b27-b397-8c2817615a6e">

**Comment by jasongao97** [comment]
Can we try this? a notation similar to the custom table column width.

<img width="786" alt="image" src="https://github.com/nature-of-code/noc-book-2023/assets/6762203/2b12454b-bc1f-4b2d-81b2-199cd6c8fc3c">

**Comment by shiffman** [comment]
Yes, this will work great!

**Comment by jasongao97** [comment]
Implemented: https://github.com/nature-of-code/fetch-notion/pull/19

**Comment by shiffman** [comment]
Thank you @jasongao97!!
