### ISSUE TITLE
A whole bunch of issues with the intro chapter

### ISSUE THREAD

**Issue by simon-tiger** [nature-of-code/noc-book-2#53]
I already posted this in the Discord but I feel like this is a better place to put this so I'm reposting it here

---

So in the section with the random walk, you say any given pixel has 8 neighbors. This is sort of correct, but it really depends on what you define as a neighbor. You could define a neighbor as an orthogonally adjacent square and that would be just as correct

---

This particular code snippet is wrong:
```js
// 1 and 3 are stored in the array twice, making them more likely to be picked than 2.
let stuff = {1, 1, 2, 3, 3};
// Picking a random element from an array
let value = random(stuff);
print(value);
```
You have to use square brackets, also I would use `console.log` but if you want you can use `print` it doesn't really matter

---

In I.4 you just refer to a simulation of monkeys that doesn't even exist. Like...you never even introduced it

---

Then there's this paragraph:
<img width="666" alt="Screenshot 2022-08-01 at 15 26 36" src="https://user-images.githubusercontent.com/21979673/182469649-484dbaad-2d8a-4ad3-b240-5508d35eeec5.png">
The `y=x` graph is actually wrong. The probability of any given value being picked is actually zero. What this graph actually is is what's called a "probability density function" (PDF). It doesn't show what the probability is of any one value being picked, it just shows the proportions of those probabilities. That's still not an entirely accurate description but you get what I mean

---

The beginning of chapter 1 still has the old division scheme for the book: the first 5 chapters are about physics, the next 3 about complexity, and the final 2 about intelligence. I'm not saying this is wrong, but especially with swapping chapters 5 and 6, I feel like you're moving to a different system: the first 6 chapters about physics, and the final 4 about...other things

---

Chris Sears posted a thing:
> *Puts on math teacher hat* 
> From the introduction: "Technically speaking, the random number picked can never be 4.0, but rather the highest possibility is 3.999999999 (with as many 9s as there are decimal places)..." Since 3.9999..... = 4.0, you may want to sidestep this part. One possible edit could be: "Technically speaking, the random number picked can never be exactly 4, but numbers like 3.9, 3.99, or 3.999999999 are possible." 
> Is there a GitHub repository for the book? Sorry I missed the live stream where you talked about the book. I feel like a student who missed class.
> *Takes off teacher hat and puts on dunce cap*

This is the famous 0.99999... = 1 theorem. In case you haven't seen it before, here is an algebraic proof:
```
Let's call 0.99999... X
X = 0.99999...

Multiply by 10
10X = 9.99999...

Subtract
9X = 9

Divide by 9
X = 1
```
And here's an intuitive proof:
```
True thing about the real numbers: take two numbers. Unless they're the same, there must be a number greater than one and less than the other (e.g. take the average)

Can you name a number which is in between 0.99999... and 1? You can't, it's impossible. From the above, it thus logically follows that 0.99999... and 1 are the same
```

---

Finally, not a mistake but an idea (not saying you should do this but I just feel like it makes sense): what if you call the intro chapter chapter 0? Everything in code starts at 0 anyway, so I feel like this would be a good idea

**Comment by shiffman** [comment]
Hi Simon, thank you for all of this feedback! As silly as it might be you are welcome to post separate issues for each item. This way I can close them one at a time as I update the text. Some of the fixes are quick and some require additional thinking so I may save until later!

**Comment by shiffman** [comment]
Working on these! A few notes:

1. The monkeys are referenced at the start of I.3.
2. Re: Probability Density Function do you think there is a way this sentence could be rewritten to be more clear? 

>  In other words, if x is the random number, the likelihood of it being picked could be mapped to the y-axis with the function y = x.

3. Since JavaScript has limited decimal places, what if I say:

> Technically speaking, the random number picked can never be 4.0, but rather the highest possibility is 3.999999999 (with as many 9s as JavaScript will allow); since the floor() function lops off the decimal place, the highest possible whole number (aka integer) is 3.

I do like the idea of chapter 0! I'll open a separate issue for that.

**Comment by shiffman** [comment]
The text has been updated to address these comments, closing for now, please re-open or add new issues if you have additional questions and comments!
