### ISSUE TITLE
Grey and rounded box for code snippets and Examples

### ISSUE THREAD

**Issue by tuantinghuang** [nature-of-code/noc-book-2#530]
We discussed some possibilities to implement grey background for code snippets and in the example codes.

1. Extending the rounded box of an example all the way til then end of the code

<img width="1512" alt="Screenshot 2023-10-11 at 9 52 15 AM" src="https://github.com/nature-of-code/noc-book-2023/assets/90000947/a57c68bd-953c-4127-b837-9035590ecca4">

when the code is separated into two pages, the potential to use scissors here- 

<img width="1512" alt="Screenshot 2023-10-11 at 9 52 06 AM" src="https://github.com/nature-of-code/noc-book-2023/assets/90000947/70e7625e-d9f5-4957-8d1d-b74090e638f5">

<br><br>
2. For regular code snippets, if we are using the grey background, maybe we can round it on the four corners ?
<img width="1512" alt="Screenshot 2023-10-11 at 9 51 52 AM" src="https://github.com/nature-of-code/noc-book-2023/assets/90000947/586eb2e3-ad9a-48aa-ac3e-107c133959de">

**Comment by shiffman** [comment]
I think this can be closed now! Yes @jasongao97 and @tuantinghuang?

**Comment by tuantinghuang** [comment]
yes, looks great!
