### ISSUE TITLE
Possible explanation of figure 0.2

### ISSUE THREAD

**Issue by dipamsen** [nature-of-code/noc-book-2#532]
The explanation suggests that the figure shows a graph of a Gaussian distribution, however, it shows two different distributions with different standard deviations. Though this is mentioned in the figure caption, it might not be clear from the figure that it is two different Gaussian distributions. The text above also doesnt match this. (I would expect one figure just showing a single gaussian curve to start with, before showing variations with standard deviation).

![image](https://github.com/nature-of-code/noc-book-2023/assets/59444569/6f3760b2-efe7-4273-aa46-0162bc565761)

**Comment by shiffman** [comment]
Hi @dipamsen I changed it as follows, let me know what you think:

That’s exactly how a normal distribution (sometimes called a “Gaussian distribution” after mathematician Carl Friedrich Gauss) works. A graph of this distribution is informally known as a “bell” curve. The curve is generated by a mathematical function that defines the probability of any given value occurring as a function of the mean (often written as μ, the Greek letter *mu*) and standard deviation (σ, the Greek letter *sigma*).

Figure 0.2 Two example “bell” curves of a normal distribution: low standard deviation on the left, high on the right.

In the case of height values between 200 and 300, you probably have an intuitive sense of the mean (average) as 250. However, what if I were to say that the standard deviation is 3? Or 15? What does this mean for the numbers? The graph depicted in Figure 0.2 should give you a hint. On the left is a distribution with a very low standard deviation, where the majority of the values pile up around the mean (they don’t deviate much from the standard). The version on the right has a higher standard deviation, so the values are more evenly spread out from the average (they deviate more).

**Comment by dipamsen** [comment]
Great! But now the website version will have to be changed to make sense (which can be done later)

**Comment by shiffman** [comment]
Adding a reminder to split this into two different p5.js sketches and incorporate the new design in #464

**Comment by shiffman** [comment]
Tracking in #590 now!
