### ISSUE TITLE
chp2: Some typos

### ISSUE THREAD

**Issue by ManoylovAC** [nature-of-code/noc-book-2#537]
### 1. Coma instead of dot.
> so on), Here I’ve 

https://github.com/nature-of-code/noc-book-2023/blob/36ceaeeab85ec493bf2e28fbeb951d05f63a5d3e/content/02_forces.html#L299

### 2. Question mark instead of dot.

> For example, think of a fan located where the mouse is and pointed toward the circles?

https://github.com/nature-of-code/noc-book-2023/blob/36ceaeeab85ec493bf2e28fbeb951d05f63a5d3e/content/02_forces.html#L342

### 3. Extra "when the mouse is pressed"? Maybe one of the two can be removed??

<img width="778" alt="image" src="https://github.com/nature-of-code/noc-book-2023/assets/6568745/34a32725-d40d-4542-bdc5-5dfacebb7ae8">

https://github.com/nature-of-code/noc-book-2023/blob/36ceaeeab85ec493bf2e28fbeb951d05f63a5d3e/content/02_forces.html#L364

### 4. Extra space after minus

> \- 1/2 is a constan

https://github.com/nature-of-code/noc-book-2023/blob/36ceaeeab85ec493bf2e28fbeb951d05f63a5d3e/content/02_forces.html#L497

### 5. I guess whole phrase should be emphasized but now it's "broken"

> many objects attract many objects
`<em>many obj</em>ects attract <em>many</em> object<em>s</em>`

<img width="430" alt="image" src="https://github.com/nature-of-code/noc-book-2023/assets/6568745/9d2b4fc6-1b2a-48fd-b28f-fc56c215f89a">

### 6. Here used to be a [video link here](https://thecodingtrain.com/tracks/the-nature-of-code-2/noc/2-forces/6-mutual-attraction), but now it's gone
<img width="755" alt="image" src="https://github.com/nature-of-code/noc-book-2023/assets/6568745/aabfec1a-24d1-46aa-9a5e-d60635c0a5f5">

https://github.com/nature-of-code/noc-book-2023/blob/36ceaeeab85ec493bf2e28fbeb951d05f63a5d3e/content/02_forces.html#L1070-L1071

**Comment by shiffman** [comment]
Hi @ManoylovAC thank you so much for this review! The book is now undergoing a professional copy-edit (3-4 weeks) and I believe most of these mistakes will be caught through that. I'll mark this issue as "future" so that I double-check them afterwards. For the "mutual attraction" link, I will be updating and adding URLs and other additional materials for the website after the PDF goes to print.

**Comment by shiffman** [comment]
These are all fixed now!
