### ISSUE TITLE
Embeded examples

### ISSUE THREAD

**Issue by jasongao97** [nature-of-code/noc-book-2#54]
I'm thinking about utilizing `p5-web-editor`'s API (e.g. <https://editor.p5js.org/editor/codingtrain/projects/JmEToUfk>) to fetch and download example codes during website build time (or import time, depending on whether we want it to be tracked by git). So they can be served at the same place as the website with customizations. it could be in subfolders like `content/examples/Nature_of_Code_1:_Vectors_1`.

In this way, only a p5 editor link bookmark need to be added to the `Notion callout block`. 

<img width="1107" alt="Screen Shot 2022-08-04 at 12 01 48 PM" src="https://user-images.githubusercontent.com/6762203/182894547-03484485-26fe-4597-9c13-15250cdfd460.png">

**Comment by shiffman** [comment]
Ah this is a great idea! So https://github.com/nature-of-code/noc-examples-p5.js/ would be deprecated and the source of the examples would be the web editor itself. And when we run `import-notion-docs` all of the examples would be brought into the repo as well! 

One thing to consider is I also make solution exercises, but I could always just put those in another repo and/or create a way of sharing those within the book text itself as well.

**Comment by jasongao97** [comment]
In terms of `solution exercises`, do you mean p5 sketches that don't appear as an embed?

**Comment by shiffman** [comment]
> In terms of `solution exercises`, do you mean p5 sketches that don't appear as an embed?

Yes, exactly! This is lower priority given that I can work this out separately or even after the book/website launches. But it might be interesting to develop something that adds links to sample solutions in the text itself. Let's get the examples going and revisit later?

**Comment by jasongao97** [comment]
> Yes, exactly! This is lower priority given that I can work this out separately or even after the book/website launches. But it might be interesting to develop something that adds links to sample solutions in the text itself. Let's get the examples going and revisit later?

Got it! Links are supported anywhere with rich text. Or do you want a customized style for sample solutions? We can use notion embed for embedded examples and bookmarks for sample solutions if needed. They both can be easily created when pasting an URL in a page.

<img width="736" alt="image" src="https://user-images.githubusercontent.com/6762203/182971652-db2635d3-e43e-4472-9339-e7acdcd82c51.png">

**Comment by shiffman** [comment]
Thanks @jasongao97 I think this could work! Let's revisit the exercise solutions later, I'll open a new issue to track!
