### ISSUE TITLE
Figure 10.1 Neuron Diagram

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#550]
I'm opening a thread to discuss 10.1. 

<img src="https://github.com/nature-of-code/noc-book-2023/assets/191758/b87e8e57-0ed2-4dbd-bfbd-9811f91f0b04" width="400">

The reference (that I provided!) image used is the following:

https://qbi.uq.edu.au/brain/brain-anatomy/what-neuron
<img src="https://github.com/nature-of-code/noc-book-2023/assets/191758/0db8448a-bf31-44f1-8b5e-5d5234c8a2a9" width="300">

Doing some research I think the way the multiple neurons are _floating_ next to each other is off. One idea is to just remove the other neurons. Another is to redraw and try to depict a bit more accurately how a neuron connects via the axon->synapses->dendrites of another neuron.  Here is how wikipedia depicts it:

https://en.wikipedia.org/wiki/Dendrite
![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/c94ab5af-c445-434e-a4a5-afa192924791)

And another from Khan Academy:

https://youtu.be/ob5U8zPbAX4
https://www.khanacademy.org/science/biology/human-biology/neuron-nervous-system/v/anatomy-of-a-neuron
![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/1b4a7eaa-af8d-4301-8170-e3d8476b6165)

And some other example I found:

https://www.researchgate.net/figure/Neural-dendrites-axon-and-synapse-Courche-2013_fig3_270584525
![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/899e5690-3fff-41ad-b540-27f6add2d3db)

https://www.biologyonline.com/dictionary/axon-terminal
![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/dbe21cd9-7f16-43e2-8294-f1ebc38db6b8)

https://www.biologyonline.com/dictionary/axon-terminal
![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/9e7aa45f-f445-4f82-b709-7c476535bb96)

**Comment by zee-em** [comment]
let's chat about this one on our call :)

**Comment by zee-em** [comment]
either show a simplified network or a single neuron

**Comment by zee-em** [comment]
since we're talking about networks I did an illustration based on one of the diagrams you shared of two neurons and an "action potential" that would travel along the axon and stimulate a signaling event. I only labeled the parts that seem relevant.  Let me know what you think!
![Figure_10-1](https://github.com/nature-of-code/noc-book-2023/assets/13405058/8ad72ece-9e40-4ad5-b315-835b92bbeabd)

**Comment by shiffman** [comment]
This is great! I think maybe I might remove the "action potential", it's beyond what I want to try to explain so without defining that it doesn't make sense in the illustration. We can keep the arrow though!  I will also revise the paragraph below to account for the new info in the illustration.

----

To answer these questions, I’ll once again look to nature for inspiration—specifically, the human brain. A brain can be described as a biological neural network, an interconnected web of neurons transmitting elaborate patterns of electrical and chemical signals. Within each neuron, dendrites receive input signals, and based on those inputs, the neuron fires an output signal down its axon to the synapse with the next neuron (see Figure 10.1). Or something like that. How the human brain actually works is an elaborate and complex mystery, one that I’m certainly not going to attempt to unravel in rigorous detail in this chapter.

**Comment by zee-em** [comment]
removed arrow and updated :)

**Comment by shiffman** [comment]
Woohoo!
