### ISSUE TITLE
Figure 10.7, slight adjustment

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#551]
There's a lot going on in this illustration i think it would be a big more clear if some of the elements could maybe be shifted a bit to the left?

![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/20c9fe1f-9a28-4d5c-8212-d1cb2997b399)

* If it helps the axes could be a lighter grey
* They can have arrows on them to match Figure 10.4 better
* We should either include all weights $w_0$, $w_1$, $w_\text{bias}$ or no weights?
* "2D Space" can be removed also if it looks cleaner without.

**Comment by zee-em** [comment]
updated-- is this better?


![Figure_10-7](https://github.com/nature-of-code/noc-book-2023/assets/13405058/680bb802-fb89-48ed-b9a8-9c07bea4900d)

**Comment by zee-em** [comment]
fyi the two axes lines are the same size, I think it's a visual trick that they look different?

**Comment by zee-em** [comment]
stretch the arrows so xy and dot are near each other. slide the dot in the space. move triangle

**Comment by zee-em** [comment]
I've uploaded a new version, please approve :)

**Comment by shiffman** [comment]
This is so great! Three small changes:

1. In top speech bubble the x's needs the subscripts $x_0$ and $x_1$
2. The weight labels should consistently be on the same side of the line and in the center.
3. Remove "as needed" in bottom right speech bubble.

![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/1756d7bd-b4ea-4a97-b3fc-0ecb79335235)

**Comment by zee-em** [comment]
updated and uploaded!

**Comment by shiffman** [comment]
All set!!
