### ISSUE TITLE
Figure 10.8 and 10.9: Graph of y = 1/2x -1

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#552]
The axes should have arrowheads instead of ticks at the end, the line can also include arrowheads and doesn't need to extend to the very edge. Let's also label the axes. Here is a mockup of 10.8, and then the same changes can be applied to 10.9 as well.

![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/c55c5830-e703-4f26-a107-bf73ef917178)

**Comment by zee-em** [comment]
updated, please review. 
![Figure_10-8 4](https://github.com/nature-of-code/noc-book-2023/assets/13405058/53549939-7109-4d3e-b37d-71402d4d9911)

![Figure_10-8b 3](https://github.com/nature-of-code/noc-book-2023/assets/13405058/53ef995f-4cfa-41c1-9ad5-1f28a0ed2221)

**Comment by shiffman** [comment]
great! should say "yline is less than y" and add dots back!

**Comment by zee-em** [comment]
![Figure_10-8b 4](https://github.com/nature-of-code/noc-book-2023/assets/13405058/6032dc71-efbb-46e9-832d-50f72b69cc31)

**Comment by shiffman** [comment]
the dot (4,3) and if you want to remove y-axis and x-axis from this second one that is ok too

**Comment by zee-em** [comment]
uploaded!

**Comment by shiffman** [comment]
10.9 is great! The new illustration for 10.8 still needs to be uploaded to notion.

**Comment by zee-em** [comment]
uploaded :)

**Comment by shiffman** [comment]
Perfect!
