### ISSUE TITLE
Figure 10.10: more blob like?

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#553]
A little more blob like? What if we make the right side of the diagram a little more blob like? I think this will match the way I describe the acidophilic vs. alkaliphilic in the text a little better?

![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/e2c1eba3-7172-4d06-96c8-f9ef5364162e)

**Comment by zee-em** [comment]
updated. Please review, approve, and I'll upload to Notion.
![Figure_10-10 2](https://github.com/nature-of-code/noc-book-2023/assets/13405058/1df5e8a8-1210-4505-991f-fb3df20be0fd)

**Comment by shiffman** [comment]
Yes, add to Notion!

**Comment by zee-em** [comment]
uploaded the approved version above. closing this issue.
