### ISSUE TITLE
Figure 11.2: Flappy Bird Annotation

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#555]
I love these flappy bird illustrations! Some comments:

1. I would love to emphasize the annotations more. Some ideas to consider?
   * remove vines or make the vines layer more transparent?
   * make everything but the annotations a little lighter / more transparent?
   * punch in a bit on the bird?
   * thicken and bold the lines and numbers?
1. For the "y-position" annotations let's add a dot at the end of the horizontal lines.
2. The bird's path is actually flying down (dotted line) but the y-velocity annotation (2) is pointing up. These should be consistent. Maybe adjust the birds path to be on the upswing? (Also, would it make sense for the bird to be in the identical place for 11.1 and 11.2?)

![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/07a0831e-d3a8-4e98-b478-5a82605fcd2c)

**Comment by zee-em** [comment]
Two options, both with lighter vines/pipes and a fixed bird path. We'd use this same path/position for the first figure. Second with a zoom on the bird.  Which one do you prefer? I can also ditch the vines if they are really not working. 

![Figure_11 2 3](https://github.com/nature-of-code/noc-book-2023/assets/13405058/a2ad385c-b28f-487d-a439-fcefead1e29c)

here's the zoom in:

![Figure_11 2 4](https://github.com/nature-of-code/noc-book-2023/assets/13405058/e2fa97eb-713c-4774-aee9-bc7fd3dee54d)

**Comment by shiffman** [comment]
I like the first one!! (but both work if you have a preference?) I think the vines work great now with everything being a little lighter.

**Comment by zee-em** [comment]
new illos updated, please check :)

**Comment by shiffman** [comment]
It looks great!!
