### ISSUE TITLE
Figure 11.3 - height?

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#556]
Maybe hold off on this for a bit b/c I should look at how the layout is in the PDF, but this diagram seems especially tall compared to the other neural network diagrams. This is partially due to the 5 inputs, but also maybe the spacing is a bit wider. I think the dots could be about 50% of the distance from each other vertically and everything tightened up?

![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/a59a0f67-c6f7-4a6f-9b6e-138d90ae68ef)

**Comment by shiffman** [comment]
Now that I checked it actually looks quite nice so maybe leave as is for now?

<img width="1728" alt="Screen Shot 2023-10-30 at 8 27 36 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/79ab0c7c-5436-4c69-8297-ab8238b82d60">

**Comment by zee-em** [comment]
Ok, leaving as is for now. I think larger size this helps a bit with readability as if everything was closer we'd get a very tight tangle of lines to nodes.

**Comment by shiffman** [comment]
Ok, I'm actually going to just close this, one less thing to do! I'll re-open later if there are any layout issues.
