### ISSUE TITLE
To create a page on the website that showcase all the code examples

### ISSUE THREAD

**Issue by jasongao97** [nature-of-code/noc-book-2#573]
A `/code` page that list all the code examples within the book.

Reference: https://github.com/nature-of-code/noc-syllabus-S21/blob/main/noc-examples.md

**Comment by shiffman** [comment]
Here are the comments I posted in #662 for further development and discussion:

> On issue I'm having: the anchor links seem to be correct as far as I can tell, but when I click on them they send me to the wrong place in the book. It's usually a paragraph or two above where the actual example is. Are you seeing this behavior? I tried 4-5 of them randomly and this happened each time.

> I think we could maybe finesse the design a bit in terms of the example title and link to book along with the link to the p5.js web editor version of the example, but we can wait until we're implementing the new design for the website in https://github.com/nature-of-code/noc-book-2023/pull/648. (cc @tuantinghuang)

> Finally, I would love to be able to link to each chapter specifically, we can probably do that with an anchor link but maybe we also have a sub TOC for this page like we do with the chapters.

**Comment by shiffman** [comment]
This is looking wonderful in the new site! Maybe it makes sense to have the thumbnail image (and/or example #) also link to the example? I find myself expecting to click on that.

**Comment by shiffman** [comment]
Closing!
