### ISSUE TITLE
Figure 4.4 + 4.5 change to 90% black

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#577]
Print PDF only, make sure the 4.4 screenshot.png's are different (one circles, one textures)

![Screen Shot 2023-12-05 at 9 09 59 PM](https://github.com/nature-of-code/noc-book-2023/assets/191758/e31ae8de-cafa-477b-b41c-72f4199bcaad)

**Comment by shiffman** [comment]
@tuantinghuang re-assigning to you, but let me know if you need help or you prefer I take care of this!

**Comment by shiffman** [comment]
@tuantinghuang this is completed, yes?

**Comment by tuantinghuang** [comment]
@shiffman yes it is!
