### ISSUE TITLE
add solution to exercise 2.16 and screenshot.png 

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#579]
https://editor.p5js.org/codingtrain/sketches/bEt7eLZ6Y

**Comment by shiffman** [comment]
This has now been added to Notion with the following screenshot.png:

https://editor.p5js.org/natureofcode/sketches/Qxahj4k5D

![screenshot](https://github.com/nature-of-code/noc-book-2023/assets/191758/084e6185-3045-4ad3-9522-73d7b4268a1e)

@tuantinghuang I'm re-assigning this to you in case you want to make any adjustments to the screenshot to match your methodology? If it looks good you can close!

**Comment by tuantinghuang** [comment]
Looks good! Closing this issue now
