### ISSUE TITLE
Debounce drag force (section 2.8)

### ISSUE THREAD

**Issue by sidwellr** [nature-of-code/noc-book-2#58]
There is a small issue in section 2.8 Air and Fluid Resistance: the computed instantaneous drag force can be so large that it causes objects to bounce. This can be disconcerting to readers who try out the code and experiment with different settings and wonder what they did wrong! So it would be helpful to describe the issue: the simulation goes in steps and the large computed drag force is instantaneous and doesn't last the entire step. There is an easy solution: the drag force will cause an object to stop, but never to change direction, so just add a line to limit the drag force to mover.velocity.mag() * mover.mass if the applyForce function divides by the mover's mass, or to mover.velocity.mag() * mover.mass if it doesn't.

**Comment by shiffman** [comment]
I decided to try adding this as an exercise, what do you think?

> You might notice that if you set the coefficient of drag too high in the previous example, the circles may bounce off of the liquid! This is due to the inaccuracy of the large time steps that I mentioned earlier in this chapter. A drag force will cause an object to stop but never to reverse direction. How can you use the vector limit() function to correct this issue? You might also try dropping the objects from variables heights. How does this affect the drag as they hit the liquid?

<img width="804" alt="Screen Shot 2023-02-11 at 3 09 56 PM" src="https://user-images.githubusercontent.com/191758/218279116-55a92f9a-c657-4f43-953e-9edd1fca429d.png">

**Comment by sidwellr** [comment]
I like that. It explains the issue and points readers in the right direction, but lets them figure out the solution.

Spelling error: "variables heights"

**Comment by shiffman** [comment]
fixed the typo!
