### ISSUE TITLE
Equation and Math Font adjusment

### ISSUE THREAD

**Issue by tuantinghuang** [nature-of-code/noc-book-2#580]
Note from publisher - "Can the equation font match the font of the main text? If this isn't possible, I think it’s OK for equations that are set off from the main text to use a different font, but any mathematical expressions that appear in line with the main text should be the same font as the main text. I’ve highlighted the equations throughout the PDF."

![Screenshot 2023-12-06 at 3 50 51 PM](https://github.com/nature-of-code/noc-book-2023/assets/90000947/029535be-f4e4-4be9-8d61-76a7f030f85e)

@jasongao97 to investigate

**Comment by tuantinghuang** [comment]
@shiffman Not sure if this makes sense to discuss here or should file its own issue, but following up with the discussion about Math fonts, I have another question on how can we type in mathematical multiplication sign (x) in Notion? The publisher would like to have "x" displayed in math equations instead of "*". 

<img width="1372" alt="Screenshot 2023-12-08 at 6 24 57 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/90000947/de8e4c00-5247-48f5-9dc9-331530277e0b">

**Comment by shiffman** [comment]
Hi @tuantinghuang, the latex code for the times "x" is `\times`! It'll look like this, I'm updating this one now I'll leave the others for you, let me know if you have more questions!

![Screen Shot 2023-12-08 at 8 46 50 PM](https://github.com/nature-of-code/noc-book-2023/assets/191758/813856ed-6822-44a2-bda7-46040607688f)

**Comment by tuantinghuang** [comment]
Thank you @shiffman ! Just went through Notion and fixed all the "*" signs!

**Comment by shiffman** [comment]
Keeping the math font as is!!
