### ISSUE TITLE
Code monospaced font in code comments

### ISSUE THREAD

**Issue by tuantinghuang** [nature-of-code/noc-book-2#581]
notes from publisher - "Do you want to use code font in comments, and if so, is that possible? For example, in “Initialize the Attractor object,” “Attractor” would be in code font. I haven’t marked which words would need to be changed, but if it’s possible to use a different font for these terms, I can have the proofreader mark them."

![Screenshot 2023-12-06 at 3 53 40 PM](https://github.com/nature-of-code/noc-book-2023/assets/90000947/9a63ca10-717a-4e4e-bdba-ae38c2a55e9b)

@tuantinghuang to make a sample

**Comment by tuantinghuang** [comment]
@shiffman A quick mockup! If it's not hard to implement, I'm leaning more towards code font now. But also wondering if you think they would need more styling to separate them from the comment text?

<img width="683" alt="Screenshot 2023-12-15 at 1 52 39 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/90000947/57cd014f-7ffb-4d67-b166-086b31356cfb">

**Comment by shiffman** [comment]
@tuantinghuang I think this looks great actually! The main issue is figuring out how to mark this up properly in Notion which might be quite the effort. I think a next step would be try marking up one or two code snippets. @jasongao97 what would you suggest we try? We could do something like italics or underline in Notion as an indicator that it should be styled with monospace? Or make up our own mark-up like:

```
vector can be accessed via the *mag()* function.
```

**Comment by jasongao97** [comment]
Can we try the markdown inline code style with backticks, like:

```
vector can be accessed via the `mag()` function.
```

**Comment by shiffman** [comment]
> Can we try the markdown inline code style with backticks, like:
> 
> ```
> vector can be accessed via the `mag()` function.
> ```

Yes, of course, thank you @jasongao97 this makes the most sense! If you want to go ahead and implement it for a few code snippets / examples, then we can evaluate it and add it to the rest of the book if we like it. Thank you!

**Comment by shiffman** [comment]
Double check that it looks good in the PDF and then go through and markup all the examples!

**Comment by shiffman** [comment]
@tuantinghuang @jasongao97 i think we should shrink the monospace font size to match the rest of the comment text as best as possible. I can try addressing this.

<img width="700" alt="Screen Shot 2024-01-06 at 10 29 44 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/ac60947e-0d88-4e6e-a30a-650f10a4edc4">

**Comment by shiffman** [comment]
Trying 7pt in #622
