### ISSUE TITLE
URL render in PDF

### ISSUE THREAD

**Issue by tuantinghuang** [nature-of-code/noc-book-2#582]
The publisher would like the full URL to appear in the printed version (i.e., the PDF), but it doesn’t need to appear in Notion or the ebooks if the text referring to the URL is hyperlinked. In the print version, only the URL needs to be linked (not the text referring to it).

@shiffman to ask the publisher if he can change it so that all URLs show up as in parenthesis after the text that is linked.

Will also need a way to not render a URL twice if it's the actual raw text of the book (see screenshot example)
![Screenshot 2023-12-06 at 3 59 21 PM](https://github.com/nature-of-code/noc-book-2023/assets/90000947/570746e7-3b54-47d9-8716-4250eb270837)

**Comment by shiffman** [comment]
Our goal is to have all URLs now be linked in Notion to text and render in parenthesis in the PDF. Let's keep track of any spots in the book where this won't work, but hopefully we can adapt to have no exceptions?

**Comment by shiffman** [comment]
I've completed changing all of the URLs to be linked directly in Notion for rendering to the PDF in parentheses. This includes both URLs in the introduction and the image credits so there should be no exceptions to this rule anymore!  I'll leave this open just as a reminder to double-check.

**Comment by shiffman** [comment]
I'm double-checking the PDF render and a lot of the URLs have a trailing `/` character which I would prefer to remove for cleanliness. I'll do another round and fix that up.

**Comment by shiffman** [comment]
did a round of this!
