### ISSUE TITLE
Prince XML Logo

### ISSUE THREAD

**Issue by tuantinghuang** [nature-of-code/noc-book-2#583]
@shiffman to double check the prince XML license and re-purchase if need be

![Screenshot 2023-12-06 at 4 02 38 PM](https://github.com/nature-of-code/noc-book-2023/assets/90000947/56898664-19ae-44fb-8577-78eb4725ddd0)

**Comment by shiffman** [comment]
Adding @jasongao97 to this! I have the `license.dat` file but am not sure the best way to integrate it into the build process. There is documentation in the prince node package: https://www.npmjs.com/package/prince

```
Prince#license(filename): Prince: set the path to the PrinceXML license file. This by default uses the path license/license.dat under the PrinceXML installation. This returns the Prince API for further method chaining.
```

We should just make sure the license file is part of `.gitignore` if we include it in our builds.

**Comment by shiffman** [comment]
Need to double-check updated purchase for current princeXML version.

**Comment by shiffman** [comment]
This is all set now!
