### ISSUE TITLE
Remove italics from Chapter Opening Quotes 

### ISSUE THREAD

**Issue by tuantinghuang** [nature-of-code/noc-book-2#584]
The quotations should stay in italics but remove italics from the source lines.

![Screenshot 2023-12-06 at 4 04 27 PM](https://github.com/nature-of-code/noc-book-2023/assets/90000947/064b2ae1-d1ae-4b8f-b52c-c6cdde0d0670)

**Comment by shiffman** [comment]
Confirming Chapter 0 is fixed with #597, leaving open for @tuantinghuang to update Notion for all chapters.

**Comment by tuantinghuang** [comment]
Notion updated and just rendered pdf to check. It looks great!

**Comment by shiffman** [comment]
Thank you @tuantinghuang!
