### ISSUE TITLE
End-of-chapter projects styling

### ISSUE THREAD

**Issue by tuantinghuang** [nature-of-code/noc-book-2#585]
Add styling the headings like "Step 0 Exercise" to differentiate from the copy text.

![Screenshot 2023-12-06 at 4 06 10 PM](https://github.com/nature-of-code/noc-book-2023/assets/90000947/937e4cc2-ca4d-40b4-86c7-dff63b223b94)

**Comment by tuantinghuang** [comment]
Since there is an illustrated icon for the ecosystem already, I tried to keep the styling simple and only added bold to the "Step x Exercise." (I did it from Notion) @shiffman does this look okay to you?

<img width="663" alt="Screenshot 2023-12-13 at 4 59 35 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/90000947/e430e338-f9b1-4f46-9f01-36f64a1d438d">

**Comment by shiffman** [comment]
I wonder if we need this at all? What if it just said Ecosystem Project at the end of every chapter? I think it's clear to the reader that if we're in Chapter 2, it's step 2! What do you think?

**Comment by tuantinghuang** [comment]
I agree! I think since the ecosystem project is introduced in the introduction chapter and readers know it'll be at the end of each chapter, we don't really need this? One thing is in chapter 0 - there is an italic recap text before explaining the prompt. Would it will be as clear without the step 0 exercise? 

<img width="682" alt="Screenshot 2023-12-14 at 9 16 44 AM" src="https://github.com/nature-of-code/noc-book-2023/assets/90000947/3d464bef-cc1c-46b8-9b6f-f0e1981355d4">

**Comment by shiffman** [comment]
ah yes, let me think about how to reword this! I'll check with No Starch as well to  confirm!

**Comment by shiffman** [comment]
This has been completed and chapter 0 has been rewritten.
