### ISSUE TITLE
Figure 9.13 is Cut Off

### ISSUE THREAD

**Issue by tuantinghuang** [nature-of-code/noc-book-2#587]
Is the figure 9.13 cut off on the top? Check original image / ask Zannah.

![Screenshot 2023-12-06 at 4 21 23 PM](https://github.com/nature-of-code/noc-book-2023/assets/90000947/c70ac103-21fc-4f60-8a05-e0906e40c006)

**Comment by shiffman** [comment]
Hi @zee-em, did you mean for this bloop to be cutoff? Without a border to the image it looks a little strange, shall we adjust to see the full large bloop?

**Comment by zee-em** [comment]
This has been revised and uploaded to Notion!

**Comment by shiffman** [comment]
Hi @zee-em I'm just double-checking this and I don't see the new image in Notion, can you double-check? Thank you!!

**Comment by zee-em** [comment]
re-uploaded, pls check :)

**Comment by shiffman** [comment]
Yes, looks good!!!
