### ISSUE TITLE
Turn Figure 6.18 into a p5 sketch

### ISSUE THREAD

**Issue by tuantinghuang** [nature-of-code/noc-book-2#589]
Turn the figure into a p5 sketch to get the frame border

![Screenshot 2023-12-06 at 4 22 58 PM](https://github.com/nature-of-code/noc-book-2023/assets/90000947/42147968-f42e-43bd-9ccc-4e5430932b16)

**Comment by shiffman** [comment]
Completed! I think I should leave open, however, until I confirm it is rendering correctly in the build.

**Comment by tuantinghuang** [comment]
Looks great! Closing the issue now
