### ISSUE TITLE
Figure 0.2 Render not aligning

### ISSUE THREAD

**Issue by tuantinghuang** [nature-of-code/noc-book-2#590]
Figure 0.2 is separated and rendered as 2 images. However, since the one on the right doesn't have a caption, the alignment is a bit off.

![Screenshot 2023-12-06 at 8 45 44 PM](https://github.com/nature-of-code/noc-book-2023/assets/90000947/f5f4a653-bb12-4a26-9448-570287fbd0e7)

**Comment by shiffman** [comment]
I had an error in the Notion formatting which is now fixed in #592 

<img width="834" alt="Screen Shot 2023-12-06 at 11 09 43 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/c08af9e5-ffc1-4003-9c52-0382a112d738">
