### ISSUE TITLE
Add Descriptions to links in the Introduction

### ISSUE THREAD

**Issue by tuantinghuang** [nature-of-code/noc-book-2#591]
You can find the full version of the code on the book’s website. There, you can interact with, modify, and experiment with the code in the [p5.js Web Editor](https://editor.p5js.org/). Additionally, everything is included in the book’s GitHub repository. Here are the full URLs to access all the materials:

- https://natureofcode.com
- https://github.com/nature-of-code
- https://editor.p5js.org/natureofcode/sketches

> Once all the website info is solidified, this section may benefit from a brief explanation of what exactly is on each site (and maybe how to find it, unless it's so self-explanatory once the reader gets to the site)

**Comment by shiffman** [comment]
This has been completed as part of my work on #582
