### ISSUE TITLE
Sublists' bullets in another list

### ISSUE THREAD

**Issue by tuantinghuang** [nature-of-code/noc-book-2#600]
When there's another list under a list, the points should be rendered as "a., b.,..." instead of numbers. Although we are using a. b. in Notion, it is not rendered in the pdf.

PDF Render:
<img width="1398" alt="Screenshot 2023-12-08 at 6 53 03 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/90000947/3e866628-ff33-4a57-9177-c0f6d13662df">

Notion:
<img width="845" alt="Screenshot 2023-12-14 at 10 12 46 AM" src="https://github.com/nature-of-code/noc-book-2023/assets/90000947/c8d5fcd1-cc17-423e-ad73-b6a8faaf543b">

**Comment by tuantinghuang** [comment]
@jasongao97 I'm not sure how to approach this...we probably need a conditional statement to detect if a list is within a list. Do you have any thoughts on this?

**Comment by jasongao97** [comment]
Implemented in #605
