### ISSUE TITLE
Repeated paragraph in Ch. 2

### ISSUE THREAD

**Issue by iyzg** [nature-of-code/noc-book-2#609]
<p>This still causes confusion because it sounds like these forces would always cancel each other out. This isn’t the case. Remember, the forces act on different objects. And just because the two forces are equal doesn’t mean that the objects’ movements are equal (or that the objects will stop moving).</p>

<p>This still causes confusion because it sounds like these forces would always cancel each other out. This isn’t the case. Remember, the forces act on different objects. And just because the two forces are equal doesn’t mean that the objects’ movements are equal (or that the objects will stop moving).</p>

^ This section is repeated twice

**Comment by shiffman** [comment]
Ah, thanks for catching this! It's fixed now! (won't be live on the site until the next build)
