### ISSUE TITLE
Drag force velocity is relative (section 2.8)

### ISSUE THREAD

**Issue by sidwellr** [nature-of-code/noc-book-2#61]
Section 2.8 on the drag force states that v refers to the speed of the object moving. This is correct, but there is a subtle omission: v refers to the speed of the object moving relative to the fluid. So there is an unstated assumption that the fluid is not moving; if the fluid has a velocity (for example, dropping objects into a river), you need to subtract the fluid velocity from the object velocity before taking its magnitude. Similarly, for the direction, v-hat.

There are a few ways to address this:

1. Ignore it; the section is complicated enough without it. Astute readers who ask themselves how to model dropping objects into a river will figure it out pretty easily.

2. In the descriptions for v and v-hat, state the assumption that the fluid is stationary. Perhaps add a parenthetical comment that we would need to subtract the fluid's velocity if isn't.

2a. In addition to 2, add an exercise to drop objects in a moving stream instead of a pool so readers can explore how to do this.

3. Rewrite the descriptions to state that v and v-hat refer to the relative speed and direction: the object velocity minus the fluid velocity. Also rewrite the code to incorporate this. This isn't difficult, but it increases the complexity of an already complicated topic. And you'd need to decide whether to redo the video to include it.

Of course, since the fluid creating drag can be moving air, this can provide a more realistic method for modeling wind than the simple method used in section 2.5. There are several ways to approach this as well, from ignoring it to writing a new section "Revisiting Wind" describing how to do it and philosophizing about when to use each method.

**Comment by shiffman** [comment]
This is such a good comment!! I'm a little overwhelmed with rewrites and trying to keep this project moving forward. For now, I'm adding a parenthetical, although maybe this is a better exercise prompt than the "lift" one you can see in #58. I could replace that one? 4 exercises there is probably too much? I could also remove the surface area one.

**Comment by shiffman** [comment]
Here's the parenthetical:

> - $v$ refers to the speed of the object moving. OK, you’ve got this one! The object’s speed is the magnitude of the velocity vector: `velocity.mag()`. And $v^2$ just means $v$ squared or $v \times v$. (I’ll note this assumes the liquid or gas is stationary and not moving, if you drop an object into a flowing river you’d have to also take the relative speed of the water into account!)

**Comment by sidwellr** [comment]
I would just leave the parenthetical. Readers who are really interested can make their own exercises! I think the surface area exercise is particularly enlightening, so would not remove it.
