### ISSUE TITLE
Missing line break in table (math formula)

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#610]
@jasongao97 any ideas on how to force a line break for these two tables in Chapter 8?

![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/d4decea2-52b5-4697-8727-359a9472781f)
![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/e7be7892-bf63-4932-86fe-73d03eb1447d)

Notion:
<img width="832" alt="Screen Shot 2023-12-26 at 4 28 44 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/a192a252-a964-4dd4-a236-daac8884ef73">

<img width="842" alt="Screen Shot 2023-12-26 at 4 31 01 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/52dd0218-53fc-4e76-bce1-691f2bee5c97">

**Comment by shiffman** [comment]
copy edit note to change AB to body font, but for L-System notation I think it's better to keep the math font.

**Comment by shiffman** [comment]
@tuantinghuang let's change it back for now

**Comment by shiffman** [comment]
All of these are changing from math formula to body font but this issue still exists.

**Comment by jasongao97** [comment]
Added custom raw HTML in table cell

```
<div style="white-space: pre-wrap;">A → ABA
B → BBB</div>
```

<img width="771" alt="image" src="https://github.com/nature-of-code/noc-book-2023/assets/6762203/ba4bab08-4918-4f7f-9f77-19b5e425f370">

**Comment by shiffman** [comment]
Oh, this is a smart way of doing it!!

**Comment by jasongao97** [comment]
Change to span element to avoid generating extra space

```
<span style="white-space: pre-wrap;">A → ABA
B → BBB</span>
```

**Comment by jasongao97** [comment]
Checked the latest build and it is fixed.
