### ISSUE TITLE
Math formula in code comments

### ISSUE THREAD

**Issue by tuantinghuang** [nature-of-code/noc-book-2#612]
Is it possible to style code comments with math fonts?

<img width="1258" alt="Screenshot 2024-01-04 at 10 05 19 AM" src="https://github.com/nature-of-code/noc-book-2023/assets/90000947/f0aa8b3f-526a-446c-b958-4efd7fb409e7">

**Comment by shiffman** [comment]
DS to rewrite the comment

**Comment by shiffman** [comment]
New comment text:

<img width="607" alt="Screen Shot 2024-01-06 at 10 25 48 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/5008c35c-9e52-447e-a051-2538076beea5">
