### ISSUE TITLE
Heading 4 in Notion (Chapter 5 and 10)

### ISSUE THREAD

**Issue by tuantinghuang** [nature-of-code/noc-book-2#613]
In Chapter 5 and 10, there are places we are using a callout box for this heading. The publisher suggested that we change this to heading 4, but there's no default heading 4 in Notion as an option. @shiffman I forgot if we had a reason for the current styling, or if we should just give this callout box another css styling, ie. using the callout box as a markup to style it as heading 4?

<img width="600" alt="Screenshot 2024-01-04 at 10 14 12 AM" src="https://github.com/nature-of-code/noc-book-2023/assets/90000947/a49de873-6b18-4486-9cf5-b95f7151b662"><br/><br/>

Notion markup:
<img width="600" alt="Screenshot 2024-01-04 at 10 14 53 AM" src="https://github.com/nature-of-code/noc-book-2023/assets/90000947/b4532a15-4b36-487b-ab50-33625c2e0df5"><br/><br/>

Other examples in the pdf: 
<img width="400" alt="Screenshot 2024-01-04 at 10 18 53 AM" src="https://github.com/nature-of-code/noc-book-2023/assets/90000947/b8076ea0-b94d-42d1-9e99-cb835285cc78">

**Comment by shiffman** [comment]
Use calllout box to indicate h4 then we just need standard styling for h4 in the PDF
