### ISSUE TITLE
Styling math formulas

### ISSUE THREAD

**Issue by tuantinghuang** [nature-of-code/noc-book-2#614]
Is it possible to style math formulas? 
Two places that the publisher suggested edits -

1. bolding the multiplication sign in a table:

<img width="1232" alt="Screenshot 2024-01-04 at 9 51 09 AM" src="https://github.com/nature-of-code/noc-book-2023/assets/90000947/6f0ddcd7-534a-4683-a515-c51834e152b0"><br/><br/>

2. adding extra space before and after minus sign: 
(I tried adding space in Notion, but it won't show up)

<img width="1319" alt="Screenshot 2024-01-04 at 9 34 02 AM" src="https://github.com/nature-of-code/noc-book-2023/assets/90000947/9bbbb8f1-13d2-4707-bf40-ee4c10c0e746">

**Comment by jasongao97** [comment]
I've updated the bold sign in Notion with `\boldsymbol{\times}`. Regarding the second one, I believe we could incorporate spaces using Katex. However, I'm a bit uncertain about the styling choices. How do you think about this? @shiffman
