### ISSUE TITLE
Spacing and new lines will be final checked

### ISSUE THREAD

**Issue by tuantinghuang** [nature-of-code/noc-book-2#619]
The publisher mentioned some spacing and new line issues, will fine tune and double check all the big spaces once the content is set!

Some examples:
<img width="1200" alt="Screenshot 2024-01-04 at 4 47 40 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/90000947/78e24dc7-d591-4ad3-91bb-2595afaa7cd9"><br/><br/>

<img width="1200" alt="Screenshot 2024-01-04 at 4 47 32 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/90000947/21f5c219-b425-4ae2-9503-830838b12ac9"><br/><br/>

<img width="1200" alt="Screenshot 2024-01-04 at 4 48 05 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/90000947/e196eb60-d90b-4b0b-86ec-10e3a4604c93"><br/><br/>

**Comment by shiffman** [comment]
Closing this issue in lieu of more specific ones in the latest round.
