### ISSUE TITLE
Drag force constant (section 2.8)

### ISSUE THREAD

**Issue by sidwellr** [nature-of-code/noc-book-2#62]
The drag force video did a great job of explaining how many of the items in the drag equation are constants that are combined together into one constant c in the code. Section 2.8 conflates the combined constant c with the coefficient of drag, one of its components. It works, but the approach in the video seems more correct. Please consider rewriting the descriptions in 2.8 to align with the video. (For A, note that is part of the constant, but could be separated; see exercise 2.6 (or whatever the number ends up as after renumbering the exercises; section 2.5 has several labeled "Exercise 2.x").)

**Comment by shiffman** [comment]
Here's a new paragraph I added, what do you think?

> While I’ve written the formula above with $C_d$ as the lone constant representing the “coefficient of drag”, I can also think of it as all of the constants combined ( $-1/2$, $\rho$, $A$). A more sophisticated simulation might consider them separately and could be considered an exercise for the reader.

<img width="860" alt="Screen Shot 2023-02-10 at 8 19 12 PM" src="https://user-images.githubusercontent.com/191758/218230653-04ec2c35-bf3d-4abd-8f44-f78312b7edc4.png">

**Comment by sidwellr** [comment]
That is helpful. Thanks.
