### ISSUE TITLE
Repeller class inconsistent in section 4.12

### ISSUE THREAD

**Issue by sidwellr** [nature-of-code/noc-book-2#63]
In section 4.12, Particle Systems with Repellers, the final repeller class code at the end of the section is confusingly different from the code described earlier in the section. Different variable names are used and the earlier version uses setMag() while the final version multiplies the unnormalized direction by the computed force. This should be reconciled. The variable names used in the final version are preferable, but "constrain(d, 5, 100)" should be "constrain(distance, 5, 100)", and change "dir.mult(force)" to "dir.setMag(force)". Then change the earlier version to match.

**Comment by shiffman** [comment]
I've made these consistent now, thank you! (next website update to follow later today!)
