### ISSUE TITLE
Use start point (not end point) when normal point is off a segment (section 6.9)

### ISSUE THREAD

**Issue by sidwellr** [nature-of-code/noc-book-2#64]
In section 6.9, Path Following with Multiple Segments, if the normal point is not between the endpoints, a and b, of some segment, you pretend the end point, b, of the segment is the normal. But if you then set the target a little further along the path as explained in section 6.8, the target will be off of the segment. This can sometimes trap a vehicle that continually sees that target as the closest. A better solution is to pretend the start point, a, of the segment is the normal when the normal is off the segment. This will keep the target on the segment and have a more stable result. Also, a vehicle that is near the intersection of two segments but not on either one should go towards the segment that starts at the intersection, not the one that ends there; this will happen if the "pretend" normal point is a.

**Comment by shiffman** [comment]
Ah, yes, this is a good point, however, with my example that "wraps" the vehicles around the right edge of the canvas, they end up steering back towards the beginning of the "last" segment as they leave the canvas. I've temporarily changed this here https://editor.p5js.org/natureofcode/sketches/1T-6LupvJ. I'm leaving this open now to revisit, let me know if you have any further thoughts.

**Comment by shiffman** [comment]
I went back to the end point b/c my example works best, but included this caveat:

> If it’s not within the line segment, I’ll just pretend the end point of that line segment is the normal. (You might also try the beginning point, depending on the particulars of your path.) This will ensure that the vehicle always stays on the path, even if it strays out of the bounds of the line segments themselves.

Closing as I'm down to the wire, but welcome further discussion!
