### ISSUE TITLE
Adding page number references

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#644]
There are several spots in the book that say "see page XX", this can be added manually in later when the PDF is finalized or we can consider having the page number reference be auto-generated, this is a capability of "magic book" / paged media CSS.

**Comment by jasongao97** [comment]
The feature is currently working for links targeting specific blocks (anchor points). However, it's broken for ones pointing to paths which are lost when the content is merged into a single file. I'd love to work on a solution and implement a transformation to address this problem.

**Comment by shiffman** [comment]
tracking in #673
