### ISSUE TITLE
Things to add to the website

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#645]
These are some temporary things we should maybe add to the website header while we're waiting to implement @tuantinghuang's design? 

* link to https://thecodingtrain.com/ using CT logo
* link to github repo (using github icon?) or maybe a heart icon to link to: https://github.com/sponsors/CodingTrain
* temporary link to "noc archive": https://nature-of-code.github.io/natureofcode.com/

**Comment by shiffman** [comment]
These are now completed but where might we link to the old archive just in case? (Maybe it's not necessary and can just go in the README of this repo)

**Comment by jasongao97** [comment]
> These are now completed but where might we link to the old archive just in case? (Maybe it's not necessary and can just go in the README of this repo)

Sure! May I ask where the archived website is hosted? Is it on GitHub Pages?

**Comment by shiffman** [comment]
Oh, I forgot I moved it!

https://noc-processing-archive.netlify.app/
https://github.com/nature-of-code/Nature-of-Code-Website-Archive

**Comment by shiffman** [comment]
Let's, for now, just put the archive in GitHub README and maybe it can go on #947

**Comment by shiffman** [comment]
Should be all set now
