### ISSUE TITLE
Typo in Introduction -> A word about p5.js

### ISSUE THREAD

**Issue by DevinCLane** [nature-of-code/noc-book-2#647]
> All that said, nothing that this book’s content strictly to p5.js—or Processing, for that matter.

Might want to read:

> That said, nothing in this book's content is strictly related to p5.js.

Cheers!

**Comment by shiffman** [comment]
Thank you for the feedback! Even though the book is published with p5.js now, I will still be maintaining Processing versions of all of the examples so prefer to keep that extra addendum!

**Comment by DevinCLane** [comment]
Oh yes, I'm not drawing attention to content or meaning of this sentence, but rather a minor grammatical typo/confusion. As it's written:

> All that said, _nothing that_ this book’s _content strictly to_ p5.js—or Processing, for that matter.

It seems to be missing a verb and/or a preposition to me. I believe what you're trying to say is that there is: 

> nothing _in_ this book's content _that is_ strictly _tied_ to p5.js--or Processing, for that matter. 

The specific words chosen are somewhat up to style of course, but I understand the sentence to mean "you can use these concepts in any language you want". So you might say strictly tied/related/bound/limited to, etc.

I hope I clarified the point I'm trying to make. Love the work!

**Comment by shiffman** [comment]
Oh, whoops! Yes, I see now!

**Comment by shiffman** [comment]
Completed
