### ISSUE TITLE
Maximum speed (section 6.3)

### ISSUE THREAD

**Issue by sidwellr** [nature-of-code/noc-book-2#65]
The concept of "maximum speed" for an object is introduced in section 1.8 (as "topspeed"), completely ignored in chapters 2, 3, and 4, then suddenly used again in chapter 6 (as "maxspeed") to use with steering behaviors. It may be useful to include an explanation of why and when this is needed. Perhaps something like this (feel free to use, modify, or ignore it; first and last lines are existing text):

In other words, the vector should point from position to target with a magnitude equal to maximum speed (i.e., the fastest the vehicle can go). You may have noticed I used maximum speed back in section 1.8, but then ignored it in the succeeding chapters. Perhaps you are wondering just when maximum speed should be used. The answer is simple: use it when it is needed but don't use it when it is not. I needed it in chapter 1 to keep the speed in a reasonable range. I didn't need it in chapter 2 because other forces (friction and drag) kept the speed checked, or chapter 3 because oscillation is caused by opposing forces that keep the speed limited. Nor did I need it for particles because they had a lifetime. 

But here, I'm ignoring forces such as friction and drag for simplicity, to focus on steering forces, so I need to limit the speed. First, I’ll need to make sure to add a property to the Vehicle class for maximum speed itself.

**Comment by shiffman** [comment]
This is fantastic feedback! I'm working this into chapter 5 (I swapped the orders of 5 and 6) and will report back here with an update soon.

**Comment by shiffman** [comment]
Here is what I settled on, feel free to let me know if you have additional comments!

> In other words, the vector should point from the vehicle's current position to the target position, with a magnitude equal to the maximum speed of the vehicle. The concept of maximum speed was introduced in Chapter 1 to ensure that the speed remained within a reasonable range. However, I did not always use it in the succeeding chapters. In Chapter 2, other forces such as friction and drag kept the speed in check, while in Chapter 3, oscillation was caused by opposing forces that keep the speed limited. In this chapter, maximum speed is a key parameter for controlling the behavior of a steering agent, so it will be included in all the examples.

**Comment by shiffman** [comment]
Closing!
