### ISSUE TITLE
No scissors icon

### ISSUE THREAD

**Issue by ManoylovAC** [nature-of-code/noc-book-2#650]
### The introduction mentions a scissors icon for code snippets, but I don't see them in the online version of the book

> <img width="800" alt="image" src="https://github.com/nature-of-code/noc-book-2023/assets/6568745/e351e35f-7ac7-47d2-82f3-3111c45e1db2">
> <img width="794" alt="image" src="https://github.com/nature-of-code/noc-book-2023/assets/6568745/e0c7306d-9039-4e5b-926a-ae7e05d76a2c">

https://github.com/nature-of-code/noc-book-2023/blob/087f32e0db54328f7e7ccd1ba0dc13298eb00b62/content/00_5_introduction.html#L160

**Comment by shiffman** [comment]
Ah yes, this has been implemented for the PDF print version of the book (see #447) but not yet for the website. @ManoylovAC if you are interested in reviewing the PDF to check these, let me know!

**Comment by ManoylovAC** [comment]
@shiffman yes, I would be interested in reviewing the pdf version of the book)
However, I have not yet built it locally.

I also wonder if it's designed so that the "chapter-opening-figure" blocks will not be available in the online version?

**Comment by shiffman** [comment]
> @shiffman yes, I would be interested in reviewing the pdf version of the book) However, I have not yet built it locally.
> 
> I also wonder if it's designed so that the "chapter-opening-figure" blocks will not be available in the online version?

Could you [reach out to me at my NYU email](https://itp.nyu.edu/itp/daniel-t-shiffman/) or provide a way to contact you? Thank you!

**Comment by ManoylovAC** [comment]
You can contact me via epistolariy@ukr.net or manoylov.ac@gmail.com whichever is more convenient
