### ISSUE TITLE
Chapter 0. No figcaption for Figure 0.9

### ISSUE THREAD

**Issue by ManoylovAC** [nature-of-code/noc-book-2#651]
Chapter 0 has no any image caption with title **Figure 0.9**. I guess it can be added to the next one?

> ![image](https://github.com/nature-of-code/noc-book-2023/assets/6568745/8a6cd1f4-f356-4064-9fd2-067d198e3eee)

https://github.com/nature-of-code/noc-book-2023/blob/087f32e0db54328f7e7ccd1ba0dc13298eb00b62/content/00_randomness.html#L598C300-L598C310

**Comment by shiffman** [comment]
Fixed
