### ISSUE TITLE
Chapter 3. Two different images numbered as `Figure 3.19`

### ISSUE THREAD

**Issue by ManoylovAC** [nature-of-code/noc-book-2#652]
### Chapter 3. Oscillation has two **Figure 3.19**
> <img width="799" alt="image" src="https://github.com/nature-of-code/noc-book-2023/assets/6568745/fd604287-7116-43f1-943a-1afbc6025a58">
> 
**Seems like second one should be **Figure 3.22****
> <img width="788" alt="image" src="https://github.com/nature-of-code/noc-book-2023/assets/6568745/bda0c20a-16d2-43af-98a2-ea78ea7b0806">

https://github.com/nature-of-code/noc-book-2023/blob/087f32e0db54328f7e7ccd1ba0dc13298eb00b62/content/03_oscillation.html#L904
https://github.com/nature-of-code/noc-book-2023/blob/087f32e0db54328f7e7ccd1ba0dc13298eb00b62/content/03_oscillation.html#L976

**Comment by shiffman** [comment]
Fixed
