### ISSUE TITLE
Chapter 4. Typo?

### ISSUE THREAD

**Issue by ManoylovAC** [nature-of-code/noc-book-2#653]
Perhaps a comma is needed instead of a period.

> ![image](https://github.com/nature-of-code/noc-book-2023/assets/6568745/8e6b6ab0-7b8a-4f3b-aa82-5488bdfee210)

https://github.com/nature-of-code/noc-book-2023/blob/087f32e0db54328f7e7ccd1ba0dc13298eb00b62/content/04_particles.html#L981

**Comment by shiffman** [comment]
Fixed
