### ISSUE TITLE
Chapter 6. An unclear explanation for the new image

### ISSUE THREAD

**Issue by ManoylovAC** [nature-of-code/noc-book-2#654]
I guess that before the image and its left column were different from the current version, but the text was not changed, so now there may be some confusion.

> <img width="800" alt="image" src="https://github.com/nature-of-code/noc-book-2023/assets/6568745/a29d9927-3c52-46be-80ed-b847bf4d3d11">

It is also worth looking at the next part of the text, because it also refers to the old look of the image

> <img width="764" alt="image" src="https://github.com/nature-of-code/noc-book-2023/assets/6568745/9e7afb61-5b9f-4aca-a12e-da4ad5cb010f">

https://github.com/nature-of-code/noc-book-2023/blob/087f32e0db54328f7e7ccd1ba0dc13298eb00b62/content/06_libraries.html#L1659

**Comment by shiffman** [comment]
Proposed change:

"Now look at the connections listed in Figure 6.19."

will close once implemented

**Comment by shiffman** [comment]
all set
