### ISSUE TITLE
Chapter 10. Different values

### ISSUE THREAD

**Issue by ManoylovAC** [nature-of-code/noc-book-2#656]
In the code example shows value **0.01** but should be **0.0001** like in the text and p5 editor

> ![image](https://github.com/nature-of-code/noc-book-2023/assets/6568745/7f697ee6-6344-45cd-8128-a997b32e5d80)

https://github.com/nature-of-code/noc-book-2023/blob/087f32e0db54328f7e7ccd1ba0dc13298eb00b62/content/10_nn.html#L444

**Comment by shiffman** [comment]
Thank you for these! There is currently a proofreader going over the book and making fixes, I am tagging these with the `proofreader` label and will make sure they are addressed in the final round of updates before going to print!

**Comment by shiffman** [comment]
Fixed
