### ISSUE TITLE
Chapter 11. Wrong code in the p5 editor for Example 11.4

### ISSUE THREAD

**Issue by ManoylovAC** [nature-of-code/noc-book-2#657]
In the online code for `Example 11.4` the line with `glow.update();` lie outside of `for` loop

> <img width="726" alt="image" src="https://github.com/nature-of-code/noc-book-2023/assets/6568745/e284c5fc-5989-4449-86e3-0e288bfdce85">

> ![image](https://github.com/nature-of-code/noc-book-2023/assets/6568745/40ad6950-49a2-40da-83b5-2bc1fbcb8555)

It must be inside a `for` loop to work correctly, as shown in the book

> <img width="720" alt="image" src="https://github.com/nature-of-code/noc-book-2023/assets/6568745/a8cbb358-f6b9-45cf-b363-1de31d154694">

https://github.com/nature-of-code/noc-book-2023/blob/087f32e0db54328f7e7ccd1ba0dc13298eb00b62/content/11_nn_ga.html#L636

**Comment by shiffman** [comment]
oh! great catch! Fixed!
