### ISSUE TITLE
Chapter 0. Different links for web and pdf version of book

### ISSUE THREAD

**Issue by ManoylovAC** [nature-of-code/noc-book-2#658]
Not sure if it was intended, but the web- and pdf- versions of the book have different links. In the first case we have link to the "Classes in ES6" video, and in the second link — "Objects" section of "Programming with p5.js". 

As a proposal, page can keep single block and has only a general link to the “Objects” section.

https://github.com/nature-of-code/noc-book-2023/blob/087f32e0db54328f7e7ccd1ba0dc13298eb00b62/content/00_randomness.html#L65-L70

**Comment by shiffman** [comment]
This has been changed to use the same text across the PDF and web.
