### ISSUE TITLE
Elementary CA doesn't correctly implement "edges remain constant" (section 7.3/7.4)

### ISSUE THREAD

**Issue by sidwellr** [nature-of-code/noc-book-2#66]
In section 7.3, How to Program an Elementary CA, you choose option 1, "Edges remain constant", but don't implement it. When first describing how to use a second newcells array, the edge cells remain uninitalized. Later when adding the rules, you change the name to nextgen (a minor inconsistency, but you might want to use the same name throughout). In section 7.4 when you put everything together, you initialized nextgen to all 0 when you create it, which implements a different option: "Edges become 0". This is fine for your example since the edges start 0 and remain that way. But to correctly implement "Edges remain constant", you need to explicitly copy cells[0] and cells[cells.length-1] to newcells/nextgen.

**Comment by sidwellr** [comment]
Never mind. After looking at it again, I realized I just interpreted "Edges remain constant" differently. I perceived "Edges stay the same for each generation", but you meant "Edges are always a constant 0 or 1". But I'm leaving the issue open because it's a good practice to always initialize variables, which is not done in the chapter text, so code such as the following should be added either before or after the loop from 1 to cells.length-1:

// Set edges to the constant value 0
newcells[0] = 0;
newcells[newcells.length - 1] = 0;

**Comment by shiffman** [comment]
Hi there! I've rewritten Chapter 7 and I believe this is now covered (the arrays are always initialized with all 0s before the loops where the edges are ignored). If you'd like to take a look the new chapter is here:

https://nature-of-code-2nd-edition.netlify.app/cellular-automata/

**Comment by sidwellr** [comment]
Looks like you copied the array using slice(), which will initialize everything to what it was before, not 0. Now it behaves like I interpreted "Edges remain constant" the first time; the values get copied so remain the same for each generation. The difference is subtle and not worth pointing out. Looks good to me!
