### ISSUE TITLE
To set all URLs in italics

### ISSUE THREAD

**Issue by jasongao97** [nature-of-code/noc-book-2#664]
According to NSP style

> NSP style is to set all URLs in italics; is that possible to do? We would want only the URL to be italic, not the parentheses.

**Comment by shiffman** [comment]
Also, if possible investigate rules for allowing URLs to break across lines (maybe not possible)

> URLs that must break across lines should break without a hyphen, and they should break BEFORE periods, underscores, equal signs, ampersands, and hyphens but AFTER colons, slashes and hash marks.

**Comment by jasongao97** [comment]
Implemented!

**Comment by shiffman** [comment]
fantastic, thank you!
