### ISSUE TITLE
Page breaks/widows:

### ISSUE THREAD

**Issue by jasongao97** [nature-of-code/noc-book-2#665]
- to avoid a single line by itself.
- to avoid ending right-facing pages with a colon.

> Is it possible to avoid having one line of a paragraph alone at the top or bottom of a page? Generally, if a paragraph is three lines long, it should be kept together on the same page (to avoid a single line by itself). I've noted where text could be pushed to the next page, and I've noted single lines at the top of a page with the #widow tag.
Is it possible to avoid ending right-facing pages (odd-numbered pages) with a colon? If it's possible to push text to the next page, this would likely be the easiest fix.

**Comment by shiffman** [comment]
now applied via CSS
