### ISSUE TITLE
Keep numbers and their units together

### ISSUE THREAD

**Issue by jasongao97** [nature-of-code/noc-book-2#667]
e.g. Chapter 01 / y-- / 40 percent / y=x / Figure 1.7 / Algorithm 3 / Example 2.8 / 3 meters / 2 pixels / 45 degrees / (embedded code with parenthesis) / (x, y) / x-axis / y-position

<img width="693" alt="image" src="https://github.com/nature-of-code/noc-book-2023/assets/6762203/a0c33e98-736a-4328-b07d-67984b88bee3">

~Can we use underline (or another suitable notation) to indicate words that should not be separated by a line-break?~

**Comment by jasongao97** [comment]
@jasongao97 Try writing regex to match as much as we can.

**Comment by shiffman** [comment]
This needs to be double-checked, @shiffman to review pull request.

**Comment by jasongao97** [comment]
The implementation has been successfully completed and merged. Additional cases can be added in the future if needed.

**Comment by shiffman** [comment]
@jasongao97 I noticed in the latest build one instance of "Chapter 11" being broken across a page, I wonder if we can check this one? This might be an edge case so could go into a new issue, but re-opening this one in case that makes sense?

bottom of 451:
<img width="667" alt="Screen Shot 2024-02-09 at 9 05 45 AM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/0a7cfa98-d376-48c6-ab87-7a54559eb25d">

top of 452:
<img width="699" alt="Screen Shot 2024-02-09 at 9 05 52 AM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/139f188e-6fb5-4539-a36d-312713ad8e83">
