### ISSUE TITLE
Example / Codesplit boxes' bug

### ISSUE THREAD

**Issue by jasongao97** [nature-of-code/noc-book-2#669]
> I suggest closing the top and bottom of these boxes when they break across pages. Currently sometimes they are closed, and sometimes they aren't. Gray shading sometimes overlaps the exercise border. Is it possible to make the outer border solid/unbroken? We've circled where this happens in the PDF.

**Comment by shiffman** [comment]
Also, if it closes but continues we should probably not have it be rounded? cc @tuantinghuang 

<img width="776" alt="Screen Shot 2024-01-29 at 9 01 29 AM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/547e1ef4-32fd-4898-9eb5-c30706ba52f2">

**Comment by shiffman** [comment]
top and bottom should not have rounded corners and we should use the dotted line when broken across pages.

Should we also have scissors?

**Comment by shiffman** [comment]
@jasongao97 and @tuantinghuang to be discussed in our meeting tomorrow.

> When a code listing breaks across a page, I suggest not using the dashed line, as it may get confused with the dashed line that appears with the scissors. I also suggest closing all sides of example boxes that break across pages with a solid line, if that's possible and if you'd be open to that. That's how we typically treat boxes that break across pages in our standard template.

**Comment by shiffman** [comment]
We've decided to have no separate line across any code block that breaks between pages b/c the grey background already serves that purpose. However, any code block that is broken should not have rounded bottom or top at the break. However, @jasongao97 has to investigate whether this is possible in terms of how this break is happening in the prince PDF generation. Here's an example of the bug:

<img width="1728" alt="Screen Shot 2024-02-06 at 10 02 27 AM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/8aa339eb-07ed-49b5-acfa-346bebb6e66a">

**Comment by shiffman** [comment]
Looks great! Will open new issues as they arise in the next round.
