### ISSUE TITLE
Code comments

### ISSUE THREAD

**Issue by jasongao97** [nature-of-code/noc-book-2#670]
- Editor suggest using a new font for the code/literal terms
- Several locations missing the `code` style
- $Math$ in comments

**Comment by shiffman** [comment]
* DS: keep font for code but maybe @tuantinghuang can experiment with weight as an option
* DS: tell production that can enter the backticks for code style
* @jasongao97 will try adding $$ for math

**Comment by shiffman** [comment]
@jasongao97 there is only the one spot in the book where there is a math formula I think I can just edit the comment not to include it.  Removing you as assigned to this issue, adding @tuantinghuang to consider any adjustments to weight or size of the code font in comment.

Reminder for me:
![Screen Shot 2024-01-30 at 2 50 07 PM](https://github.com/nature-of-code/noc-book-2023/assets/191758/76a8bc7b-20e1-4e24-9119-4f81f38cf865)

**Comment by shiffman** [comment]
Edited out the formulas

**Comment by tuantinghuang** [comment]
here are a couple of mockups with bolded code comments

**example 1**
bolded
![bolded](https://github.com/nature-of-code/noc-book-2023/assets/90000947/84bf8d82-66e8-4ec6-bfd6-cadc9fd09f95)

original
<img width="1033" alt="Screenshot 2024-02-06 at 08 22 38" src="https://github.com/nature-of-code/noc-book-2023/assets/90000947/3ae6610b-49da-42a8-a885-ecf7cc2810ec">


**example 2**
bolded
![bolded-2](https://github.com/nature-of-code/noc-book-2023/assets/90000947/401a3d39-5f8a-48f1-94e5-6b1dcef23b05)

original
![not-bolded-2](https://github.com/nature-of-code/noc-book-2023/assets/90000947/279c4d55-3930-4d86-9562-6100218d60f1)

**Comment by shiffman** [comment]
changing it to bold, confirm with no starch.
