### ISSUE TITLE
Ecosystem Project page arrangement

### ISSUE THREAD

**Issue by jasongao97** [nature-of-code/noc-book-2#671]
## Chapter 0:

<img width="1028" alt="image" src="https://github.com/nature-of-code/noc-book-2023/assets/6762203/5b1e17dc-9e93-4275-bf78-308b5a81ceb9">

## Chapter 1:

<img width="1453" alt="Pasted Graphic 3" src="https://github.com/nature-of-code/noc-book-2023/assets/6762203/56fba596-d096-479e-84cf-4ad3ccae8633">

**Comment by shiffman** [comment]
DS: Rewrite chapter 0 so that it fits in one page

The rest I think we have to leave as is (for now)

**Comment by shiffman** [comment]
I completed moving the paragraph outside.

**Comment by shiffman** [comment]
Leaving open to double-check in the next PDF build.

**Comment by shiffman** [comment]
@jasongao97 let's revert to not letting the ecosystem project break across 2 pages.

**Comment by jasongao97** [comment]
Reverted!
