### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by jasongao97** [nature-of-code/noc-book-2#672]
TBD:

- Acknowledgement / Introduction start on right-side page
- Add page numbers to the front matter pages

> Acknowledgments will begin on p. xvii
> the intro will begin on page xxiii
> Chapter 0 will start on Arabic numeral page 1

Question: While there is also a comment regarding the removal of page numbers on blank pages, which seems to be in contradiction with the numbers provided for the Acknowledgments/Introduction page.

**Comment by shiffman** [comment]
DS: ask production to confirm page # is not rendered but still counted on blank pages.

**Comment by shiffman** [comment]
@jasongao97 just noting here that we confirmed page numbers are not rendered but are counted for blank pages. This relates to #726

**Comment by shiffman** [comment]
Thanks for finalizing this @jasongao97!!
