### ISSUE TITLE
Page cross reference

### ISSUE THREAD

**Issue by jasongao97** [nature-of-code/noc-book-2#673]
There are various appearances throughout the pdf:

- hard-coded number, e.g. on page 135, on page XX
- correctly auto-generated number for **a specific block** (example / headings), e.g. (see page 100)
- wrongly generated number for **a chapter**, e.g. in Chapter 1 (see page 1)

**Comment by shiffman** [comment]
- Remove all page references for chapters (either by ignoring in the build or taking out the links in Notion)
- Every other page reference should be switched to be automated

**Comment by jasongao97** [comment]
> Every other page reference should be switched to be automated

I've modified all the hard-coded page number to block references in notion.
To be check in the next build.

**Comment by shiffman** [comment]
leaving open in case no starch wants to suggest other places for page references and to double check the existing ones.

**Comment by shiffman** [comment]
Closing, will address any new issues as needed
