### ISSUE TITLE
caption layout design?

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#674]
NS: "consider placing caption directly under the image."

<img width="1231" alt="Screen Shot 2024-01-29 at 8 49 47 AM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/9cf70cb4-d028-4f6d-b082-82062d0c872e">

I'm good with keeping this design but noting this comment @tuantinghuang for consideration.

**Comment by shiffman** [comment]
Keep design as is

**Comment by shiffman** [comment]
New proposal is to do away with the "title itself" and have that become the caption, it is usually redundant anyway. For example, for chapter 2 instead of the following:

<img width="696" alt="Screen Shot 2024-02-05 at 7 52 42 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/ffa918cc-1d0b-4097-98c1-a479c7b20b54">

We would have (excuse the crude mock-up). @tuantinghuang what do you think? 

<img width="696" alt="Screen Shot 2024-02-05 at 7 52 42 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/06ba46e7-75eb-4bdd-b042-59a0325c63e6">

**Comment by tuantinghuang** [comment]
I think it make sense to replace the title with captions! I tried several mockup too, with the title having the same font size as the copy but bolded - 

<img width="669" alt="Screenshot 2024-02-06 at 08 15 22" src="https://github.com/nature-of-code/noc-book-2023/assets/90000947/2790a790-9772-4693-a44e-d8267cf97346"></br>

<img width="680" alt="Screenshot 2024-02-06 at 08 14 13" src="https://github.com/nature-of-code/noc-book-2023/assets/90000947/02f1a24b-e425-4b6b-b433-a12e7eec352d"></br>

<img width="688" alt="Screenshot 2024-02-06 at 08 14 32" src="https://github.com/nature-of-code/noc-book-2023/assets/90000947/1ff09df6-a64b-4620-a6a1-2b3f2733eed9"></br>

**Comment by shiffman** [comment]
First step: @jasongao97 to adjust the build process, use Chapter 2 as example (it's adjusted in Notion)

**Comment by shiffman** [comment]
#736 has the new captions so the PDF rendering may break in weird ways until this is implemented.

**Comment by shiffman** [comment]
new design looks great!
