### ISSUE TITLE
chapter 1 opening image

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#675]
> DES: Possible to increase contrast slightly? Perhaps lighten the background so that image will not be muddy and flat when printed.

<img width="1231" alt="Screen Shot 2024-01-29 at 8 49 47 AM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/7f8d3f9e-894c-4bde-a2b5-4970cd515a42">

**Comment by tuantinghuang** [comment]
Fixed!

<img width="726" alt="Screenshot 2024-02-06 at 01 05 34" src="https://github.com/nature-of-code/noc-book-2023/assets/90000947/a1e8814a-ac81-47a9-a400-c27629e5f7d5">
