### ISSUE TITLE
chapter 2 opening image

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#677]
> DES: Adjust contrast and open up highlights? Looks a bit muddy.

<img width="659" alt="Screen Shot 2024-01-29 at 8 56 02 AM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/e214872e-3620-4de0-944d-15360585cfe7">

**Comment by tuantinghuang** [comment]
Fixed!

<img width="674" alt="Screenshot 2024-02-06 at 01 06 19" src="https://github.com/nature-of-code/noc-book-2023/assets/90000947/df29e10b-0fca-49ff-97ec-b298da6abb59">

**Comment by shiffman** [comment]
looks great!
