### ISSUE TITLE
Figure 3.17 lower case "c"

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#680]
"class" should be lower case c in both places:

<img width="696" alt="Screen Shot 2024-01-29 at 9 06 35 AM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/2bac2105-786f-4ae9-9761-eb8dc9c01de9">

**Comment by zee-em** [comment]
updated and uploaded

**Comment by shiffman** [comment]
The "Class" in "Spring Class" is still upper case in the image, it also needs to be lower case!

**Comment by zee-em** [comment]
oops! fixed and uploaded

**Comment by shiffman** [comment]
all set now, thank you!!
