### ISSUE TITLE
Quote Styles

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#687]
There were several comments about the design of block quotes in the book.  @tuantinghuang can you take a look and propose a solution / finalize in Notion? This is what I think.

(1) I'm fine with changing, but I think maybe it should just stay like the block quotes (3) (4)
(2) open to any solution
(3) open to any solution
(4) should not match p.74 design but be a block quote design (italic or no italic?)
(5) should not match p.74 design but be a block quote design (italic or no italic?)

Here are screenshots of the five items.

(1) Acknowledgements:
Comment: "style this quote the same way as the epigraphs on the chapter openers? Since this quote is much longer, I'd suggest using at least italics for the quotation and then right-aligning the source line"
<img width="730" alt="Screen Shot 2024-01-30 at 2 19 13 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/f23a2693-004b-4b88-b649-494416cbd79b">

---------
(2) Comment: DES: this should have the same styling as the quotes on p. 74 (see reference below)
<img width="716" alt="Screen Shot 2024-01-30 at 2 23 00 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/d427e4b8-cb88-491c-8d11-135bd8c5bbb4">

(3) Comment: DES: see styling of similar element on p. 74 (see reference below)
<img width="746" alt="Screen Shot 2024-01-30 at 2 25 16 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/6fc384bd-4d67-4719-84b6-2696bfe4fa04">

(4) Comment: DES: block quotes need consistent styling; use same style as on p. 74? 
<img width="721" alt="Screen Shot 2024-01-30 at 2 26 32 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/5f97da4a-bf1e-46de-9abe-19b47fe8e71c">

(5) Comment: DES: use consistent styling for block quotes
<img width="737" alt="Screen Shot 2024-01-30 at 2 27 43 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/2c9c272d-1e0b-4059-858d-ce492053f718">

--------
Page 74 visual reference (these aren't quotes so I'm not sure the comments make sense):

<img width="731" alt="Screen Shot 2024-01-30 at 2 21 26 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/bb59a375-2134-4fa6-9dae-bc2598100c95">
-----

**Comment by tuantinghuang** [comment]
I'm more inclined to (5), which is with an indentation and italic, as the italic aligns more with the style of our chapter opening quotes. I also agree that the quote styles should not match p74.

Screenshots of advised versions:
(1) I'm not sure how to approach the right aligning source line, but we can discuss about this more during the meeting!
<img width="664" alt="Screenshot 2024-02-06 at 01 08 54" src="https://github.com/nature-of-code/noc-book-2023/assets/90000947/edbc57fb-01fd-41fa-99ad-fc072520d132">

(2) Question: Should the code `velocity` also be italic?
<img width="656" alt="Screenshot 2024-02-06 at 01 10 03" src="https://github.com/nature-of-code/noc-book-2023/assets/90000947/197e92ab-4893-4a8d-a105-f9daec88b3f1">

(3) 
<img width="646" alt="Screenshot 2024-02-06 at 01 11 03" src="https://github.com/nature-of-code/noc-book-2023/assets/90000947/6f669a9d-3836-4661-a6a2-ce2fa54ec1d7">

(4)
<img width="649" alt="Screenshot 2024-02-06 at 01 11 30" src="https://github.com/nature-of-code/noc-book-2023/assets/90000947/8f41179d-f3e3-4de1-a60f-c6a354fdcdd5">

(5)
<img width="631" alt="Screenshot 2024-02-06 at 01 12 03" src="https://github.com/nature-of-code/noc-book-2023/assets/90000947/963bcc54-6869-4c46-9b71-5a77acf2b700">

**Comment by shiffman** [comment]
These look great! Left a comment about the right aligning in Notion for no starch.
