### ISSUE TITLE
Fix placement of URLs

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#688]
This is a list of URLs that are rendering in incorrect or duplicate spots in the book text.

![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/06d4f05b-d52f-46e7-8035-68b4929aba89)

![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/065d098e-9839-4961-8b12-866d2964e936)

![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/a5328ba7-99ad-4a2d-adc9-8e4c42675a3a)

---

https://academic.oup.com/jrssig/article/18/6/26/7038520
![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/fc0e2925-ff8b-4f08-a262-afd5ad09d431)

---

Move url to after author names:
![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/9e917b2e-7c0a-4437-bb62-a7803b1464b3)

---

Period should be after the url:
![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/194a6376-92f5-4f51-a281-c2d7397b5829)

---

URL placed after authors names:
![Screen Shot 2024-01-30 at 2 55 05 PM](https://github.com/nature-of-code/noc-book-2023/assets/191758/477a8c3f-067e-4aef-bdef-0e32880a5738)

**Comment by shiffman** [comment]
Corrected these, need to check in next PDF build.

**Comment by shiffman** [comment]
These got all messed up again due to but in #643 but I'm applying a temporary workaround fix. @jasongao97 let's discuss this at our next meeting.

**Comment by shiffman** [comment]
They are all working now, will leave open just to discuss the weird notion bug but low priority since it renders correctly.

**Comment by jasongao97** [comment]
I've added the **join** post-process. It should be fixed now.

**Comment by shiffman** [comment]
oh amazing! We can go back and re-link them in Notion, I'll leave this open as a reminder for me to do that.

**Comment by shiffman** [comment]
Changed in Notion, will double-check rendering in next PDF build.

**Comment by shiffman** [comment]
These are all working great now.
