### ISSUE TITLE
Code comment placement bug?

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#694]
This comment appears in a strange spot, can it easily be moved a little higher?

![Screen Shot 2024-01-30 at 2 55 55 PM](https://github.com/nature-of-code/noc-book-2023/assets/191758/554b435c-6ed0-4d28-b094-2a5141876ce7)

**Comment by shiffman** [comment]
Here's another that is placed a bit higher than it needs to be?

![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/a372f6ab-b1ea-4204-8d77-1d5ae605b6db)

**Comment by shiffman** [comment]
Maybe we can fix these by manually creating two separate comments (one for the first line, another "blank" one for the rest)

**Comment by jasongao97** [comment]
Great! I'll add the solution as below. The `.continue` class will remove the top border which was for separating the pairs.

```js
  //{!4} Train the network against known data.
  train(inputs, desired) {
    let guess = this.feedforward(inputs);
    let error = desired - guess;
    for (let i = 0; i &#x3C; this.weights.length; i++) {
      //{!3.continue}
      this.weights[i] = this.weights[i] + error * inputs[i] * this.learningConstant;
    }
  }
```

<img width="707" alt="image" src="https://github.com/nature-of-code/noc-book-2023/assets/6762203/2cec3d82-19fe-49da-8140-a146d7416d2b">

**Comment by jasongao97** [comment]
> Before
> <img width="731" alt="image" src="https://github.com/nature-of-code/noc-book-2023/assets/6762203/7c9e6af6-0f6c-49c5-b09d-f92099f9527a">

In this case, the comment would be higher than the 2 lines of code. So I am thinking of adding another class `bottom-align` to make the top section bottom aligned, which rendered as:

```js
  //{!2.bottom-align} Draw the spring connection between the bob position and the anchor.
  showLine(bob) {
    stroke(0);
    //{!2.continue}
    line(bob.position.x, bob.position.y, this.anchor.x, this.anchor.y);
  }
```

<img width="704" alt="image" src="https://github.com/nature-of-code/noc-book-2023/assets/6762203/e0069283-317b-42fc-a0b9-1f12f9c27b41">

How do you feel about this? @shiffman

**Comment by shiffman** [comment]
This looks great! I'm flexible, I think either way is an improvement, happy to add these `.continue` and `.bottom-align` classes!

**Comment by jasongao97** [comment]
The fix is added! I believe there are some other places that could potentially benefit from this as well. Would you consider this an improvement? 🤔

> Before
> 
> <img width="987" alt="If they ore both particies" src="https://github.com/nature-of-code/noc-book-2023/assets/6762203/10241b44-94dd-4904-95a5-55ee1e0209eb">

> After
> ```js
>     //{!1}
>     if (particleA instanceof Particle &#x26;&#x26; particleB instanceof Particle) {
>       //{!3.continue.bottom-align} If they are both particles, change their color!
>       particleA.change();
>       particleB.change();
>     }
> ```
> <img width="978" alt="Pasted Graphic 1" src="https://github.com/nature-of-code/noc-book-2023/assets/6762203/8f9cdfe7-5e98-4a61-ab3f-a2230ba8dde9">

**Comment by shiffman** [comment]
Yes, I think anywhere where we reduce the vertical space that the code takes up is good to do!!

**Comment by shiffman** [comment]
Close this issue and we can re-open issues for any new individual comment placement questions.
