### ISSUE TITLE
Code comment backtick bug?

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#705]
Something went wrong here (chapter 8)

![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/23fb79b0-48dd-4f76-91a2-79dfcff68b94)

**Comment by shiffman** [comment]
Another issue in chapter 10, maybe has to do with being bolded?

![Screen Shot 2024-01-30 at 3 18 40 PM](https://github.com/nature-of-code/noc-book-2023/assets/191758/b3796120-a208-4926-87f7-a0ea5afba72a)

**Comment by jasongao97** [comment]
Both fixed and checked.
