### ISSUE TITLE
Table bug

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#706]
line break about first A->AB before B->A

![Screen Shot 2024-01-30 at 3 16 59 PM](https://github.com/nature-of-code/noc-book-2023/assets/191758/0afbd9bb-0830-45e0-a0fe-b63e0d50329f)

this is working correctly in an earlier table

**Comment by jasongao97** [comment]
<img width="528" alt="image" src="https://github.com/nature-of-code/noc-book-2023/assets/6762203/d14c7204-55e0-4dec-b4d4-0d9927616b21">

Added in the same way as in #610. Will check in the next build.

**Comment by jasongao97** [comment]
Checked!
