### ISSUE TITLE
Add vertical padding to Figure 8.20?

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#707]
![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/0f35520c-d7ba-41fd-953f-49d5a65f43a5)

maybe wait and see what happens with #706 first

**Comment by shiffman** [comment]
@jasongao97 to check on CSS otherwise we'll just add some padding to the pixels of the image directly

**Comment by jasongao97** [comment]
Adding the extra padding will make the image flow to the next page. May I apply this change now and keep this tracked as a general content balancing issue in the next step?

<img width="1085" alt="image" src="https://github.com/nature-of-code/noc-book-2023/assets/6762203/bf71ed40-4e39-4b4c-92c4-aa15c641c60b">

**Comment by shiffman** [comment]
yes, go ahead, we can finesse it later. Also, if it turns out the layout works best with keep A->AB, B->A on the same line with a comma, we could also go back to that.
