### ISSUE TITLE
Formulas not indented?

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#709]
Can you check why this is @jasongao97? I believe others through the book are indented. This is chapter 10.

![image](https://github.com/nature-of-code/noc-book-2023/assets/191758/caacd8b6-da9f-4842-a18f-8a3a7f29c53e)

**Comment by jasongao97** [comment]
These were inline-level formulas. I have converted them to block-level and will check in the next build.

**Comment by jasongao97** [comment]
Checked!
