### ISSUE TITLE
Validation Error when importing from Notion

### ISSUE THREAD

**Issue by jasongao97** [nature-of-code/noc-book-2#71]
I got this API error message in both local and Github action environments. But it's gone after 10 minutes. It may be because I'm also editing that Notion database page. I'm saving it here for future references.

<img width="701" alt="Screen Shot 2022-08-22 at 2 42 54 PM" src="https://user-images.githubusercontent.com/6762203/185995396-1050844e-a778-4c25-810b-b71b9e5ab354.png">

**Comment by shiffman** [comment]
@jasongao97 is this resolved?

**Comment by shiffman** [comment]
Closing, not an issue anymore!
