### ISSUE TITLE
Figures 5.32 and 5.33

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#712]
For layout purpose and to help clarify, what do you think about the following changes?

Figure 5.32: instead of a gray second vehicle let's change it to the strawberry, I'm explaining separation as away from a "target" and the secondary vehicle pointing towards the main vehicle seems important whereas it is not.

![Screen Shot 2024-01-30 at 3 35 10 PM](https://github.com/nature-of-code/noc-book-2023/assets/191758/56c2e2d2-1bd4-4feb-ac46-50236520a3e4)

Figure 5.33: It'l fit into the spot where it goes better if we remove the text inside the figure ("desired velocity =- average of three fleeing vectors") I can explain that in the caption. Alternatively we could make it full width?

![Screen Shot 2024-01-30 at 3 36 13 PM](https://github.com/nature-of-code/noc-book-2023/assets/191758/b23b688a-1e8b-4edd-862c-51911981f9c5)

**Comment by zee-em** [comment]
updated and uploaded both to notion :)

**Comment by shiffman** [comment]
looking good!
