### ISSUE TITLE
Example 6.3 and Figure 8.8 recapture?

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#719]
@tuantinghuang can you help recapture these two? 

(No starch notes that 8.8 is fine, but maybe it's worth doing a nicer, higher-res line, I don't feel strongly either way.)

**Comment by tuantinghuang** [comment]
Recaptured!

Example 6.3
<img width="923" alt="Screenshot 2024-02-06 at 01 12 55" src="https://github.com/nature-of-code/noc-book-2023/assets/90000947/516e9340-3881-4886-9ac9-f63eccdf8013">

Figure 8.8
<img width="863" alt="Screenshot 2024-02-06 at 01 13 35" src="https://github.com/nature-of-code/noc-book-2023/assets/90000947/c1de0dcf-25ad-4060-b5d2-6de35ddb6bb5">
