### ISSUE TITLE
headers and footers change

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#726]
Waiting for clarification on this, last adjustments for header and footer

> only running feet, with the chapter number on the bottom left, chapter title on the bottom right, and the page number

**Comment by shiffman** [comment]
I got clarification regarding the footer (we can remove the header entirely).

Bottom Left: 
Page #     Chapter #

Bottom Right (right-aligned):
Chapter Title     Page #

There should be some padding between the page number and chapter number. Here is an example:

```
22        Chapter 2                                                               Forces 23
```

Here is a screenshot of another book of theirs for reference:

<img width="1227" alt="Screen Shot 2024-02-06 at 12 03 16 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/c35d86ec-5b82-46b9-bf1d-cb19318263d4">

Tagging in @tuantinghuang for any design thoughts.

**Comment by jasongao97** [comment]
@shiffman Thank you for the information! I just need a bit more clarification on the other pages. please let me know if my following understanding is correct.

- Acknowledgments: only shows page number
  ```
  xx                                                      xxi
  ```
- Introduction: left and right pages both show 'Introduction' with page numbers
  ```
  xxiv  Introduction                        Introduction  xxv
  ```
- Chapter 0 - 11
  ```
  22  Chapter 2                                    Forces  23
  ```
- Appendix: nothing
- Every first page omit the chapter name

**Comment by shiffman** [comment]
As specified by no starch!

- Acknowledgments: please use the page number plus the word Acknowledgments in the footer
- Introduction: as you have it is correct (page number + the word Introduction)
- Chapters: as you have it is correct
- Appendix: please use the page number plus the word Appendix in the footer
- Blank pages: correct, nothing

**Comment by shiffman** [comment]
re-assigning to myself to double-check

**Comment by shiffman** [comment]
Looking good!
