### ISSUE TITLE
Wrong values in code under example 5.1

### ISSUE THREAD

**Issue by pie999** [nature-of-code/noc-book-2#753]
In the code under example 5.1 the values for this.maxforce and this.maxspeed are switched compared to the original p5js sketch.

https://github.com/nature-of-code/noc-book-2023/blob/4952081d64038a56b84cc9715faf3216939d8d06/content/05_steering.html#L170-L171

**Comment by shiffman** [comment]
Great catch! Fixed in Notion, will be in the next build.
