### ISSUE TITLE
Example 0.1 and 6.4 formatting

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#763]
Example 0.1 probably needs its own design (with the paragraph of text) and 6.4 is maybe a rendering bug?

<img width="705" alt="Screen Shot 2024-02-12 at 12 42 49 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/b37a720a-a184-41c7-ba94-1962e6c248a9">

<img width="678" alt="Screen Shot 2024-02-12 at 1 27 00 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/44bab2f3-bb13-4928-90c2-466afe0865e2">

**Comment by jasongao97** [comment]
<img width="744" alt="image" src="https://github.com/nature-of-code/noc-book-2023/assets/6762203/903696a6-5c70-4753-8edb-32f8189770fc">

Our current approach is to join the example to the adjacent code snippet. Switching the hierarchy from

```
- Example
  - Codesplit
```

to

```
- Example
- Codesplit
```

should resolve this.

**Comment by jasongao97** [comment]
<img width="712" alt="image" src="https://github.com/nature-of-code/noc-book-2023/assets/6762203/3123ef9f-f4aa-493e-9b04-969c67f29cd5">

<img width="753" alt="image" src="https://github.com/nature-of-code/noc-book-2023/assets/6762203/3abd7603-591f-46f4-8640-b19bd383c78b">

Updated in Notion and fixed the styles. Although I am not sure about the design of the scissors in this case. How do you think of this? @shiffman @tuantinghuang

**Comment by shiffman** [comment]
leaving open to check Example 6.4 in next PDF render

**Comment by shiffman** [comment]
These are fixed!
