### ISSUE TITLE
Inconsistent variable name in example 5.12

### ISSUE THREAD

**Issue by pie999** [nature-of-code/noc-book-2#767]
In the showcase code in example 5.12 the number of columns is first defined as `cols` 
https://github.com/nature-of-code/noc-book-2023/blob/421ce887656583f7f181ffd4e844ee32d7398bbe/content/05_steering.html#L1430
and it's the variable name used in two for loops later in the code
https://github.com/nature-of-code/noc-book-2023/blob/421ce887656583f7f181ffd4e844ee32d7398bbe/content/05_steering.html#L1438
https://github.com/nature-of-code/noc-book-2023/blob/421ce887656583f7f181ffd4e844ee32d7398bbe/content/05_steering.html#L1448
but then `columns` is used for constraining
https://github.com/nature-of-code/noc-book-2023/blob/421ce887656583f7f181ffd4e844ee32d7398bbe/content/05_steering.html#L1460
https://github.com/nature-of-code/noc-book-2023/blob/421ce887656583f7f181ffd4e844ee32d7398bbe/content/05_steering.html#L1477

**Comment by shiffman** [comment]
Fixed! Went with just using "cols" since that is the naming convention for the flowfield examples. Will double-check in the next build.

**Comment by shiffman** [comment]
all set
