### ISSUE TITLE
Ignored argument in flocking with binning example

### ISSUE THREAD

**Issue by pie999** [nature-of-code/noc-book-2#768]
In the code for the flocking with binning example, in the run method of the Flock class this.boids is passed as an argument to boid.run(), but the run method of the Boid class doesn't have any parameters since it's using the global grid variable.
https://github.com/nature-of-code/noc-book-2023/blob/421ce887656583f7f181ffd4e844ee32d7398bbe/content/examples/05_steering/example_5_9_flocking_with_binning/flock.js#L15-L19
https://github.com/nature-of-code/noc-book-2023/blob/421ce887656583f7f181ffd4e844ee32d7398bbe/content/examples/05_steering/example_5_9_flocking_with_binning/boid.js#L17-L34

**Comment by shiffman** [comment]
Fixed!
