### ISSUE TITLE
Internal X-Refs

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#778]
(I'll come back and add more detail later, but we need things like "In Chapter 3" to link to chapter 3 in the digital PDF.

**Comment by jasongao97** [comment]
Shall we use a regular expression for matching, or manually add them into Notion? It's worth mentioning that in certain contexts, jumping directly to the start of a chapter might not be ideal, for example:

<img width="542" alt="image" src="https://github.com/nature-of-code/noc-book-2023/assets/6762203/bc59dee7-306f-4a10-91c8-135aa074e10f">

**Comment by jasongao97** [comment]
Feature added in #881 and https://github.com/nature-of-code/fetch-notion/pull/28.

@shiffman May I start adding page reference in Notion? Is there a rule to follow?

**Comment by shiffman** [comment]
@jasongao97 what is your preference in terms of adding them manually in notion vs. detecting? Either way would work for me.

**Comment by shiffman** [comment]
Need to do a pass to link all of the spots in Notion.

**Comment by shiffman** [comment]
@jasongao97 I think we can close this issue? We can open new issues as references are needed?

**Comment by shiffman** [comment]
This can be closed!
