### ISSUE TITLE
Allow urls to break at https:// ?

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#781]
![Screen Shot 2024-02-23 at 6 52 58 PM](https://github.com/nature-of-code/noc-book-2023/assets/191758/398b26ad-fdd5-4306-9830-353f289df9d3)

> could part of this URL (http://) fit on the previous line to help avoid the short word on the last line of the paragraph?

**Comment by shiffman** [comment]
Solution propose for this and #789 is to add manual breaks (SHIFT-ENTER) in Notion and then style those for the PDF only.

**Comment by jasongao97** [comment]
I just realized that the URL is added during the build process, so we can not add manual breaks. Will think about another solution later.

**Comment by shiffman** [comment]
That makes sense, this is very low priority and fine to leave out, shall we just close it?

**Comment by jasongao97** [comment]
> That makes sense, this is very low priority and fine to leave out, shall we just close it?

I think this could be potentially fix with #666. Shall we keep it open for a little while longer?

**Comment by shiffman** [comment]
Ok, will do!

**Comment by shiffman** [comment]
I'm going to close this, I think we leave as is, adding manual `<br>` tags is working best for #666
