### ISSUE TITLE
Opening Image Caption Formatting

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#783]
The opening image caption is not picking up the italic formatting from Notion—italics in this case.

Notion:
<img width="808" alt="Screen Shot 2024-02-24 at 9 45 59 AM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/a73191af-39e8-46fe-9932-f2d9147952a3">

PDF:
<img width="736" alt="Screen Shot 2024-02-24 at 9 46 56 AM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/c943212a-6cc4-4436-9b22-f1b1e1e1c938">

**Comment by shiffman** [comment]
Also chapter 2
<img width="787" alt="Screen Shot 2024-02-24 at 10 20 22 AM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/8ab1ffbb-6fa4-46a3-9a7e-d0d4178d2596">

**Comment by jasongao97** [comment]
The fix is merged! Leaving open to check.

**Comment by shiffman** [comment]
Looking good!
