### ISSUE TITLE
new paragraph bug?

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#784]
Not starting a new paragraph in Coding Conventions callout box in Chapter 0.

PDF:
![Screen Shot 2024-02-24 at 9 48 47 AM](https://github.com/nature-of-code/noc-book-2023/assets/191758/ad17e35b-3f29-4f14-b06e-7e410287dedd)

Notion:
<img width="789" alt="Screen Shot 2024-02-24 at 9 49 35 AM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/ee84e3c6-11ab-41ff-854d-ce5b558e3f41">

**Comment by jasongao97** [comment]
It was a line-break instead of a separate paragraph in Notion. Fixed!

**Comment by shiffman** [comment]
Leaving open b/c I might move the callout box since it changed the flow.

**Comment by shiffman** [comment]
Should be all set now with #854
