### ISSUE TITLE
Custom page reference

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#787]
Can we customize this particular page reference to read:

> (See "The Random Walker class on page 3 for a brief review of OOP basics.)

![Screen Shot 2024-02-24 at 10 10 02 AM](https://github.com/nature-of-code/noc-book-2023/assets/191758/43215092-2823-474f-8ab8-c2c0cea1ebfa)

**Comment by shiffman** [comment]
Another place where we need "on page 26" to avoid parentheses in parentheses.

![Screen Shot 2024-02-24 at 10 22 45 AM](https://github.com/nature-of-code/noc-book-2023/assets/191758/9b4d980a-d651-4ea2-99d6-25be7e77776d)

**Comment by shiffman** [comment]
Another in Chapter 3

> "The Pendulum" on page 158, 

![Screen Shot 2024-02-24 at 11 24 52 AM](https://github.com/nature-of-code/noc-book-2023/assets/191758/17c6e089-3548-46d0-ae93-e5304f10077f)

**Comment by shiffman** [comment]
I guess there are a lot of these. Here's one for Chapter 5.

> "Combining Behaviors" on page 269),


![Screen Shot 2024-02-24 at 1 00 37 PM](https://github.com/nature-of-code/noc-book-2023/assets/191758/8383a6ae-ff3b-4bd3-81dd-63e015468ed9)

**Comment by shiffman** [comment]
Another in Chapter 6.

> ...see "Other Physics Libraries" on page 294 for alternatives...

![Screen Shot 2024-02-24 at 2 49 21 PM](https://github.com/nature-of-code/noc-book-2023/assets/191758/0370c3aa-66f8-4b52-82f7-f21760aca359)

**Comment by shiffman** [comment]
One more in chapter 11!

> "Speeding Up Time" on page 578.)

![Screen Shot 2024-02-24 at 9 38 56 PM](https://github.com/nature-of-code/noc-book-2023/assets/191758/cc2c1e43-6e17-4c03-a8c6-cf63d2b9307d)

**Comment by shiffman** [comment]
Let's change them all to "on page ##" without parentheses.

**Comment by jasongao97** [comment]
The update is merged!

**Comment by shiffman** [comment]
Leaving open until no starch approves this global change (but looks good in the PDF!)

**Comment by shiffman** [comment]
This is approved by no starch.
