### ISSUE TITLE
No page references for Chapter references

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#788]
Not sure why this one appeared?

![Screen Shot 2024-02-24 at 10 11 44 AM](https://github.com/nature-of-code/noc-book-2023/assets/191758/b5e4ad4e-78a8-47a9-83ef-3fd313386b04)

**Comment by jasongao97** [comment]
Removed in Notion

**Comment by shiffman** [comment]
I will double check but also noting that it eventually will need #778

**Comment by shiffman** [comment]
This one is fixed
