### ISSUE TITLE
Exception to number and unit "keep together"

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#789]
From no starch:

> it would be OK to separate the number from its unit in this case to avoid the hole 

![Screen Shot 2024-02-24 at 10 12 35 AM](https://github.com/nature-of-code/noc-book-2023/assets/191758/0320d292-1c5e-4b11-a515-82dc7e80c526)

**Comment by shiffman** [comment]
Another one in Chapter 2.

![Screen Shot 2024-02-24 at 10 21 55 AM](https://github.com/nature-of-code/noc-book-2023/assets/191758/b37a4a8f-13d0-42f7-b449-f51100b87d3a)

**Comment by jasongao97** [comment]
<img width="508" alt="image" src="https://github.com/nature-of-code/noc-book-2023/assets/6762203/d20077c3-2c36-468d-b2a9-3a770f48173a">

<img width="495" alt="image" src="https://github.com/nature-of-code/noc-book-2023/assets/6762203/0a5b0980-6796-4e39-9010-17538f2e1de7">

Merged and working great! Closing

**Comment by shiffman** [comment]
Great! This could also potentially be a solution for other orphans, but I can wait and see what happens with #666
