### ISSUE TITLE
line breaks chapter 4 opening quote

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#796]
Not sure why these line breaks aren't being used, did I format this incorrectly? @tuantinghuang I recall you were working on this at one point?

Notion:
<img width="854" alt="Screen Shot 2024-02-24 at 11 41 10 AM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/8ce92181-bc97-4db7-adfd-fb21fed88707">

PDF:
![Screen Shot 2024-02-24 at 11 40 59 AM](https://github.com/nature-of-code/noc-book-2023/assets/191758/bf164d38-ed52-4cf7-af8f-dcb054d8663a)

**Comment by jasongao97** [comment]
Update to separated paragraphs! Fixed.
