### ISSUE TITLE
Suggested Edit in Introduction

### ISSUE THREAD

**Issue by Prof-Sears** [nature-of-code/noc-book-2#80]
From the introduction:

> If you have a system with a certain number of possible outcomes, the probability of the occurrence of a given event equals the number of outcomes that qualify as that event divided by the total number of all possible outcomes. A coin toss is a simple example—it has only two possible outcomes, heads or tails. There is only one way to flip heads. The probability that the coin will turn up heads, therefore, is one divided by two: 1/2 or 50%.

First sentence should start: "If you have a system with a certain number of **equally-likely** possible outcomes,...".

**Comment by shiffman** [comment]
updated, will show up on the next website build!
