### ISSUE TITLE
Suggested Edit in Introduction #2

### ISSUE THREAD

**Issue by Prof-Sears** [nature-of-code/noc-book-2#81]
> 3.145 would be more likely to be picked than 3.144, even if that likelihood is just a tiny bit greater.

If you're trying to map the number value to the probability it is accepted, consider using numbers less than 1 in this example.

**Comment by shiffman** [comment]
How is this?

> However, this reduces the probabilities to a fixed number of options. What if you wanted to make a more general rule—the higher a number, the more likely it is to be picked? 0.8791 would be more likely to be picked than 0.8532, even if that likelihood is just a tiny bit greater. In other words, if x is the random number, the likelihood of it being picked could be mapped to the y-axis with the function y = x.

**Comment by Prof-Sears** [comment]
That works.

**Comment by shiffman** [comment]
Thank you!
