### ISSUE TITLE
No "Despicable Me" in Vector introduction

### ISSUE THREAD

**Issue by Prof-Sears** [nature-of-code/noc-book-2#82]
https://www.youtube.com/watch?v=A05n32Bl0aY

**Comment by shiffman** [comment]
I know! I'm just so attached to my Airplane quote. I'm also actually considering removing the quotes from the book and opening each chapter with an inspirational artwork or historical/scientific reference.

**Comment by shiffman** [comment]
well, it was time, despicable me quote is now in the vector chapter!
