### ISSUE TITLE
keep two <ol> elements together (chapter 11)

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#837]
@jasongao97 I was going to wrap 4 and 5 below in an `avoid-break` to have them together on the next page, but it resets the numbers. I guess I could use our override the numbering? This is low priority but nice to fix if you have an idea.

![Screen Shot 2024-02-24 at 9 26 37 PM](https://github.com/nature-of-code/noc-book-2023/assets/191758/e7b89185-c33b-42d7-8ff1-ee236b736b11)

**Comment by shiffman** [comment]
I just tried something like this for a part of chapter 10, i'm probably taking this too far but will see if it works.

<img width="934" alt="Screen Shot 2024-02-24 at 9 49 59 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/394da25e-5006-46b1-8c66-21fd4d7e367a">

**Comment by shiffman** [comment]
and now i've done it here as well in chapter 10:

<img width="864" alt="Screen Shot 2024-02-24 at 10 01 23 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/70ab302e-6d3d-42b3-b070-fcc112856129">

And the original spot in chapter 11:

<img width="875" alt="Screen Shot 2024-02-24 at 10 00 34 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/ce39d10f-435c-4e14-9626-d7ffa50bf09a">

**Comment by jasongao97** [comment]
Sure! Do you mean to prevent a single list item to be placed alone at the top or bottom of a page? And also from break inside? Maybe we could do something like this:

```scss
ol,
ul {
  ...

  li {
    break-inside: avoid;
  }

  li:first-child {
    break-after: avoid;
  }

  li:last-child {
    break-before: avoid;
  }
}
```

**Comment by shiffman** [comment]
Yes, this could work! Essentially I want to optionally set any of the following:

* don't allow a break inside of an individual bullet
* don't alllow two bullets to be separated (which is really to avoid a single bullet left on one page).

It's actually working the way I implemented it but feel free to change it to something better if you like!

**Comment by shiffman** [comment]
It would be nice to have better rules to define how this should work to avoid "orphans" essentially but let's just leave my manual "hack" in for now since it will make the PDF render correctly!

**Comment by shiffman** [comment]
I'm going to close this issue now as the project is wrapping up. I'll tag in @alanvww who I know is working on a related project for ITP thesis, this is relevant to the kinds of issues we discussed in our recent meeting!
