### ISSUE TITLE
Stochastic is not non-deterministic (section 8.5)

### ISSUE THREAD

**Issue by sidwellr** [nature-of-code/noc-book-2#84]
Section 8.5 contains the phrase "stochastic (or non-deterministic) fractal". This is technically incorrect; stochastic means random; non-deterministic is more like undefined. These are not equivalent. Some examples of non-deterministic behavior are using uninitialized variables in some languages (like C) and concurrent programs with an unresolved race condition. It takes on an even more specific meaning in the phrase "Non-deterministic Polynomial" (NP), an important topic in theoretical computer science. Non-determinism is outside the scope of Nature of Code; there is no need to mention it. But to be technically accurate, you may want to change the phrase to "stochastic (or random) fractal".

**Comment by shiffman** [comment]
I've edited the line:

> In this section, I will examine techniques for generating a stochastic (or non-deterministic) fractal, with a case study of a branching tree. Starting with the a deterministic version, let’s look at the production rules:

to read:

> In this section, I will examine techniques for generating a stochastic (or random) fractal, with a case study of a branching tree. Starting with the a deterministic version, let’s look at the production rules:

Is it still accurate to reference to a "precisely self-similar" fractal as "deterministic", this is the term I've seen used but is there a better one? Here's another paragraph from earlier in the text.

> This is an example of a stochastic fractal, meaning that it is built out of probabilities and randomness. Unlike the deterministic tree-branching structure, it is statistically self-similar. As I go through the examples in this chapter, I will explore both deterministic and stochastic techniques for generating fractal patterns.

**Comment by sidwellr** [comment]
Deterministic and stochastic are fancy terms for predictable and random. They are both widely used in fractal geometry, so it's good to use them; it will help readers who want to learn more. But you may want to define deterministic. I think the earlier paragraph you quoted is the first occurrence; you could state: "Unlike the deterministic (or predictable) tree-branching structure..."

**Comment by shiffman** [comment]
Great idea, incorporating this feedback, thank you!
