### ISSUE TITLE
`allow-break` in codesplit?

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#859]
Could this possibly work?

```js
  checkEdges() {
    //{!11.allow-break} When it reaches one edge, set the position to the other edge.
    if (this.position.x > width) {
      this.position.x = 0;
    } else if (this.position.x &#x3C; 0) {
      this.position.x = width;
    }

    if (this.position.y > height) {
      this.position.y = 0;
    } else if (this.position.y &#x3C; 0) {
      this.position.y = height;
    }
  }
```

I've changed the comment to just covering 5 lines right now and the desired layout is working, so this is just an enhancement if easy to do.

<img width="1728" alt="Screen Shot 2024-02-26 at 6 19 07 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/809a3b23-1258-4ddd-b829-2a8bce541701">

**Comment by jasongao97** [comment]
Updated in Notion! Will check in the next build.

**Comment by shiffman** [comment]
Thanks for adding this!
