### ISSUE TITLE
comment placement

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#884]
Here is one comment that could maybe be placed differently?

![Screen Shot 2024-03-04 at 6 03 20 PM](https://github.com/nature-of-code/noc-book-2023/assets/191758/208f9115-13cd-4317-bc82-bfb352b685b1)

**Comment by shiffman** [comment]
Another one that could be moved down?

![Screen Shot 2024-03-04 at 6 12 11 PM](https://github.com/nature-of-code/noc-book-2023/assets/191758/8f84801a-cc48-4554-bc96-f6d43881ee92)

**Comment by jasongao97** [comment]
How about the following placement?

<img width="753" alt="image" src="https://github.com/nature-of-code/noc-book-2023/assets/6762203/db2b2188-471d-4c72-95ab-3633a4d79d05">

<img width="725" alt="image" src="https://github.com/nature-of-code/noc-book-2023/assets/6762203/d5e88527-c520-49d0-9f53-eea2c36397c5">

**Comment by shiffman** [comment]
I made the changes in Notion, i'll doouble check next build:

```js
    //{!1} The rules of life!
    if (board[i][j] === 1 && neighborSum < 2) next[i][j] = 0;
    //{.continue}
    else if (board[i][j] === 1 && neighborSum > 3) next[i][j] = 0;
    else if (board[i][j] === 0 && neighborSum === 3) next[i][j] = 1;
    else next[i][j] = board[i][j];
```

```js
  repel(particle) {
    // {!1}
    let force = p5.Vector.sub(this.position, particle.position);
    // {.continue.bottom-align} This is the same repel algorithm from Chapter 2: forces based on gravitational attraction.
    let distance = force.mag();
    distance = constrain(distance, 5, 50);
    let strength = -1 * this.power / (distance * distance);
    force.setMag(strength);
    return force;
  }
  ```

**Comment by shiffman** [comment]
I did some additional adjusting and I think they are good now!
