### ISSUE TITLE
A.2 or A.3 reference

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#886]
Hi @zee-em, this comment came in via no starch proofreading:

> should this be A.3? There's currently no in-text callout to Figure A.3.

Let me know what you think!

![Screen Shot 2024-03-04 at 6 19 38 PM](https://github.com/nature-of-code/noc-book-2023/assets/191758/3c7179fa-2723-4b7f-b6be-20a2a3dd7fa8)

**Comment by zee-em** [comment]
I think it could say, "In figure A.2, do the curved lines...." And then, below "... to clarify your creatures orientation, as in figure A.3"  

Does this make  sense?

**Comment by shiffman** [comment]
This is great I think updated! Thank you @zee-em!
