### ISSUE TITLE
p5.js examples workflow

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#89]
Note for @jasongao97 and I to finalize the p5.js example workflow. Ideally I would just work on / change examples in the p5 web editor and that would propagate to a GitHub repo and the embeds on the site. TBD.

**Comment by shiffman** [comment]
Related to this I'll want to adjust this language in the introduction. The p5 web editor examples are primary but for print readers it may be useful to have a page that links to all examples.

> Each time you see the above Example heading in this book, it means there is a corresponding code example available on [GitHub](https://github.com/nature-of-code/noc-examples-p5.js).

**Comment by shiffman** [comment]
I'm noticing that the p5 web editor examples do not include the code-split notation—which is fine, they shouldn't but I'll likely need to do a pass over the book to cross-check all the embedded code with the examples (if I'm making minor adjustments to the web editor versions.)

**Comment by jasongao97** [comment]
<img width="807" alt="Screen Shot 2022-09-28 at 9 54 09 AM" src="https://user-images.githubusercontent.com/6762203/192797649-3af1dd35-356a-4d22-8258-e74f3ed4588c.png">

I'm switching example URLs from ID to slug alias. So if we accidentally delete or replace the source sketch, we just need to keep them the same name and don't need to update the URL in the content.

**Comment by shiffman** [comment]
Notes from our meeting. All code for the book can be categorized as:

* Example (tied to a specific example # in the book)
* Exercise (tied to a specific exercise # in the book)
* Figure (tied to a sepcific figure # in the book)
* Extra (community contribution or extra example provided by me)

We just need a naming convention for the slugs. To be continued. . .

**Comment by shiffman** [comment]
I think this can be closed. @jasongao97 anything here left to consider?

**Comment by shiffman** [comment]
Well, we certainly have the examples working now, closing!
