### ISSUE TITLE
design guidelines for examples

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#90]
The examples are a mish-mosh of different background colors and shape colors. I'll use this thread to track a convention for

* background color
* shape outline color
* shape fill color
* strokeWeight

Obviously there will be some variation, but this is a good starting point. I think it makes sense to have white backgrounds. This will look best I believe in print? But I'm open to something different for the web (though that adds complexity in terms of maintaining the codebase.)

![Screen Shot 2022-09-21 at 10 56 05 AM](https://user-images.githubusercontent.com/191758/191539928-082d772a-0887-49fa-b4d6-ebc733eb2ff7.png)

**Comment by jasongao97** [comment]
Here are some tests for the following color palette:

- background color: 255
- shape outline color: 0
- shape fill color: 127
- strokeWeight: 2

![Untitled Diagram (1)](https://user-images.githubusercontent.com/6762203/197911513-6d0643b5-1fb1-47b0-b301-57fe7a8eb493.png)

**Comment by shiffman** [comment]
This works for me! @zee-em do you have any thoughts in terms of the interplay of these with the illustrations?

**Comment by shiffman** [comment]
This can be closed as the styles have been applied across the board. Individual issues can be opened if there are sketches that are off.
