### ISSUE TITLE
Figure 10.4 spelling error

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#906]
Hi @zee-em, latest round of proofing caught these mispellings!

hydrophyllic -> hydrophilic
xerophyllic -> xerophilic

('i' instead of 'y' and one 'l' instead of two!)

We could also change the labels to the nouns "hydrophytes" and "xerophytes", i'm not sure which is better, either way!

<img width="828" alt="Screen Shot 2024-03-09 at 10 45 20 AM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/d3bbe797-ca92-4d0d-8c55-2fd451a8ece9">

**Comment by zee-em** [comment]
updated and sent via notion

**Comment by shiffman** [comment]
The new image is great, closing!!!
