### ISSUE TITLE
GA Example "Steps" Code Comments

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#908]
These comments need some cleanup re-formatting.

* "Step 1: Initialization" should be paired and grey boxed with the for loop
* "Step 2: Selection" should be above the for loop not paired with anything
* "Step 2a: Calculate fitness" should be paired with the for loop

@jasongao97 can you take a look? @tuantinghuang feel free to weigh in if you have any design thoughts.

![Screen Shot 2024-03-11 at 7 46 57 PM](https://github.com/nature-of-code/noc-book-2023/assets/191758/55720310-415b-4714-88f0-aaf7df94d339)

**Comment by jasongao97** [comment]
#913 and an update in notion should fix it. There were some invisible notations after `Step 1`

<img width="873" alt="image" src="https://github.com/nature-of-code/noc-book-2023/assets/6762203/4cdb77e4-a8e5-4a2c-b66f-c495505ec0f1">

**Comment by jasongao97** [comment]
Updated in #915!

**Comment by shiffman** [comment]
This is all set!
