### ISSUE TITLE
Formulas that aren't really formulas. 

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#91]
The spacing is wonky for elements that are more freeform text inside of a latex formula.

```
number~of~aces / number~of~cards = 4 / 52 = 0.077 \approx 8\%
(1/2) * (1/2) * (1/2) = 1/8~(or~0.125)
```

Not sure how to improve these.

Website render:
![Screen Shot 2022-09-21 at 11 18 46 AM](https://user-images.githubusercontent.com/191758/191544037-b611c21a-e904-4fa1-aea6-f24ddde4bee2.png)

Notion:
<img width="786" alt="Screen Shot 2022-09-21 at 11 17 48 AM" src="https://user-images.githubusercontent.com/191758/191543892-2e7b4de5-bf6e-4e1e-8064-3e7390875f99.png">

**Comment by shiffman** [comment]
Also @jasongao97 I think ultimately we should left align these?

**Comment by jasongao97** [comment]
I think this is because I changed the equation in notion but haven't run the import script again. Will try

**Comment by sidwellr** [comment]
If it uses LaTeX to render math, try using \textrm to include text in equations. For example:

`\textrm{number of aces} / \textrm{number of cards} = 4/52 \approx 8\%`

**Comment by shiffman** [comment]
Ah, great suggestion @sidwellr thank you, we will try this!

**Comment by shiffman** [comment]
@jasongao97 I updated these with @sidwellr's and they look quite nice I think! (In notion at least) We can close this issue once we see they look good in the HTML build.

![Screen Shot 2022-10-11 at 1 43 15 PM](https://user-images.githubusercontent.com/191758/195162526-9b90d92e-6719-4535-828a-c2fb3451cdbe.png)

**Comment by shiffman** [comment]
Just noting that #110 can close this issue when merged.
