### ISSUE TITLE
notion-fetch update?

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#918]
I wonder if me renaming the repo caused this issue, naming it back to noc-book-2023 temporarily to check.

https://github.com/nature-of-code/noc-book-2023/actions/runs/8256059741

<img width="1344" alt="Screen Shot 2024-03-12 at 5 41 25 PM" src="https://github.com/nature-of-code/noc-book-2023/assets/191758/197fb081-deb9-4bc9-a0bd-4d973b6ba7cd">

**Comment by shiffman** [comment]
whether renaming the repo broke something, changing it back doesn't seem to fix it. maybe just a coincidence and an update is needed. @jasongao97 can you take a look?

**Comment by jasongao97** [comment]
This issue is caused by some images in Chapters 7 and 8 that are still referencing the old GitHub repo. I have replaced all of them and checked. The most recent build was passed: #919.

**Comment by shiffman** [comment]
This can be closed after @jasongao97 just briefly reviews #920 and #919 to make sure they are identical.

**Comment by shiffman** [comment]
This is all set now!
