### ISSUE TITLE
Figure 6.5 Error

### ISSUE THREAD

**Issue by ManoylovAC** [nature-of-code/noc-book-2#923]
### Figure 6.5
It seems that the upper left coordinate has lost its minus. Should be `-10, -10`

<img width="761" alt="image" src="https://github.com/nature-of-code/noc-book-2/assets/6568745/ad88a788-ec39-48e6-9c0e-4ba7f887a3ec">

https://github.com/nature-of-code/noc-book-2/blob/f286509d8cd49aab1fc0b30f84edf525fa940377/content/06_libraries.html#L564

**Comment by shiffman** [comment]
Great catch! @zee-em this is another one little mistake that slipped through! Can you fix along with #922? Thank you!!

**Comment by shiffman** [comment]
Corrected in Notion! (Actually leaving these open until the new PDF is generated)
