### ISSUE TITLE
Figure 6.9 click does not work

### ISSUE THREAD

**Issue by ManoylovAC** [nature-of-code/noc-book-2#924]
### Figure 6.9 click does not work

The [book says](https://github.com/nature-of-code/noc-book-2/blob/main/content/06_libraries.html#L671) the click should work, but it no longer works

> (In the online version, you can toggle the correct and incorrect renderings by clicking the mouse.)
<img width="797" alt="image" src="https://github.com/nature-of-code/noc-book-2/assets/6568745/d14e555f-288b-43f3-a446-abde39c482eb">

https://github.com/nature-of-code/noc-book-2/blob/f286509d8cd49aab1fc0b30f84edf525fa940377/content/06_libraries.html#L667-L670

**Comment by shiffman** [comment]
I've corrected this, it will show up in the next site build. Here's the example directly:

https://editor.p5js.org/natureofcode/sketches/HWeBLcNuu
