### ISSUE TITLE
Example 6.10 the backlight did not work

### ISSUE THREAD

**Issue by ManoylovAC** [nature-of-code/noc-book-2#925]
According to the description, 4 lines should be highlighted, but this did not work (perhaps due to an extra space in the markup).

<img width="791" alt="image" src="https://github.com/nature-of-code/noc-book-2/assets/6568745/562ae976-3898-4d5b-b24d-ce2211906f2c">

https://github.com/nature-of-code/noc-book-2/blob/f286509d8cd49aab1fc0b30f84edf525fa940377/content/06_libraries.html#L1029-L1033

**Comment by shiffman** [comment]
Noting this is a website error only, the PDF is correct.
