### ISSUE TITLE
Chp 6: const vs let for destructuring (proposal)

### ISSUE THREAD

**Issue by ManoylovAC** [nature-of-code/noc-book-2#926]
In the section on [destructuring](https://github.com/nature-of-code/noc-book-2/blob/main/content/06_libraries.html#L247), you suggest using the `const` keyword for cases with library, but some of the examples use let again. For consistency, you can add const to all such cases with library classes destructuring.

<img width="351" alt="image" src="https://github.com/nature-of-code/noc-book-2/assets/6568745/19d6cd1d-02f7-4e8e-af2f-76dab2b49552">

vs

<img width="395" alt="image" src="https://github.com/nature-of-code/noc-book-2/assets/6568745/86ca957a-9ee6-4fbc-a5ff-7693587d300b">

**Comment by shiffman** [comment]
Ah, thanks for catching this! I will fix definitely for the website, but it might not make it into the print book, we'll see if I can squeeze it in, it's off to the printer on April 9!

**Comment by shiffman** [comment]
Made some adjustments in #931 take a look!
