### ISSUE TITLE
cpt 10: column titles

### ISSUE THREAD

**Issue by ManoylovAC** [nature-of-code/noc-book-2#929]
Several tables have the same column header names: "phrase". Perhaps these names should be reviewed.

<img width="221" alt="image" src="https://github.com/nature-of-code/noc-book-2/assets/6568745/20693b91-c6d7-4186-9827-49e730180676">
<img width="499" alt="image" src="https://github.com/nature-of-code/noc-book-2/assets/6568745/da33cfff-39e8-4059-828a-1bad97a8fbcb">
<img width="297" alt="image" src="https://github.com/nature-of-code/noc-book-2/assets/6568745/f7a33e94-d461-49b1-beb6-d5e5cfa664df">
<img width="329" alt="image" src="https://github.com/nature-of-code/noc-book-2/assets/6568745/bd511a9e-cf9e-4b29-b5d9-aa82de36b283">

https://github.com/nature-of-code/noc-book-2/blob/fd14992f4130bd679758da87245ac1aafd2b1060/content/10_nn.html#L80

https://github.com/nature-of-code/noc-book-2/blob/fd14992f4130bd679758da87245ac1aafd2b1060/content/10_nn.html#L102

https://github.com/nature-of-code/noc-book-2/blob/fd14992f4130bd679758da87245ac1aafd2b1060/content/10_nn.html#L121-L124

https://github.com/nature-of-code/noc-book-2/blob/fd14992f4130bd679758da87245ac1aafd2b1060/content/10_nn.html#L201-L202

https://github.com/nature-of-code/noc-book-2/blob/fd14992f4130bd679758da87245ac1aafd2b1060/content/10_nn.html#L293-L294

**Comment by shiffman** [comment]
Wow, this is a major error, thank you for catching this! Just under the wire before it goes to print.

**Comment by shiffman** [comment]
This should be fixed in #930, @ManoylovAC feel free to take a look and make sure I got it right!

**Comment by ManoylovAC** [comment]
Yes, great - now the tables look as they should
