### ISSUE TITLE
Purchase links

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#939]
"Buy the Book" should change to "Pre-Order" maybe right now?

Also, what would be an elegant way to link to multiple places to purchase the book, for example:

https://nostarch.com/nature-code
https://bookshop.org/p/books/the-nature-of-code-daniel-shiffman/20597363?ean=9781718503700
https://www.amazon.com/Nature-Code-Daniel-Shiffman/dp/1718503709
https://www.barnesandnoble.com/w/the-nature-of-code-daniel-shiffman/1114086024

(Eventually I may have a way to order directly from the site.)

Should we design and create a "buy the book" page?

**Comment by jasongao97** [comment]
How about a small hover menu like this?

https://github.com/nature-of-code/noc-book-2/assets/6762203/64ce1840-a8e0-4161-9fa5-a3cf9a30ce43

**Comment by shiffman** [comment]
Yes, this is great! Would the No Starch direct link be from "pre order" directly? I wonder if we should list it explicitly?

**Comment by jasongao97** [comment]
> Would the No Starch direct link be from "pre order" directly?

Yes, it was. Perhaps it could be the buy-directly-from-site button and the No Starch link will be list explicitly below? I was trying to prevent the confusion for a user to click directly on the button which does nothing.

**Comment by shiffman** [comment]
Yes, that works! We may change this eventually if I am able to take orders directly from the website itself in the future!

**Comment by shiffman** [comment]
Closing this issue now that we have purchase links + mobile support!
