### ISSUE TITLE
Purchase Link not visible on mobile

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#944]
I'm not seeing the "pre-order" option on mobile. (Related to #939 but filing as a separate issue)

**Comment by shiffman** [comment]
Step 1: Design for pre-order button on mobile
Step 2: Consider the idea of a larger "purchase" page which would outline various options and info.

**Comment by tuantinghuang** [comment]
for step 1, what do you think about this placement?

<img width="250" alt="Screenshot 2024-05-01 at 08 52 19" src="https://github.com/nature-of-code/noc-book-2/assets/90000947/d6a3afbb-07a4-4f83-ba6e-4df0a09e7a69">

**Comment by shiffman** [comment]
Yes, this looks great! We should probably have the button say "PREORDER" for now and would it behave like discussed #939  or just be a single link?

**Comment by shiffman** [comment]
Working great!
