### ISSUE TITLE
Incorporate Videos?

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#946]
Do we add them in the chapters themselves (new elements in Notion that are ignored for PDF build) or a separate page? Or just link to coding train site, hmmmmm.

**Comment by shiffman** [comment]
First step is to design a mock-up of a few ideas that range from:

* small, subtle YT play button (with chapter sub-heading?)
* to, larger thumbnail of video itself or even YT embed player

**Comment by tuantinghuang** [comment]
@jasongao97 let me know if you need more specific details!

Inactive state
<img width="943" alt="Screenshot 2024-06-01 at 16 24 54" src="https://github.com/nature-of-code/noc-book-2/assets/90000947/b831a605-46d4-4662-b38a-b8a042644df9">

Active state (when hovered )
<img width="943" alt="Screenshot 2024-06-01 at 16 25 09" src="https://github.com/nature-of-code/noc-book-2/assets/90000947/2d13f392-633d-48dc-9d96-75df6a00a64c">

**Comment by shiffman** [comment]
A tiny nitpicky comment but the space between the pink play button and "Video 1.1" looks quite wide, I might tighten that up a little bit?

**Comment by shiffman** [comment]
The implementation is now completed with #985 but I need to go through and add all the videos! @tuantinghuang this is something I'm happy for you to work on we can discuss!

**Comment by tuantinghuang** [comment]
@shiffman Yes let's discuss! I'm happy to go through Notion and add the videos too!

**Comment by tuantinghuang** [comment]
@jasongao97 Is it okay to attach a video to an example? If so, where should I place the callout box?

Take this [fractal tree - L system video](https://youtu.be/E1B4UoSQMFw?si=I4VAIFvbJ2hBmtyL) as an example. I think it would be better to attach it next to example 8.9 on the website. Is it possible to place the video next to the example header?

<img width="855" alt="Screenshot 2024-09-27 at 13 47 41" src="https://github.com/user-attachments/assets/14f78106-e59e-461b-994b-635d85db19a7">

**Comment by tuantinghuang** [comment]
@shiffman I went through all videos on Nature of code track on the CT website. And here's a list of things that I'm unsure of!

- Some video tracks that I don't know where to insert:
  - 3.7 Additive waves
  - 5.3 Pursue & Evade (if we can attach videos next to exercise 5.3 that would be ideal)
  - chapter 8: Object oriented fractal tree, Dragon Curve
  - chapter 10: XOR problem
  
- Video 6.3 appeared on the website before 6.2, is that okay?

- There are some videos that make sense to be watched together, can they be placed side by side? (Something like the attached image below) @jasongao97 Would you have any thoughts on this? Currently they are 2 consecutive video callout boxes in Notion.
  - 9.3 + 9.4 Shakespeare Monkey Example + code
  - 9.7 + 9.8 Pool Selection + Improve Pool Selection
  - Chapter 10: Perceptron Part 1 +2, Multilayer Perceptron Part 1 + 2

![Screenshot 2024-09-27 at 14 20 13](https://github.com/user-attachments/assets/2806b389-8a72-45af-b92f-12dab6b2e44b)

**Comment by tuantinghuang** [comment]
We noticed another bug for the video - When hovered the thumbnail is sometimes blocked by images in the front.

<img width="705" alt="Screenshot 2024-10-04 at 11 23 54" src="https://github.com/user-attachments/assets/639c5544-6b6d-4757-bcef-2fa7200921a9">

**Comment by jasongao97** [comment]
> @jasongao97 Is it okay to attach a video to an example? If so, where should I place the callout box?

The video callout box should be placed inside the Example block. I believe the following will work.

<img width="733" alt="image" src="https://github.com/user-attachments/assets/b8cc497c-648c-4497-af57-ebde85cc2237">

**Comment by shiffman** [comment]
@jasongao97 is working on last remaining items:

* [x] more than one video
* [x] fixing layout bug

@tuantinghuang you can go ahead and add more "double" videos in Notion as well as videos that go with Examples (or exercises).

**Comment by shiffman** [comment]
These last two bugs/features have been implemented. @tuantinghuang do you want to do one more pass over adding any videos to Notion and then we can close?

**Comment by tuantinghuang** [comment]
@shiffman The double videos look great! I added all videos on Notion, but just haven't pulled them into Github yet!

**Comment by shiffman** [comment]
More videos came through as part of #1041! I'm closing this issue now and we can open individual issues related to videos going forward if need be!
