### ISSUE TITLE
Add screenshot to the sketch itself?

### ISSUE THREAD

**Issue by jasongao97** [nature-of-code/noc-book-2#96]
I'm developing a new way of managing embedded sketches and static screenshots for pdf build. Could we add a `screenshot.png` file to the p5 ketch, so we only need one link in Notion to reference both the embed and the static image? The static image will be added during the `import-notion-docs` stage and appear only in the pdf build.

It will look like this in Notion: (It's only one block and can be added anywhere e.g. multi-column)

<img width="934" alt="image" src="https://user-images.githubusercontent.com/6762203/193432502-80d1fba8-1f71-46aa-9593-cf8e1a197fce.png">

And in p5 editor:

<img width="499" alt="image" src="https://user-images.githubusercontent.com/6762203/193432536-c64a894a-b069-4895-94b6-ec1caaea302c.png">

What do you think of it? @shiffman

**Comment by shiffman** [comment]
Yes, I love this idea! One issue is that the p5 editor only allows 5 MB uploading but I don't think that will be an issue for any of the screenshots I want to include.
