### ISSUE TITLE
Minor value typo in GA chapter

### ISSUE THREAD

**Issue by bcbailey** [nature-of-code/noc-book-2#960]
Very minor typo here for the normalized fitness value, `0.1` should be `0.15`
https://github.com/nature-of-code/noc-book-2/blob/main/content/09_ga.html#L249

PS: Love the book

**Comment by shiffman** [comment]
Arg! Wish I had caught this one before going to print! Thanks for the comment ❤️ 

Fixing in Notion, site will update on next build.
