### ISSUE TITLE
Minor typo in chapter 3

### ISSUE THREAD

**Issue by bergonom** [nature-of-code/noc-book-2#961]
Towards the bottom of the "[Properties of Oscillation](https://natureofcode.com/oscillation/#properties-of-oscillation)" section, there is a bit of text that reads: "Think about what’s going here." It should be "Think about what’s going **on** here."

**Comment by shiffman** [comment]
Correcting in notion which will update the site in a future build! I think I'll create a label to track text corrections that I'm making post print run?
