### ISSUE TITLE
Minor styling issue in chapter 7

### ISSUE THREAD

**Issue by bergonom** [nature-of-code/noc-book-2#962]
In the section "[What Is a Cellular Automaton?](https://natureofcode.com/cellular-automata/#what-is-a-cellular-automaton)" Excel is stylized as Ex<em>cel</em> - with the last three letters italicized. [Microsoft does not seem to style it that way](https://www.microsoft.com/en-us/microsoft-365/excel). Perhaps the intention was to italicize the entire product name (i.e. _Excel_)?

**Comment by shiffman** [comment]
This was actually intentional! The idea was to link the "cel" (italics for emphasis) to "cells in a spreadsheet" but maybe that's doesn't come through? Thanks for the feedback!

**Comment by shiffman** [comment]
Going to close this issue and leave as is! Thanks for the feedback @bergonom!
