### ISSUE TITLE
Not working: Example 6.12: Soft Swinging Pendulum

### ISSUE THREAD

**Issue by Ramblurr** [nature-of-code/noc-book-2#967]
Hi there, I hope you don't mind bug reports from random readers!

But I thought you should know, this example isn't working: [Example 6.12: Soft Swinging Pendulum](https://natureofcode.com/physics-libraries/#example-612-soft-swinging-pendulum)

Opening the sketch in the editor shows the error `ReferenceError: toxi is not defined`

(I'm eagerly awaiting my printed copy!)

Edit: in fact all of the following sketches that include toxi aren't working.

**Comment by shiffman** [comment]
Strange, they are working for me! What browser / OS / etc? Can you maybe do a screen recording where you click from the website into the sketch and run it showing the error?

**Comment by Ramblurr** [comment]
@shiffman Of course it is user error :( The `cdn.jsdelivr.net` domain was blocked by my ad blocker, while `cdnjs.cloudflare.com` wasn't which is why the other sketches were working.

My apologies for the noise!
