### ISSUE TITLE
Chapter Opening Images

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2#976]
@tuantinghuang we converted and adjusted some of the chapter opening images to be B&W for the print book, but we could return to color for the website? Specifically Chapters 1 and 9. (The others are actually color.) What do you think?

**Comment by tuantinghuang** [comment]
Yes, I think it makes sense to keep it coherent and have color images! Should I edit in Notion directly and replace the B&W images with color ones for chapter 1 and 9?

**Comment by shiffman** [comment]
These are all set!
