### ISSUE TITLE
Exercise 1.6 (probably?) refers to wrong place in Chapter 0

### ISSUE THREAD

**Issue by Ramblurr** [nature-of-code/noc-book-2#979]
Exercise 1.6 says:

> [Exercise 1.6](https://natureofcode.com/vectors/#exercise-16)
> Referring back to Exercise 0.6, implement an acceleration calculated with Perlin noise.

But [Exercise 0.6](https://natureofcode.com/random/#exercise-06) doesn't use perlin noise, it's the accept-reject exercise with a quadratic probability distribution.

I think Exercise 1.6 means to refer to [Example 0.6](https://natureofcode.com/random/#example-06-a-perlin-noise-walker)?

**Comment by shiffman** [comment]
Great catch! I've fixed this in Notion and added to #1017. It should be corrected on the website during the next build.
