### ISSUE TITLE
incorrect label on Fig 1.16

### ISSUE THREAD

**Issue by neildt56** [nature-of-code/noc-book-2#981]
Figure 1.16 seems to refer to dx twice, instead of dx and dy.
The text associated with the figure appears to be correct.

**Comment by shiffman** [comment]
Ah. good catch! Since the `dx` is rendered with the font I might be able to make this fix myself! Tagging in @zee-em, look we found a mistake in an illustration!

![image](https://github.com/user-attachments/assets/bf044ca4-9e81-49a0-b8fb-7f023f89fd1e)

**Comment by zee-em** [comment]
Hi! I've fixed this and uploaded to Notion, and also saved new & Procreate files to the Google drive  :)

**Comment by zee-em** [comment]
here's the new image FYI
![Figure_1-16](https://github.com/user-attachments/assets/5020c3a8-b502-46b7-b0f1-7641de42a9a5)

**Comment by shiffman** [comment]
Corrected and added to errata!
