### ISSUE TITLE
Strikethrough not rendering on web build

### ISSUE THREAD

**Issue by Thomascountz** [nature-of-code/noc-book-2#983]
> When calling a static method, instead of referencing an object instance, you reference the name of the class. Here’s the right way to implement the vector addition example:

> 
> ```diff
> let v = createVector(0, 0);
> let u = createVector(4, 5);
> - let w = v.add(u);
> let w = p5.Vector.add(v, u);
> ```

**Comment by shiffman** [comment]
This is actually correct in the print version of the book....

<img width="652" alt="Screenshot 2024-10-07 at 8 20 05 PM" src="https://github.com/user-attachments/assets/a8320454-e0ee-4f62-9efe-c0e7e7927b31">

...but not rendering correctly online:

<img width="857" alt="Screenshot 2024-10-07 at 8 21 19 PM" src="https://github.com/user-attachments/assets/ca46901f-87f6-4697-824d-7c3609fe0acc">

@jasongao97 can you look into this?

**Comment by shiffman** [comment]
Noting another instance of this: https://github.com/nature-of-code/noc-book-2/pull/1041#issuecomment-2427730016

**Comment by shiffman** [comment]
Thank you @jasongao97!
